### ISSUE TITLE
How should I set parameters to improve speed？

### ISSUE THREAD

**Issue by crkmary** [marbl/canu#1301] opened 2019-03-26 07:09 UTC
I am running Canu (version 1.8) using Nanopore reads （a human genome sequenced with Nanopore at 40-50X) on the local machine which has 64-thread AMD Opteron 6380 @2.5GHz CPUs with 512Gbp of memory.
canu -p asm -d asm genomeSize=3.1g -nanopore-raw ../rawdata/Human.filt.fq.gz cor MinCoverage=0 corMaxEvidenceErate=0.22 useGrid=false batThreads=60 batMemory=500

It's the first time I'm running Canu. Canu is in correction/1-overlapper task for more than 50 days.

But I read in an article that it should run about 62K CPU hours (including 29K to correct, 33K to assemble).
canu -p asm -d asm genomeSize=3.1g gridOptionsJobName=na12878nano "gridOptions=–time 72:00:00–partitionnorm" -nanopore-raw rel3*.fastq.gz corMinCoverage=0 corMaxEvidenceErate=0.22 errorRate=0.045 "corMhapOptions=–threshold 0.8–num-hashes 512–ordered-sketchsize 1000–ordered-kmer-size 14"
They assembly ran on a cluster comprised of a mix of 48-thread dual-socket Intel E5-2680 v3 @ 2.50GHz CPUs with 128 Gbp of memory and 8-thread dual-socket Intel CPU E5-2698 v4 @ 2.20GHz CPUs with 1,024 Gbp of memory.

Why am I so much slower than in this article?How should I set parameters to improve speed?

Thanks，
Mary

**Comment by skoren** [comment] 2019-03-27 17:03
Duplicate of #1300

**Closed by skoren** 2019-03-27 17:03 UTC
