### ISSUE TITLE
Certain cormhap jobs take at least 50% longer than others

### ISSUE THREAD

**Issue by ilyavs** [marbl/canu#1262] opened 2019-02-24 06:21 UTC
Hi,
I am assembling nanopore reads from a metagenomic sample on a SGE cluster. I ran canu with 48gb cormhap memory and 8 cormhap cores to limit the number of jobs per node. When I run with 50m genome size the entire assembly finished in ~7 hours. When I run with 100m genome size, some of the cormhap jobs finish in less than 24 hours, some take longer and some are still running now after more than 38 hours. These are the last 4 jobs and they are all on the same node. However, other nodes that had 4-5 jobs already finished. Each job (java process) uses the full 8 cores and 8.3% of the memory according to the top command on the node.
I would expect that the difference in run time between jobs would be smaller.  Any suggestions?
* Sorry for the formatting, don't know what went wrong when pasting canu.out
Here is the output of canu -version:
Canu 1.8
Here is the canu.out:

```
Found perl:
   /net/mraid08/export/genie/long_read_assembly/miniconda3/envs/longread_assembly/bin/perl
   This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi

Found java:
   /etc/alternatives/java
   openjdk version "1.8.0_91"

Found canu:
   /net/mraid08/export/genie/long_read_assembly/canu/canu-1.8/Linux-amd64/bin/canu
   Canu 1.8

-- Canu 1.8
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   \u0160o\u0161ic M, \u0160ikic M.
--   Edlib: a C/C\u2009++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_91' (from '/etc/alternatives/java') with -d64 support.
-- Detected gnuplot version '4.6 patchlevel 0   ' (from 'gnuplot') and image format 'svg'.
-- Detected 56 CPUs and 504 gigabytes of memory.
-- Detected Sun Grid Engine in '/SGE6/sge6.2u4/default'.
-- Detected Grid Engine environment 'threads'.
-- User supplied Grid Engine consumable '-l mem_free=MEMORY'.
-- 
-- Found   2 hosts with   8 cores and   15 GB memory under Sun Grid Engine control.
-- Found   8 hosts with  72 cores and  376 GB memory under Sun Grid Engine control.
-- Found   8 hosts with  56 cores and  503 GB memory under Sun Grid Engine control.
-- Found   5 hosts with  24 cores and  251 GB memory under Sun Grid Engine control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     15 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       12 GB    8 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   48 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    48 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl    48 GB    8 CPUs  (overlap detection)
-- Grid:  ovb       48 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       48 GB    1 CPU   (overlap store sorting)
-- Grid:  red       48 GB    6 CPUs  (read error detection)
-- Grid:  oea       48 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      200 GB    8 CPUs  (contig construction with bogart)
-- Grid:  cns       48 GB    8 CPUs  (consensus)
-- Grid:  gfa        8 GB    8 CPUs  (GFA alignment and processing)
--
-- In 'P2A_100m.seqStore', found Nanopore reads:
--   Raw:        1619877
--   Corrected:  0
--   Trimmed:    0
--
-- Generating assembly 'P2A_100m' in '/net/mraid08/export/genie/long_read_assembly/Runs/P2A/1.assemble_100m'
--
-- Parameters:
--
--  genomeSize        100000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1200 ( 12.00%)
--    utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1200 ( 12.00%)
--    utgErrorRate    0.1200 ( 12.00%)
--    cnsErrorRate    0.2000 ( 20.00%)
--
--
-- BEGIN CORRECTION
--
-- All 13 mhap precompute jobs finished successfully.
-- Finished stage 'cor-mhapPrecomputeCheck', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
--
-- 'mhap.jobSubmit-01.sh' -> job 799143 tasks 1-43.
--
----------------------------------------
-- Starting command on Fri Feb 22 18:37:22 2019 with 217458.69 GB free disk space

    cd /net/mraid08/export/genie/long_read_assembly/Runs/P2A/1.assemble_100m
    qsub \
      -hold_jid 799143 \
      -l mem_free=4g \
      -pe threads 1 \
      -V \
      -q himem7.q \
      -S /bin/bash  \
      -cwd \
      -N 'canu_P2A_100m_P2A' \
      -j y \
      -o canu-scripts/canu.04.out  canu-scripts/canu.04.sh
Your job 799144 ("canu_P2A_100m_P2A") has been submitted

-- Finished on Fri Feb 22 18:37:22 2019 (furiously fast) with 217458.69 GB free disk space
----------------------------------------
```

**Comment by skoren** [comment] 2019-02-28 03:14
We've seen some jobs take longer and the runtime can vary if one partition has more repetitive reads by chance. However, a lot of difference we've observed has been due to other issues on a node (e.g. slow I/O or network interface or memory overload). Since your slow jobs seem to all be on one node, I'd suspect this is the cause. You could try deleting one of the jobs from the grid and re-running manually it on another node to confirm if the node is the issue or the job partition itself.

**Comment by ilyavs** [comment] 2019-02-28 05:22
I deleted all the jobs and restarted canu. They finished under 24 hours and the assembly finished properly.
However, I aim at having my assembly pipeline as automated as possible. Is there some way to prevent this or handle this issue automatically when it occurs?
Thanks,
Ilya.

**Comment by skoren** [comment] 2019-02-28 14:47
You would have to check what was going on with that node at the time of job slowness. There isn't an easy way within Canu to tell when a job is running longer than it should. You could set a conservative time limit for these jobs so they'd get killed and re-launched automatically after a fixed time (say double the mean). However, if you really do have a job that needs more time, it will still fail and you'll need to check on your asm.

**Comment by ilyavs** [comment] 2019-02-28 14:53
Thank you very much.
Ilya.

**Comment by skoren** [comment] 2019-03-03 00:48
Closing, nothing to change in Canu as the same job finished fast on restart indicating an intermittent node issue.

**Closed by skoren** 2019-03-03 00:48 UTC
