### ISSUE TITLE
utgcns segmentation fault

### ISSUE THREAD

**Issue by Huanle** [marbl/canu#684] opened 2017-10-26 23:17 UTC
**canu command:**
canu gridEngineMemoryOption="-l vmem=60gb -l mem=60gb"  corMhapSensitivity=high correctedErrorRate=0.055 minReadLength=1000  -p C1 -d c1_canu-_asm genomeSize=1189m -pacbio-corrected ALL.PACBIO.EC.fa

```
**Error message in canu.out:**
-- Consensus jobs failed, tried 2 times, giving up.
--   job ctgcns/0056.cns FAILED.
--

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

**the actually Failed Command:**
utgcns -G ../C1.ctgStore/partitionedReads.gkpStore/ -T ../C1.ctgStore/ 1 56 -O ctgcns/0056.cns.WORKING -maxcoverage 40 -e 0.055 -pbdagcon -edlib -threads 16

**Canu version:** Canu 1.6  

**System:** 
Linux delta039 2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 21:19:08 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux  (server)

**error message:** 
```
generateTemplateStitch()-- generated template of length 55619, expected length 55637, -0.0324% difference.
Generated template of length 55619
Aligning reads.
Finished aligning reads.  0 failed, 43 passed.
Constructing graph
Merging graph
Calling consensus
Working on tig 106372 of length 27361 (756 children)
  unitig 106372 detected 751 contains (101.41x, 97.37%) 5 dovetail (2.74x, 2.63%)
    unitig 106372 removing 632 (64.03x) contained reads; processing only 119 contained (37.38x) and 5 dovetail (2.74x) reads

Failed with 'Segmentation fault'; backtrace (libbacktrace):
Segmentation fault
```
It doesn't seem to be exactly the same as the previously reported 'Segmentation fault' issues. 
It would be nice if you can help me sort this out? 

Hope you can help with this as everything has been going well until this point. 
Many thanks.

Cheers - Elzed

**Comment by skoren** [comment] 2017-10-27 22:53
Try running in more verbose mode (edit the consensus.sh script to have -V -V -V in it (it should say something like ```-maxcoverage 40 \```, edit it to be ```-maxcoverage 40 -V -V -V \``` and re-run the failing partition (sh consensus.sh 56) and post the output (either here or send it to our FTP site from the FAQ: http://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you). 

You could also make a package of the reads to let us reproduce the crash locally. Make a copy of consensus.sh and edit it to say ```-maxcoverage 40 -P tigerish -u 106372 \```. You could then send us the resulting file the same was as above. 

As a workaround, you can modify the consensus to use the quick option (replace ```-pbdagcon``` with ```-quick```) which should let you complete the assembly in the meantime.

**Comment by Huanle** [comment] 2017-10-28 00:14
Thanks a lot for your prompt response.
I tried the 3 of your proposed alternatives and attached the log and output files.
Hope you can detect some useful information out of them.

I tried the following commands:
1. utgcns -G ../C1.ctgStore/partitionedReads.gkpStore/ -T ../C1.ctgStore/ 1 56 -O ctgcns/0056.cns.WORKING -maxcoverage 40 -V -V -V  -e 0.055 -pbdagcon -edlib -threads 8  

2. utgcns -G ../C1.ctgStore/partitionedReads.gkpStore/ -T ../C1.ctgStore/ 1 56 -O ctgcns/0056.cns.WORKING -maxcoverage 40 -P tigCrash -u 106372  -e 0.055 -pbdagcon -edlib -threads 8  

3. utgcns -G ../C1.ctgStore/partitionedReads.gkpStore/ -T ../C1.ctgStore/ 1 56 -O ctgcns/0056.cns.WORKING -maxcoverage 40 -e 0.055 -quick -edlib -threads 8

When you say the ' package of reads', do you mean the input pacbio reads ?
 
[1.VVV.LOG.txt](https://github.com/marbl/canu/files/1423752/1.VVV.LOG.txt)
[2.tig.crash.log.LOG](https://github.com/marbl/canu/files/1423753/2.tig.crash.log.LOG)
[2.tigCrash.txt](https://github.com/marbl/canu/files/1423756/2.tigCrash.txt)
[3.quick.log](https://github.com/marbl/canu/files/1423757/3.quick.log)

**Comment by skoren** [comment] 2017-10-28 19:47
Can you send the 1.* and 2.* files. If the 3.quick.log files have no errors, you should be able to edit the consensus.sh script to use quick as you did in 3 and run it manually (not just utgcns since the script also moves the WORKING file to the completed location on success) and finish the asm.

**Comment by Huanle** [comment] 2017-10-30 02:48
Hi Sergey,
Thanks again for your response. 
I uploaded 1.VVV.LOG , 2.tigCrash and 3.quick.log files. Are the former two the ones that you are referring to? i can see them were uploaded successfully a couple of days ago. If github doesn't show them i will try ftp. 
The 3.quick.log file ends with error message:
 " generateTemplateStitch()-- generated template of length 55619, expected length 55637, -0.0324% difference.
Working on tig 106372 of length 27361 (756 children)
  unitig 106372 detected 751 contains (101.41x, 97.37%) 5 dovetail (2.74x, 2.63%)
    unitig 106372 removing 632 (64.03x) contained reads; processing only 119 contained (37.38x) and 5 dovetail (2.74x) reads

Failed with 'Segmentation fault'; backtrace (libbacktrace):  " .
Thanks.

**Comment by skoren** [comment] 2017-10-30 13:35
OK, I found the issue, it is trying to align one offending read and failing to find a location for it. The easy workaround is to increase the error rate from 0.055 to 0.060. I'll commit a fix to the tip.

**Comment by skoren** [comment] 2017-10-31 16:26
I've committed the fix to the tip. However, DO NOT switch to the tip in the middle of your assembly, it is not backwards compatible. You can complete this assembly by increasing the error rate for consensus.

**Closed by skoren** 2017-10-31 16:26 UTC
