### ISSUE TITLE
Submission issues with PBSPro_13.0.2.153173

### ISSUE THREAD

**Issue by timeu** [marbl/canu#246] opened 2016-08-31 08:34 UTC
On our HPC we have are using PBSPro_13.0.2.153173 as our scheduling system and we run into some submission errors when trying to run on the sample data. 

1. PBS does not recognize the flag `-d working_dir` (error message: invalid option -d). We fixed it by removing the flag from this [line](https://github.com/marbl/canu/blob/master/src/pipelines/canu/Grid_PBSTorque.pm#L157)
2. PBS does not recognize the flag `-t ARRAY_JOBS` (error message: invalid option -t). We fixed it by replacing the flag from `-t ARRAY_JOBS` to `-J ARRAY_JOBS` in this [line](https://github.com/marbl/canu/blob/master/src/pipelines/canu/Grid_PBSTorque.pm#L158)
3. PBS does not recognize the flag `-F 0`. We fixed this by commenting out this [line](https://github.com/marbl/canu/blob/master/src/pipelines/canu/Execution.pm#L974) and replacing it with `$off=""`
4. On the sample data the submission script tries to pass `-J 1-1` for the array job which is not valid in this PBS version. So we needed to substitute the entire `-J ARRAY_JOB` with an empty string to remove that flag.
5. The jobs failed with invalid `-W depend afteranyarray:` command. PBS does not understand `afteranyarray`. We needed to change this to `afterany`

It seems that there needs to be separate configuration settings for different versions of PBS (see latest [documentation](http://www.pbsworks.com/pdfs/PBSProUserGuide13.1.pdf) for all the flags).

**Comment by mayelasoto** [comment] 2016-09-01 08:27
Also, there is no variable PBS_ARRAYID but PBS_ARRAY_ID. So I replaced it in these [lines](https://github.com/marbl/canu/blob/a2951ae9421dafe6fc4529f27a04f8bc1aa2d4cf/src/pipelines/canu/Grid_PBSTorque.pm#L167-L168) but it keeps failing, with the error:
Error: I need PBS_ARRAY_ID set, or a job index on the command line.

**Comment by brianwalenz** [comment] 2016-09-01 18:52
Thanks for the detailed report.  I just committed support, but untested, for everything.

Some comments:

1. This _might_ cause problems.  Generally, commands run using full paths to files, and so it shouldn't matter what directory they run out of.  If you see odd files appear in, e.g., your home directory, this is probably the cause.

3.  I didn't just comment out the line, I just removed the -F option.  (Well, technically, I didn't add -F).  This is used for large array jobs, the gridEngineArrayMaxJobs parameter.  If anything doesn't work in this patch, this will be it.

4.  (Just a rant)  This was a completely unnecessary pain in the ass, thanks, PBSPro.  It _IS_ useful to have an array job with one element, so that one doesn't need to special case small jobs...just like I ended up doing.  This is also the problem with your second comment.  I added some special case code to the start of each shell script to detect and correct the one-task-job-that-isn't-a-task-array quirk,

**Comment by timeu** [comment] 2016-09-01 19:01
@brianwalenz: 
Thanks for the patch. 
We will try it tomorrow and report back to you.

**Comment by mayelasoto** [comment] 2016-09-02 13:21
Thank you for the patch. 

In this [line] (https://github.com/marbl/canu/blob/198db0971bd1a24a0cec06e093e0afe36236dd72/src/pipelines/canu/Execution.pm#L985)  if $opt is empty then the PBS option -N "" fails, so instead of emptying it, I substituted -J ARRAY_JOB with an empty string, in this way the job name is still kept. In this same if statement, I set $off = "", otherwise it adds a 0 at the end of the qsub command. 

PBS_ARRAY_ID syntax is <jobnum>[].server. So jobid=`expr $baseid + $offset` fails when submitting precompute.sh:

expr: non-integer argument
Running job based on PBS_ARRAY_ID=981285[].pbs0.ice.gmi.oeaw.ac.at and offset=0.
/var/spool/PBS/mom_priv/jobs/981285[2].pbs0: line 30: [: -eq: unary operator expected
/var/spool/PBS/mom_priv/jobs/981285[2].pbs0: line 35: [: -eq: unary operator expected
Job partitioning error. jobid is invalid.

**Comment by brianwalenz** [comment] 2016-09-02 18:28
I hopefully fixed two of the problems.

For $off adding a 0 at the end of the qsub command, this needs to be passed to the script.  Without it, it cannot handle large arrays, and might not work at all.  I don't have a solution yet.

**Comment by brianwalenz** [comment] 2016-09-02 19:17
I can't find any mention of a limit on the number of tasks for an array job, so I've just essentially disabled it for all PBS variants.  This then removes the command line parameter to the shell script.  aka, $off = "" as you did before.

**Comment by mayelasoto** [comment] 2016-09-02 20:39
Thanks, will try it out and come back to you

**Comment by brianwalenz** [comment] 2016-09-09 20:36
Success?

**Comment by mayelasoto** [comment] 2016-09-12 10:01
Sorry for the delay, our cluster was down most of last week. 

It did not finish. Still getting an error when trying to run overlap.sh. From overlap.\$PBS_ARRAY_INDEX.out :

/Canu/sampledata/ecoli-auto/trimming/1-overlapper/overlap.sh: line 9: =1: command not found
Error: I need PBS_ARRAY_INDEX set, or a job index on the command line.

However, I also noticed that apparently with this PBS when you want to set up job dependencies, the first job should be submitted with the -h, user hold, option. And once all the jobs have been submitted, the first one is released with qrls jobid. If you do not do this, the dependencies can not find the jobs and stay on hold for ever.

**Comment by brianwalenz** [comment] 2016-09-16 21:25
I think the problem is on line 590 in Execution.pm - remove the "\$" before "\$$taskenv=1\n".

Unless you can rerun from scratch, please do not update from git - make this change by hand.  The git repo has a change that I fear will be incompatible with your current assembly.

**Comment by mayelasoto** [comment] 2016-09-22 11:20
Thanks! I went through all the quick start examples and everything went fine :)

**Comment by brianwalenz** [comment] 2016-09-22 11:26
Yay!

**Closed by brianwalenz** 2016-09-22 11:26 UTC

**Comment by megancamilla** [comment] 2017-09-15 04:21
Hi, 
I'm trying to follow this thread to get canu running on our cluster running PBSPro.

It would be really helpful if you could post the successful canu command that worked after all these fixes were put in place.

Currently I've tried:
canu -d WAI1664_canutest -p WAI1664 genomeSize=40000000 stopOnReadQuality=false -nanopore-raw /short/aq97/mcm106/WAI1664_canu1.6/WAI1664_all.fastq minReadLength=2000 \
 useGrid=true gridEngine="pbs" \
 gridOptions="-P aq97 -q express -l walltime=1:00:00 -l ncpus=8 mem=30GB -l jobfs=24GB" \
 gridEngineThreadsOption="-l ncpus=THREADS" \
gridEngineMemoryOption="-l mem=MEMORY"


Getting the error message:
""""
ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   invalid useGrid (1) and gridEngine (pbs); found no execution hosts - is grid available from this host?.
ABORT:
""""

This is from the headnode of my cluster, so it should be able to submit jobs from this host. So I'm not sure where I've gone wrong.

Thanks,

Megan

**Comment by brianwalenz** [comment] 2017-09-15 11:12
Try leaving out the gridEngine="pbs" option, or using gridEngine="pbspro".  PBS and PBSPro are similar, but have (annoying) differences.

**Comment by mayelasoto** [comment] 2017-09-18 15:56
Hi Megan,

I run it as follows:

canu \
 -p Ath_idnum -d Canu/idnum/Ath_idnum \
 genomeSize=135m \
 -pacbio-raw /data/idnum.fastq -useGrid=true -gridEngine="PBSPRO"

Some of the grid options that you are trying to add I have hardcoded in
Grid_PBSTorque.pm

**Comment by megancamilla** [comment] 2017-09-18 23:16
Thanks Brian and Mayelasoto,

I appreciate your help with this. Have it running up to the overlapper step now but not in grid mode. Will try some of these changes and see where I get to. Will post in a new ticket if needed.

Best,
Megan
