### ISSUE TITLE
What counts as AT/GC rich ?

### ISSUE THREAD

**Issue by tseemann** [marbl/canu#90] opened 2016-04-13 01:47 UTC
```
For AT/GC rich genomes, it is beneficial to increase the filtering stringency over the default. 
Specifying corMaxEvidenceErate=0.15 (from the default of 0.2) is generally sufficient.
```

I have some 30% GC bacterial genomes - does that count as AT rich?

**Comment by skoren** [comment] 2016-04-13 12:58
So the genome that motivated this was P. falciparum which is about 80% AT. The problem is it skews our jaccard/identity estimate and so repeat-induced overlaps make it through the filter. I don't think a bacteria would have this problem because they generally have a lot fewer repeats. Bacillus generally works fine without any changes even though it is 35-ish% GC.

**Comment by skoren** [comment] 2016-05-05 23:21
Closing, please reopen if not resolved.

**Closed by skoren** 2016-05-05 23:21 UTC
