### ISSUE TITLE
Excessive Coverage Detected and Bad UID for job execution errors

### ISSUE THREAD

**Issue by jvr0ds** [marbl/canu#2123] opened 2022-05-04 15:58 UTC
I am trying to assemble some giant virus genomes in grid, but when I submit the run, these errors warnings always are generated.
OS is Linux

Command used:
```
!/bin/sh
#Author jvrodrigues934
#PBS -N canu
#PBS -q fila256
#PBS -l select=1:ncpus=64
/programs/canu/build_bin_here/bin/canu -p 2 -d 2_montagem genomeSize=370k -pacbio-hifi /home/jvrodrigues934/in/2_40-NE-4.subreads.fastq.gz
```

1) file called seqStore.err
```
Creating library '2_40-NE-4.subreads' for PacBioHiFi corrected-trimmed reads.

                  reads               bases
Loaded        272987  93.3%   2466605921  99.5%  /home/jvrodrigues934/in/2_40-NE-4.subreads.fastq.gz
Short          19549   6.7%     11929607   0.5%


All reads processed.

               reads               bases
Loaded        272987  93.3%   2466605921  99.5%
Short          19549   6.7%     11929607   0.5%


EXCESSIVE COVERAGE DETECTED.  Sampling reads.

For genome size of       370000 bases,
            retain     74000000 bases (200.00X coverage).

Found       272987 reads with   2466605921 bases (6666.50X coverage).
Dropped     264777 reads with   2392601430 bases (6466.49X coverage).
Retained      8210 reads with     74004491 bases (200.01X coverage).
```

2)error meryl-configure
```
-- Starting command on Tue May  3 18:00:24 2022 with 4434.246 GB free disk space

    cd unitigging/0-mercounts
    ./meryl-configure.sh \
    > ./meryl-configure.err 2>&1

-- Finished on Tue May  3 18:00:25 2022 (one second) with 4434.215 GB free disk space

--  segments   memory batches

--        01  0.21 GB       2

--  For 8210 reads with 74004491 bases, limit to 1 batch.

--  Will count kmers using 01 jobs, each using 2 GB and 4 threads.

-- Finished stage 'merylConfigure', reset canuIteration.

-- Running jobs.  First attempt out of 2.

-- Failed to submit compute jobs.  Delay 10 seconds and try again.

CRASH:
CRASH: canu snapshot v2.3-development +18 changes (r10289 1893349ec9fabbb0a20827a3efd24ac5dbbca23d)
CRASH: Please panic, this is abnormal.
CRASH:
CRASH:   Failed to submit compute jobs.
CRASH:
CRASH: Failed at /programs/canu/build_bin_here/bin/../lib/site_perl/canu/Execution.pm line 1259.
CRASH:  canu::Execution::submitOrRunParallelJob(2, 'meryl', 'unitigging/0-mercounts', 'meryl-count', 1) called at /programs/canu/build_bin_here/bin/../lib/site_perl/canu/Meryl.pm line 847
CRASH:  canu::Meryl::merylCountCheck(2, 'utg') called at /programs/canu/build_bin_here/bin/canu line 1117
CRASH:
CRASH: Last 50 lines of the relevant log file (unitigging/0-mercounts/meryl-count.jobSubmit-01.out):
CRASH:
CRASH: qsub: Bad UID for job execution
```
Since this kind of method is new to my research group, no one knows how to resolve it.

**Comment by skoren** [comment] 2022-05-04 16:40
The high coverage subsampling is OK to ignore, Canu just doesn't the >1000x coverage you have for assembly. The other error is because your grid does not allow hosts to submit jobs, see: https://canu.readthedocs.io/en/latest/faq.html#my-run-stopped-with-the-error-failed-to-submit-batch-jobs. Since your genome is small, just add `useGrid=false` to constrain canu to a single node. Make sure you also add `maxThreads=X maxMemory=Y` to match whatever your PBS request for the canu command is.

**Comment by jvr0ds** [comment] 2022-05-04 17:45
Thank you for the help. Those errors were resolved!! However, no overlaps were created.

-- Starting 'bat' concurrent execution on Wed May  4 14:30:21 2022 with 4269.25 GB free disk space (1 processes; 1 concurrently)

    cd unitigging/4-unitigger
    ./unitigger.sh 1 > ./unitigger.000001.out 2>&1

-- Finished on Wed May  4 14:30:22 2022 (one second) with 4269.247 GB free disk space

----------------------------------------
-- Unitigger finished successfully.

-- Finished stage 'unitigCheck', reset canuIteration.

----------------------------------------
-- Starting command on Wed May  4 14:30:22 2022 with 4269.247 GB free disk space

    cd unitigging
    /programs/canu/build_bin_here/bin/utgcns \
      -S ../teste.seqStore \
      -T  ./teste.ctgStore 1 \
      -partition 0.8 1.5 0.1 \
    > ./teste.ctgStore/partitioning.log 2>&1
sh: line 1: ./teste.ctgStore/partitioning.log: No such file or directory

-- Finished on Wed May  4 14:30:22 2022 (like a bat out of hell) with 4269.247 GB free disk space

----------------------------------------

ERROR:
ERROR:  Failed with exit code 1.  (rc=256)
ERROR:

ABORT:
ABORT: canu snapshot v2.3-development +18 changes (r10289 1893349ec9fabbb0a20827a3efd24ac5dbbca23d)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to partition the reads.

Reading some other issues, I set the configFilter to "2 0 1.0 0.5 0" . 
Something different that happened now is that the output directory is created outside my file directory, where my .sh exec file is. Also, the canu-scripts directory is empty.

**Comment by skoren** [comment] 2022-05-04 17:50
What is the report file in the assembly folder look like? Are you sure these are HiFi reads and not regular CLR reads, the name `*.subreads.fastq` would imply they are not HiFi or perhaps need to be filtered to only include Q20 outputs.

**Comment by jvr0ds** [comment] 2022-05-05 17:28
You were absolutely right!! My source made a mistake when sent me the reads details. I fixed the command to -pacbio.
However, this error now happened. I changed the maxMemory to 1000Gb too.

-- Using slow alignment for consensus (iteration '1').
-- Configured 2 consensus jobs.
-- All 2 consensus jobs finished successfully.
-- Finished stage 'consensusCheck', reset canuIteration.
-- Using slow alignment for consensus (iteration '0').
-- Configured 2 consensus jobs.

----------------------------------------
-- Starting command on Thu May  5 13:56:50 2022 with 3911.254 GB free disk space

    cd unitigging
    /programs/canu/build_bin_here/bin/tgStoreLoad \
      -S ../teste2.seqStore \
      -T  ./teste2.ctgStore 2 \
      -L ./5-consensus/ctgcns.files \
    > ./5-consensus/ctgcns.files.ctgStoreLoad.err 2>&1
sh: line 4: 144606 Aborted                 (core dumped) /programs/canu/build_bin_here/bin/tgStoreLoad -S ../teste2.seqStore -T ./teste2.ctgStore 2 -L ./5-consensus/ctgcns.files > ./5-consensus/ctgcns.files.ctgStoreLoad.err 2>&1

-- Finished on Thu May  5 13:56:51 2022 (one second) with 3911.256 GB free disk space

----------------------------------------

ERROR:
ERROR:  Failed with exit code 134.  (rc=34304)
ERROR:

ABORT:
ABORT: canu snapshot v2.3-development +18 changes (r10289 1893349ec9fabbb0a20827a3efd24ac5dbbca23d)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   failed to load unitig consensus into ctgStore.
ABORT:
ABORT: Disk space available:  3911.256 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/5-consensus/ctgcns.files.ctgStoreLoad.err):
ABORT:
ABORT:   Reading layouts from '5-consensus/ctgcns/0001.cns'.
ABORT:   Reading layouts from '5-consensus/ctgcns/0001.cns' completed.
ABORT:   Reading layouts from '5-consensus/ctgcns/0002.cns'.
ABORT:   tgStoreLoad: utility/src/utility/bits.C:265: void stuffedBits::setPosition(uint64): Assertion `_dataBlk > 0' failed.
ABORT:
ABORT:   Failed with 'Aborted'; backtrace (libbacktrace):
ABORT:   utility/src/utility/system-stackTrace.C::82 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   utility/src/utility/bits.C::265 in _ZN11stuffedBits11setPositionEm()
ABORT:   utility/src/utility/bits.C::232 in _ZN11stuffedBits4loadEP8_IO_FILEP10readBuffer()
ABORT:   stores/tgTig.C::431 in _ZN5tgTig14loadFromStreamEP8_IO_FILE()
ABORT:   stores/tgStoreLoad.C::113 in _Z8loadTigsPKcS0_i11tgStoreTypeRSt6vectorIS0_SaIS0_EE()
ABORT:   stores/tgStoreLoad.C::231 in main()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()

**Comment by skoren** [comment] 2022-05-06 13:43
Given that it failed on a read, I'd guess your hit a disk quota and ran out of space. 

Before trying to get more space though, I wanted to clarify what exactly your sequencing reads are. If your reads are indeed from a HiFi library you should not assemble them as PacBio and instead ask for the proper Q20+ output. HiFi libraries are shorter than normal sequencing and extremely redundant by design so they do not assemble well if you treat them as CLR reads.

**Comment by jvr0ds** [comment] 2022-05-12 17:22
Sorry for the wait.
I talked to the source and confirmed it is CLR reads. Also, I talked to the server administration and space on disk shouldn't be a problem. I removed all files that were at my directory, leaving only the reads and the .sh, but the same error is still happening.

**Comment by skoren** [comment] 2022-05-12 20:43
I didn't notice you're using a newer commit than the release, I wonder if you're hitting the bug fixed by: https://github.com/marbl/canu/commit/8e10cfcb0ffcf4a87f29913e83b2be247754eedd. Could you try running either the 2.2 release version or updating your version to the latest tip and see if it still crashes? Both should be compatible with your existing assembly so you could resume it from where it stopped.

**Comment by jvr0ds** [comment] 2022-05-18 20:32
We updated our version and finnaly we got the assembly. Thank you very much!!

**Closed** 2022-05-18 21:24 UTC
