### ISSUE TITLE
read correction jobs failed

### ISSUE THREAD

**Issue by haghshenas** [marbl/canu#78] opened 2016-03-25 04:46 UTC
Hi there,

I cloned the latest code of canu and built it on a machine with 8 cores and 32 GB of RAM.
It worked successfully on some datasets but fails on some others.

Here is the partial output I got from canu:

    ----------------------------------------
    -- Using overlaps no worse than 0.30 fraction error for correcting reads (from corErrorRate parameter).
    -- generate corrected reads attempt 0 begins with 0 finished, and 6 to compute.
    
    ----------------------------------------
    -- Starting concurrent execution on Thu Mar 24 17:26:58 2016 with 90.1 GB free disk space (6 processes; 2 concurrently)
    
        /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.sh 1 > /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.000001.out 2>&1
        /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.sh 2 > /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.000002.out 2>&1
        /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.sh 3 > /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.000003.out 2>&1
        /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.sh 4 > /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.000004.out 2>&1
        /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.sh 5 > /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.000005.out 2>&1
        /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.sh 6 > /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.000006.out 2>&1
    
    -- Finished on Thu Mar 24 17:43:49 2016 (1011 seconds) with 90.1 GB free disk space
    ----------------------------------------
    -- generate corrected reads attempt 1 begins with 5 finished, and 1 to compute.
    ----------------------------------------
    -- Starting concurrent execution on Thu Mar 24 17:43:49 2016 with 90.1 GB free disk space (1 processes; 2 concurrently)
    
        /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.sh 3 > /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.000003.out 2>&1
    
    -- Finished on Thu Mar 24 17:47:18 2016 (209 seconds) with 90.1 GB free disk space
    ----------------------------------------
    --
    -- 1 read correction jobs failed:
    --   job /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correction_outputs/0003.fasta FAILED.
    -- generate corrected reads attempt 2 begins with 5 finished, and 1 to compute.
    ----------------------------------------
    -- Starting concurrent execution on Thu Mar 24 17:47:19 2016 with 90.1 GB free disk space (1 processes; 2 concurrently)
    
        /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.sh 3 > /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.000003.out 2>&1
    
    -- Finished on Thu Mar 24 17:50:48 2016 (209 seconds) with 90.1 GB free disk space
    ----------------------------------------
    -- Concatenating correctReads output.
    ================================================================================
    Don't panic, but a mostly harmless error occurred and canu failed.
    
    canu failed with 'can't open '/home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/corjob.files' for reading: No such file or directory'.

The file correction/2-correction/correctReads.000003.out contains:

    /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correctReads.sh: line 99: 24614 Done(141)               ( $bin/generateCorrectionLayouts -b $bgn -e $end -rl /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/ecoli.readsToCorrect -G /home/ehaghshe/canuRuns/asm_ecoli/correction/ecoli.gkpStore -O /home/ehaghshe/canuRuns/asm_ecoli/correction/ecoli.ovlStore -S /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/ecoli.globalScores -C 80 -legacy -F && touch /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correction_outputs/$jobid.dump.success )
         24615 Segmentation fault      | $bin/falcon_sense --min_idt 0.7 --min_len 1000 --min_ovl_len 500 --min_cov 4 --n_core 4 > /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correction_outputs/$jobid.fasta.WORKING 2> /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correction_outputs/$jobid.err
    Read layout generation failed.
    mv: cannot stat ‘/home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/correction_outputs/0003.fasta’: No such file or directory

and the file correction/2-correction/correction_outputs/0003.err

    
    Failed with 'Segmentation fault'
    
    Backtrace (mangled):
    
    /home/ehaghshe/soft/canu/Linux-amd64/bin/falcon_sense[0x40716d]
    /lib64/libpthread.so.0(+0xf100)[0x7f85b933c100]
    /home/ehaghshe/soft/canu/Linux-amd64/bin/falcon_sense[0x408cef]
    /home/ehaghshe/soft/canu/Linux-amd64/bin/falcon_sense[0x40958c]
    /home/ehaghshe/soft/canu/Linux-amd64/bin/falcon_sense[0x402735]
    /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f85b8f8db15]
    /home/ehaghshe/soft/canu/Linux-amd64/bin/falcon_sense[0x403239]
    
    Backtrace (demangled):
    
    [0] /home/ehaghshe/soft/canu/Linux-amd64/bin/falcon_sense() [0x40716d]
    [1] /lib64/libpthread.so.0::(null) + 0xf100  [0x7f85b933c100]
    [2] /home/ehaghshe/soft/canu/Linux-amd64/bin/falcon_sense() [0x408cef]
    [3] /home/ehaghshe/soft/canu/Linux-amd64/bin/falcon_sense() [0x40958c]
    [4] /home/ehaghshe/soft/canu/Linux-amd64/bin/falcon_sense() [0x402735]
    [5] /lib64/libc.so.6::(null) + 0xf5  [0x7f85b8f8db15]
    [6] /home/ehaghshe/soft/canu/Linux-amd64/bin/falcon_sense() [0x403239]
    
    GDB:
    
    
Any idea what the problem can be?

**Comment by skoren** [comment] 2016-03-25 12:24
This looks like a bug in falcon_sense or generateCorrectionLayouts, which dataset are you using? If you are able to edit correctReads.sh script to remove the call to falcon_sense and instead of the pipe redirect the generateReadCorrectionLayouts output to a file, something like:

```
$bin/generateCorrectionLayouts -b $bgn -e $end -rl /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/ecoli.readsToCorrect -G /home/ehaghshe/canuRuns/asm_ecoli/correction/ecoli.gkpStore -O /home/ehaghshe/canuRuns/asm_ecoli/correction/ecoli.ovlStore -S /home/ehaghshe/canuRuns/asm_ecoli/correction/2-correction/ecoli.globalScores -C 80 -legacy -F > $jobid.falcon_lay
```

If that runs, the bug is in falcon_sense and if you share the generated falcon_lay file I should be able to test the error locally.

**Comment by haghshenas** [comment] 2016-03-25 17:59
I am using [E.coli dataset](https://github.com/PacificBiosciences/DevNet/wiki/E%20coli%20K12%20MG1655%20Hybrid%20Assembly) which is partially corrected using short reads.

I made the changes in correctReads.sh script. It runs and as you said the bug should be in falcon_sense. You can access file 0003.falcon_lay file [here](https://drive.google.com/folderview?id=0B3R-_ssnhJvzRC1KNHh4WW5WVU0&usp=sharing).

**Comment by skoren** [comment] 2016-03-25 18:38
Partially corrected? If your reads are corrected by Illumina data (e.g. over about 97.5% identity), you should be able to use -pacbio-corrected as the option rather than -pacbio-raw. The reads will still be trimmed based on overlaps but it will skip the correction step. Based on a quick look at your data, the identity seems high but a large number of reads have multi-piece mappings or bad end trim points (40%) so I think -pacbio-corrected would work. It is possible that -pacbio-raw will recover some poorly corrected regions and make the full read higher-identity rather than splitting it and I saw this was the case for several reads in your posted file.

I was able to reproduced your crash. This is fixed in a commit on our development branch but isn't yet in master. If you update src/falcon_sense/libfalcon/falcon.C:
```
                             score =  (double) aln_col->link_count[ck] - (double) coverage[i] * 0.5;
 +                        } else if (pj > msa_array[pi]->max_delta) {
 +                            score =  (double) aln_col->link_count[ck] - (double) coverage[i] * 0.5;
                          } else {		                          } else {
```
and compile, it should fix the error.

**Comment by haghshenas** [comment] 2016-03-29 02:52
We know that some regions on our long reads have remained uncorrected. So as you said we wanted to take advantage of recovering these regions by -pacbio-raw.

The suggested change fixed the error.
Thanks a lot

**Comment by skoren** [comment] 2016-03-30 15:16
Willl be fixed in an upcoming release

**Closed by skoren** 2016-03-30 15:16 UTC
