### ISSUE TITLE
Mhap overlap jobs failed

### ISSUE THREAD

**Issue by dopameinfy** [marbl/canu#1499] opened 2019-10-02 00:31 UTC
Hi,

I have rerun Canu for several times but it always gave me this error message:

```
-- BEGIN CORRECTION
--
--
-- Mhap overlap jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/results/000118.ovb FAILED.
--   job correction/1-overlapper/results/000121.ovb FAILED.
--   job correction/1-overlapper/results/000124.ovb FAILED.
--   job correction/1-overlapper/results/000127.ovb FAILED.
--   job correction/1-overlapper/results/000130.ovb FAILED.
--   job correction/1-overlapper/results/000133.ovb FAILED.
--   job correction/1-overlapper/results/000136.ovb FAILED.
--   job correction/1-overlapper/results/000139.ovb FAILED.
--   job correction/1-overlapper/results/000142.ovb FAILED.
--   job correction/1-overlapper/results/000150.ovb FAILED.
--   job correction/1-overlapper/results/000170.ovb FAILED.
--   job correction/1-overlapper/results/000172.ovb FAILED.
--   job correction/1-overlapper/results/000174.ovb FAILED.
--   job correction/1-overlapper/results/000176.ovb FAILED.
--   job correction/1-overlapper/results/000178.ovb FAILED.
--   job correction/1-overlapper/results/000182.ovb FAILED.
--   job correction/1-overlapper/results/000184.ovb FAILED.
--   job correction/1-overlapper/results/000186.ovb FAILED.
--   job correction/1-overlapper/results/000188.ovb FAILED.
--

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

**Comment by skoren** [comment] 2019-10-02 13:41
This is usually an issue with the JVM/memory/disk corruption? 

Is it possible you're running out of disk space? How much free space does canu report you have and do you have any quotas?

Post the canu preamble (where it reports resources it plans to use) and the output of one of the failing jobs (```correction/1-overlapper/mhap.*118.out``` or similar) (see #1444 for similar error/suggestions).

**Comment by skoren** [comment] 2019-10-09 13:51
Any update on this?

**Comment by skoren** [comment] 2019-10-14 18:14
Idle, no response.

**Comment by dopameinfy** [comment] 2019-10-15 18:27
Hi skoren,
sorry for the late response - I was away for last week. I've double checked my disk space and tried to rerun canu again, but still failed. 
My canu script:
`#!/bin/bash
#PBS -l vmem=16G
#PBS -l walltime=1:0:0
#PBS -m e
#PBS -V
module load canu
canu -p X_201909 -d ./X_201909_canu genomeSize=1g -pacbio-raw pacbio.fasta -nanopore-raw nanopore.fasta  -useGrid=true -gridOptions="-l vmem=128G,nodes=1:ppn=8,walltime=4:0:0:0"`

preamble
```

--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     64 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       16 GB   24 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   32 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    16 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl    16 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       12 GB    8 CPUs  (read error detection)
-- Grid:  oea        4 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      256 GB   16 CPUs  (contig construction with bogart)
-- Grid:  gfa       16 GB   16 CPUs  (GFA alignment and processing)
```
The output on one of the failed job:

```
Found perl:
   /N/soft/rhel7/perl/gnu/5.24.1/bin/perl
   This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-thread-multi

Found java:
   /bin/java
   openjdk version "1.8.0_212"

Found canu:
   /gpfs/hps/soft/rhel7/canu/1.8/bin/canu
   Canu 1.8

Running job 1 based on PBS_ARRAYID=1 and offset=0.
Job previously completed successfully.
```

Thanks for your help!!

**Comment by skoren** [comment] 2019-10-15 18:40
That doesn't look like one of the failing jobs, it reports it already successfully completed. There should be ones ending with an error message instead. check tail of all the output files to see which ones have it.

**Comment by dopameinfy** [comment] 2019-10-15 20:53
The above is actually in the failing jobs.
When I rerun canu, it says 
```
BEGIN CORRECTION
--
--
-- Running jobs.  First attempt out of 2.
--
-- 'mhap.jobSubmit-01.sh' -> job 1406244.s1 task 118.
-- 'mhap.jobSubmit-02.sh' -> job 1406245.s1 task 121.
-- 'mhap.jobSubmit-03.sh' -> job 1406246.s1 task 124.
-- 'mhap.jobSubmit-04.sh' -> job 1406247.s1 task 127.
-- 'mhap.jobSubmit-05.sh' -> job 1406248.s1 task 130.
-- 'mhap.jobSubmit-06.sh' -> job 1406249.s1 task 133.
-- 'mhap.jobSubmit-07.sh' -> job 1406250.s1 task 136.
-- 'mhap.jobSubmit-08.sh' -> job 1406251.s1 task 139.
-- 'mhap.jobSubmit-09.sh' -> job 1406252.s1 task 142.
-- 'mhap.jobSubmit-10.sh' -> job 1406253.s1 task 150.
-- 'mhap.jobSubmit-11.sh' -> job 1406254.s1 task 170.
-- 'mhap.jobSubmit-12.sh' -> job 1406255.s1 task 172.
-- 'mhap.jobSubmit-13.sh' -> job 1406256.s1 task 174.
-- 'mhap.jobSubmit-14.sh' -> job 1406257.s1 task 176.
-- 'mhap.jobSubmit-15.sh' -> job 1406258.s1 task 178.
-- 'mhap.jobSubmit-16.sh' -> job 1406259.s1 task 182.
-- 'mhap.jobSubmit-17.sh' -> job 1406260.s1 task 184.
-- 'mhap.jobSubmit-18.sh' -> job 1406261.s1 task 186.
-- 'mhap.jobSubmit-19.sh' -> job 1406262.s1 task 188.
--
----------------------------------------
-- Starting command on Tue Oct 15 14:56:21 2019 with 236148.829 GB free disk space

    cd /N/dc2/scratch/yif/X
    qsub \
      -j oe \
      -d `pwd` \
      -W depend=afterany:1406244.s1:1406245.s1:1406246.s1:1406247.s1:1406248.s1:1406249.s1:1406250.s1:1406251.s1:1406252.s1:1406253.s1:1406254.s1:1406255.s1:1406256.s1:1406257.s1:1406258.s1:1406259.s1:1406260.s1:1406261.s1:1406262.s1 \
      -l mem=4g \
      -l nodes=1:ppn=1 \
      -l vmem=128G,nodes=1:ppn=8,walltime=4:0:0:0  \
      -N 'canu_X_201909' \
      -o canu-scripts/canu.15.out  canu-scripts/canu.15.sh

-- Finished on Tue Oct 15 14:56:21 2019 (in the blink of an eye) with 236148.829 GB free disk space
----------------------------------------
```
The tail of canu.out is
```

-- BEGIN CORRECTION
--
--
-- Mhap overlap jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/results/000118.ovb FAILED.
--   job correction/1-overlapper/results/000121.ovb FAILED.
--   job correction/1-overlapper/results/000124.ovb FAILED.
--   job correction/1-overlapper/results/000127.ovb FAILED.
--   job correction/1-overlapper/results/000130.ovb FAILED.
--   job correction/1-overlapper/results/000133.ovb FAILED.
--   job correction/1-overlapper/results/000136.ovb FAILED.
--   job correction/1-overlapper/results/000139.ovb FAILED.
--   job correction/1-overlapper/results/000142.ovb FAILED.
--   job correction/1-overlapper/results/000150.ovb FAILED.
--   job correction/1-overlapper/results/000170.ovb FAILED.
--   job correction/1-overlapper/results/000172.ovb FAILED.
--   job correction/1-overlapper/results/000174.ovb FAILED.
--   job correction/1-overlapper/results/000176.ovb FAILED.
--   job correction/1-overlapper/results/000178.ovb FAILED.
--   job correction/1-overlapper/results/000182.ovb FAILED.
--   job correction/1-overlapper/results/000184.ovb FAILED.
--   job correction/1-overlapper/results/000186.ovb FAILED.
--   job correction/1-overlapper/results/000188.ovb FAILED.
--

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```
All of the 19 files has an output claiming "job previously complete successfully", but canu was actually interrupted because the 19 jobs failed. 
Also I tried to delete the *.ovb.WORKING files but nothing changed. 

Thanks for your help!!

**Comment by dopameinfy** [comment] 2019-10-15 21:02
Actually something similar happened to me before like in "overlap jobs failed #1339" but at a later step. Is it something caused by PBS?

**Comment by skoren** [comment] 2019-10-15 21:23
Ah yes PBS did have issues with re-starting failed jobs in 1.8 which has subsequently been fixed. The failed job is reporting it's trying to run job 1 which fails, I think this was fixed by commit ad083d3e21b446c041d6ebf1c3aab728ca7fea2e. 

You could try updating to the 1.9 branch which you have to check out/build yourself and you'd have to restart from scratch to see if the issue is resolved. It would be good to know if this is really fixed and we don't have access to PBS. Alternatively, you'd have to re-run the failed jobs yourself by hand as you did for the previous issue. Remove any ```*WORKING*``` and ```*mhap*``` files in results first.

**Comment by dopameinfy** [comment] 2019-10-15 21:29
I'll try to rerun by hand! Could you please give me an example of the command line I could run?

**Comment by skoren** [comment] 2019-10-15 21:30
As in your previous issue, in an interactive session run ```sh mhap.sh <jobid -1>``` so for 118 run ```sh mhap.sh 117``` (I recall this is needed because you always have an offset of 1 in an interactive session too).

**Comment by skoren** [comment] 2019-10-16 19:15
I would be curious if editing your submit script (for at least one failed job) as in my suggestion 3 works as that's the fix for the next release and I want to confirm it works.

**Comment by dopameinfy** [comment] 2019-10-17 16:23
The job is now running and the standard output file looks fine.

I run job 184 by submitting the script:
```
#!/bin/sh

qsub -j oe -d `pwd` \
  -l mem=32g -l nodes=1:ppn=8 -l vmem=128G,nodes=1:ppn=8,walltime=4:0:0:0 \
  -N "cormhap_X" \
   \
  ./mhap.sh -F "183" \
> ./mhap.jobSubmit-17.out 2>&1

```
If I ran mhap.sh -F "184" 

Then the program actually runs for job 185:

```
Found perl:
   /N/soft/rhel7/perl/gnu/5.24.1/bin/perl
   This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-thread-multi

Found java:
   /bin/java
   openjdk version "1.8.0_212"

Found canu:
   /gpfs/hps/soft/rhel7/canu/1.8/bin/canu
   Canu 1.8

Running job 185 based on PBS_ARRAYID=1 and offset=184.
Job previously completed successfully.
```

**Comment by skoren** [comment] 2019-10-17 17:14
There should be no PBS_ARRAYID defined in the environment for a non-array job and I don't see a -t option in the command. I've tested this on other PBS systems without issue. This seems like a bug/issue on your specific PBS installation.

What version of PBS do you have (qsub -v)? Did you define PBS_ARRAYID yourself before running canu in the environment? What if you run unset PBS_ARRAYID then submit job 184 as you did before does it run the correct one?

**Comment by skoren** [comment] 2019-10-27 20:55
Idle, original error was due to a bug in 1.8, fixed in 1.9 release. Not sure why PBS_ARRAYID is always defined as 1,  this is not the case on other PBS systems.

**Closed by skoren** 2019-10-27 20:55 UTC

**Comment by sadikmu** [comment] 2020-04-06 17:03
Hi @skoren 

Can I pease request your help?

I have got a similar error problem for Canu-2.0 on correction stage running it on SLURM. 

script 

`path-to-/canu-2.0/Linux-amd64/bin/canu -correct -p cor -d cor_out -genomeSize=475m 
-pacbio-raw xxx.fastq.gz`





message on canu-scripts/canu.07.out 

-- BEGIN CORRECTION
-- No change in report.

-- OVERLAPPER (mhap) (correction) complete, not rewriting scripts.


-- Mhap overlap jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/results/000001.ovb FAILED.
--   job correction/1-overlapper/results/000003.ovb FAILED.
--   job correction/1-overlapper/results/000006.ovb FAILED.
--   job correction/1-overlapper/results/000008.ovb FAILED.
--   job correction/1-overlapper/results/000009.ovb FAILED.
--   job correction/1-overlapper/results/000010.ovb FAILED.
--   job correction/1-overlapper/results/000012.ovb FAILED.
--   job correction/1-overlapper/results/000013.ovb FAILED.
--   job correction/1-overlapper/results/000016.ovb FAILED.
--   job correction/1-overlapper/results/000018.ovb FAILED.
--   job correction/1-overlapper/results/000020.ovb FAILED.
--   job correction/1-overlapper/results/000022.ovb FAILED.
--   job correction/1-overlapper/results/000024.ovb FAILED.
--   job correction/1-overlapper/results/000028.ovb FAILED.
--   job correction/1-overlapper/results/000032.ovb FAILED.
--   job correction/1-overlapper/results/000034.ovb FAILED.
--   job correction/1-overlapper/results/000036.ovb FAILED.
--   job correction/1-overlapper/results/000038.ovb FAILED.
--   job correction/1-overlapper/results/000040.ovb FAILED.
--   job correction/1-overlapper/results/000042.ovb FAILED.
--   job correction/1-overlapper/results/000044.ovb FAILED.
--   job correction/1-overlapper/results/000046.ovb FAILED.
--   job correction/1-overlapper/results/000048.ovb FAILED.
--   job correction/1-overlapper/results/000054.ovb FAILED.
--   job correction/1-overlapper/results/000056.ovb FAILED.
--   job correction/1-overlapper/results/000060.ovb FAILED.
--   job correction/1-overlapper/results/000064.ovb FAILED.
--   job correction/1-overlapper/results/000068.ovb FAILED.
--   job correction/1-overlapper/results/000072.ovb FAILED.
--   job correction/1-overlapper/results/000076.ovb FAILED.
--   job correction/1-overlapper/results/000078.ovb FAILED.
--   job correction/1-overlapper/results/000080.ovb FAILED.
--   job correction/1-overlapper/results/000088.ovb FAILED.
--   job correction/1-overlapper/results/000092.ovb FAILED.
--   job correction/1-overlapper/results/000094.ovb FAILED.
--   job correction/1-overlapper/results/000095.ovb FAILED.
--   job correction/1-overlapper/results/000096.ovb FAILED.
--   job correction/1-overlapper/results/000100.ovb FAILED.
--   job correction/1-overlapper/results/000104.ovb FAILED.
--   job correction/1-overlapper/results/000108.ovb FAILED.
--   job correction/1-overlapper/results/000112.ovb FAILED.
--   job correction/1-overlapper/results/000116.ovb FAILED.
--   job correction/1-overlapper/results/000124.ovb FAILED.
--   job correction/1-overlapper/results/000126.ovb FAILED.
--   job correction/1-overlapper/results/000128.ovb FAILED.
--   job correction/1-overlapper/results/000130.ovb FAILED.
--   job correction/1-overlapper/results/000131.ovb FAILED.
--   job correction/1-overlapper/results/000132.ovb FAILED.
--   job correction/1-overlapper/results/000136.ovb FAILED.
--   job correction/1-overlapper/results/000140.ovb FAILED.
--   job correction/1-overlapper/results/000142.ovb FAILED.
--   job correction/1-overlapper/results/000143.ovb FAILED.
--   job correction/1-overlapper/results/000144.ovb FAILED.
--   job correction/1-overlapper/results/000148.ovb FAILED.
--   job correction/1-overlapper/results/000156.ovb FAILED.
--   job correction/1-overlapper/results/000158.ovb FAILED.
--   job correction/1-overlapper/results/000159.ovb FAILED.
--   job correction/1-overlapper/results/000160.ovb FAILED.
--   job correction/1-overlapper/results/000168.ovb FAILED.
--   job correction/1-overlapper/results/000172.ovb FAILED.
--   job correction/1-overlapper/results/000176.ovb FAILED.
--   job correction/1-overlapper/results/000180.ovb FAILED.
--   job correction/1-overlapper/results/000182.ovb FAILED.
--   job correction/1-overlapper/results/000183.ovb FAILED.
--   job correction/1-overlapper/results/000184.ovb FAILED.
--   job correction/1-overlapper/results/000207.ovb FAILED.
--   job correction/1-overlapper/results/000208.ovb FAILED.
--   job correction/1-overlapper/results/000223.ovb FAILED.
--   job correction/1-overlapper/results/000263.ovb FAILED.
--   job correction/1-overlapper/results/000275.ovb FAILED.
--   job correction/1-overlapper/results/000276.ovb FAILED.
--   job correction/1-overlapper/results/000295.ovb FAILED.
--   job correction/1-overlapper/results/000299.ovb FAILED.
--   job correction/1-overlapper/results/000300.ovb FAILED.
--   job correction/1-overlapper/results/000320.ovb FAILED.
--   job correction/1-overlapper/results/000329.ovb FAILED.
--   job correction/1-overlapper/results/000365.ovb FAILED.
--   job correction/1-overlapper/results/000425.ovb FAILED.
--   job correction/1-overlapper/results/000502.ovb FAILED.
--   job correction/1-overlapper/results/000514.ovb FAILED.
--   job correction/1-overlapper/results/000517.ovb FAILED.
--   job correction/1-overlapper/results/000519.ovb FAILED.
--   job correction/1-overlapper/results/000521.ovb FAILED.
--   job correction/1-overlapper/results/000525.ovb FAILED.
--   job correction/1-overlapper/results/000527.ovb FAILED.
--   job correction/1-overlapper/results/000529.ovb FAILED.
--   job correction/1-overlapper/results/000531.ovb FAILED.
--   job correction/1-overlapper/results/000533.ovb FAILED.
--   job correction/1-overlapper/results/000535.ovb FAILED.
--   job correction/1-overlapper/results/000537.ovb FAILED.
--   job correction/1-overlapper/results/000539.ovb FAILED.
--   job correction/1-overlapper/results/000541.ovb FAILED.
--   job correction/1-overlapper/results/000543.ovb FAILED.
--   job correction/1-overlapper/results/000545.ovb FAILED.
--   job correction/1-overlapper/results/000547.ovb FAILED.
--   job correction/1-overlapper/results/000549.ovb FAILED.
--   job correction/1-overlapper/results/000551.ovb FAILED.
--   job correction/1-overlapper/results/000553.ovb FAILED.
--   job correction/1-overlapper/results/000555.ovb FAILED.
--   job correction/1-overlapper/results/000557.ovb FAILED.
--   job correction/1-overlapper/results/000559.ovb FAILED.
--   job correction/1-overlapper/results/000561.ovb FAILED.
--   job correction/1-overlapper/results/000563.ovb FAILED.
--   job correction/1-overlapper/results/000567.ovb FAILED.
--   job correction/1-overlapper/results/000569.ovb FAILED.
--   job correction/1-overlapper/results/000571.ovb FAILED.
--   job correction/1-overlapper/results/000573.ovb FAILED.
--   job correction/1-overlapper/results/000575.ovb FAILED.
--   job correction/1-overlapper/results/000577.ovb FAILED.
--   job correction/1-overlapper/results/000579.ovb FAILED.
--   job correction/1-overlapper/results/000581.ovb FAILED.
--   job correction/1-overlapper/results/000583.ovb FAILED.
--   job correction/1-overlapper/results/000585.ovb FAILED.
--   job correction/1-overlapper/results/000587.ovb FAILED.
--   job correction/1-overlapper/results/000589.ovb FAILED.
--   job correction/1-overlapper/results/000591.ovb FAILED.
--   job correction/1-overlapper/results/000593.ovb FAILED.
--   job correction/1-overlapper/results/000595.ovb FAILED.
--   job correction/1-overlapper/results/000597.ovb FAILED.
--   job correction/1-overlapper/results/000601.ovb FAILED.
--   job correction/1-overlapper/results/000603.ovb FAILED.
--   job correction/1-overlapper/results/000605.ovb FAILED.
--   job correction/1-overlapper/results/000607.ovb FAILED.
--   job correction/1-overlapper/results/000609.ovb FAILED.
--   job correction/1-overlapper/results/000611.ovb FAILED.
--   job correction/1-overlapper/results/000613.ovb FAILED.
--   job correction/1-overlapper/results/000615.ovb FAILED.
--   job correction/1-overlapper/results/000617.ovb FAILED.
--   job correction/1-overlapper/results/000619.ovb FAILED.
--   job correction/1-overlapper/results/000625.ovb FAILED.
--   job correction/1-overlapper/results/000627.ovb FAILED.
--   job correction/1-overlapper/results/000629.ovb FAILED.
--   job correction/1-overlapper/results/000631.ovb FAILED.
--   job correction/1-overlapper/results/000633.ovb FAILED.
--   job correction/1-overlapper/results/000635.ovb FAILED.
--   job correction/1-overlapper/results/000637.ovb FAILED.
--   job correction/1-overlapper/results/000641.ovb FAILED.
--   job correction/1-overlapper/results/000649.ovb FAILED.
--   job correction/1-overlapper/results/000653.ovb FAILED.
--   job correction/1-overlapper/results/000657.ovb FAILED.
--   job correction/1-overlapper/results/000661.ovb FAILED.
--   job correction/1-overlapper/results/000664.ovb FAILED.
ABORT:
ABORT: canu snapshot v2.0-development +440 changes (r9933 2a460375aa0a6a967ce05037fcd0f0dea20c9253)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
`
The options mentioned in #1339  #1087 , #1074 , #1043 do no seem to work for me. 

manually running sh mhap.sh 223 failed jobs output the following and the outputs are the same for other jobs except change in the names of **Fetch blocks/000???.dat** files

**$ sh mhap.sh 223:** 

`Found perl:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
   This is perl 5, version 30, subversion 1 (v5.30.1) built for x86_64-linux-thread-multi

Found java:
  
   openjdk version "1.8.0_152-release"

Found canu:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_GB.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
   canu snapshot v2.0-development +440 changes (r9933 2a460375aa0a6a967ce05037fcd0f0dea20c9253)

Running job 223 based on command line options.
Fetch blocks/000130.dat
Fetch blocks/000131.dat
Fetch blocks/000132.dat
Fetch blocks/000133.dat
Fetch blocks/000134.dat
Fetch blocks/000135.dat
Fetch blocks/000136.dat
Fetch blocks/000137.dat
Fetch blocks/000138.dat
Fetch blocks/000139.dat
Fetch blocks/000140.dat
Fetch blocks/000141.dat
Fetch blocks/000142.dat
Fetch blocks/000143.dat
Fetch blocks/000144.dat
Fetch blocks/000145.dat
Fetch blocks/000146.dat
Fetch blocks/000147.dat
Fetch blocks/000148.dat
Fetch blocks/000149.dat
Fetch blocks/000150.dat
Fetch blocks/000151.dat
Fetch blocks/000152.dat
Fetch blocks/000153.dat
Fetch blocks/000154.dat
Fetch blocks/000155.dat
Fetch blocks/000156.dat
Fetch blocks/000157.dat
Fetch blocks/000158.dat
Fetch blocks/000159.dat
Fetch blocks/000160.dat
Fetch blocks/000161.dat
Fetch blocks/000162.dat
Fetch blocks/000163.dat
Fetch blocks/000164.dat
Fetch blocks/000165.dat
Fetch blocks/000166.dat
Fetch blocks/000167.dat
Fetch blocks/000168.dat
Fetch blocks/000169.dat
Fetch blocks/000170.dat
Fetch blocks/000171.dat
Fetch blocks/000172.dat
Fetch blocks/000173.dat
Fetch blocks/000174.dat
Fetch blocks/000175.dat
Fetch blocks/000176.dat
Fetch blocks/000177.dat
Fetch blocks/000178.dat
Fetch blocks/000179.dat
Fetch blocks/000180.dat
Fetch blocks/000181.dat
Fetch blocks/000182.dat
Fetch blocks/000183.dat
Fetch blocks/000184.dat
Fetch blocks/000185.dat
Fetch blocks/000186.dat
Fetch blocks/000187.dat
Fetch blocks/000188.dat
Fetch blocks/000189.dat
Fetch blocks/000190.dat
Fetch blocks/000191.dat
Fetch blocks/000192.dat
Fetch blocks/000193.dat
Fetch blocks/000194.dat
Fetch blocks/000195.dat
Fetch blocks/000196.dat
Fetch blocks/000197.dat
Fetch blocks/000198.dat
Fetch blocks/000199.dat
Fetch blocks/000200.dat
Fetch blocks/000201.dat
Fetch blocks/000202.dat

Running block 000056 in query 000223

sqStore_loadMetadata()-- Using 'raw' 0x01 reads.`

**Comment by skoren** [comment] 2020-04-06 17:10
Not really the same issue since you're not on PBS and on a different version of Canu. 

You are actually not using 2.0 as your version string reports: ```v2.0-development +440 changes (r9933 2a46037)```. That commit is from a couple of days ago. You should first remove the current run completely and use the releases page to download the actual 2.0 release.

Second, there is no error in the job reported by Canu so this isn't likely to be a Canu error but is more likely an issue with slurm scheduling. You should check the history of the jobs Canu submitted to see why they terminated. It may be that the default time allocated is insufficient to complete the run.

**Comment by sadikmu** [comment] 2020-04-06 17:46
Thanks @skoren.

I will use the binary distribution from https://github.com/marbl/canu/releases/tag/v2.0, rerun it and let's you know how it goes. 

Here is a few head lines of the latest mhap out file mhap.235871_661.out in correction/1-overlapper directory if it helps to relate to slurm schedule termination. 

`Running job 661 based on SLURM_ARRAY_TASK_ID=661 and offset=0.
Fetch blocks/000221.dat
Fetch blocks/000222.dat
Fetch blocks/000223.dat

Running block 000220 in query 000661

Running with these settings:
--filter-threshold = 1.0E-7
--help = false
--max-shift = 0.2
--min-olap-length = 500
--min-store-length = 0
--no-rc = false
--no-self = false
--no-tf = false
--num-hashes = 256
--num-min-matches = 3
--num-threads = 14
--ordered-kmer-size = 14
--ordered-sketch-size = 1000
--repeat-idf-scale = 10.0
--repeat-weight = 0.9
--settings = 0
--store-full-id = true
--supress-noise = 0
--threshold = 0.8
--version = false
-f = 
-h = false
-k = 16
-p = 
-q = queries/000661
-s = ./blocks/000220.dat

Processing files for storage in reverse index...
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences stored: 5000...
Current # sequences stored: 10000...
Current # sequences stored: 15000...
Current # sequences stored: 20000...
Current # sequences stored: 25000...
Current # sequences stored: 30000...
Current # sequences stored: 35000...
Current # sequences stored: 40000...
Stored 43200 sequences in the index.
Processed 43200 unique sequences (fwd and rev)`

tail -n 10 mhap.235871_661.out

`Opened fasta file path-to-/correction/1-overlapper/blocks/000286.dat.

Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...

Processed 21600 to sequences.
Time (s) to score, hash to-file, and output: 8.24273938
Opened fasta file path-to-/correction/1-overlapper/blocks/000287.dat.

Current # sequences loaded and processed from file: 5000...
slurmstepd: error: *** JOB 235871 ON cnode47 CANCELLED AT 2020-04-06T04:41:49 DUE TO TIME LIMIT ***` 
 
I also wondering if there are ways to fit canu's assembly stages (rough estimate depending of genome size and complexity) with job scheduler time limit on slurm?

**Comment by skoren** [comment] 2020-04-07 22:16
Ok, so the issue is the default time limit is too short. 

There isn't a quick way to convert genome size to time since that will depend on your available compute, the genome repetitiveness, and sequencing technology/depth. I'd start with something like 24 or 48 hrs and if you still see some jobs failing due to time limits, you can re-run Canu with a new time limit. It will not re-run any jobs that did complete and will submit remaining jobs with the new time limit.
