### ISSUE TITLE
overlap.sh running for 22 hours. Long reads, very small genome.

### ISSUE THREAD

**Issue by miles-gene** [marbl/canu#414] opened 2017-03-21 00:40 UTC
Hello
I'm using the latest release installed two days ago. I'm trying to assemble a BAC so max genome size would be 350kb but I do have limited resources (4Gb RAM and 2/4 cores of an i5). Read correction ran fine in 2 hours and generated long reads. I would guess the median corrected read length is 85kb. The problem is trimming is taking forever. Overlap.sh has been running for 22 hours. I can't find any errors in the logs that have been generated so far, but I did notice that frequentMers.fasta is tiny at 28 bytes and contains a single sequence. I'm considering stopping and trying obtOverlapper=mhap. Any advice would be great.
Thanks for reading

**Comment by miles-gene** [comment] 2017-03-21 00:48
P.S. I set errorrate=0.025 so obtOvlErrorRate and and obtError rate are 0.075, And the reads are Minion R9.4 1D from the RAD002 chemistry.

**Comment by skoren** [comment] 2017-03-21 13:56
How much coverage do you have of your 350k sequence? If you have a median of 85kb reads you probably don't need more than 10-20 reads to assemble it and my guess is you have lots more which is slowing down the compute. You can also try ```overlapper=mhap utgReAlign=true``` to use the MHAP overlapper for trimming and assembly as well as correction.

**Comment by miles-gene** [comment] 2017-03-21 22:41
Hi
Thanks for the reply. I have 41 x coverage (13.96Mbp) of corrected reads (164 reads) although I don't know the size of the BAC. I opted for 340k as it seemed like a likely upper size limit and I wanted good coverage of the BAC ends. That doesn't seem excessive but I could reduce the genome size and generate less corrected reads.

**Comment by brianwalenz** [comment] 2017-03-29 07:13
Did you ever get an assembly?

The algorithm in question was developed for Sanger-era reads (~650bp at the time) so that it even runs on this stuff is pretty amazing.  We'll eventually end up at the 'realign' solution Sergey mentioned.  It needs more testing and validation though.

**Comment by miles-gene** [comment] 2017-03-29 23:35
Hello
Thankyou for your interest. I am currently running canu with overlapper=mhap on the reads I mentioned, I will let you know how that goes. I have recently tried to assemble a smaller BAC using the same settings. I found that correction and trimming produced 101 reads 35-37Kbp (estimated genomeSize=0.09m), however assembly produced 0 bytes in contigs.fasta. Unitigging.html reports 73 reads unique repeat dove and 28 span repeat so canu (quite correctly) has not extended the contigs as each corrected read is I think, an almost complete 'assembly'. I used graphmap to pileup the 101 corrected reads and was able to generate a 36,806bp consensus that is 92% identical to an 1100bp sequence I know is contained within the BAC and 95% id to the BAC end sequences. 
I have not yet tested if my new more accurate estimate of genome size would enable trimming and assembly to use ovl.  
Thanks

**Comment by skoren** [comment] 2017-04-04 13:06
I'd guess the reason you had no "assembly" is the filter which eliminates contigs which look like collapsed repeat/noise (primary one read with lots of contained sequences). In your case, the genome is spanned by one read. You can try the options on the FAQ:
http://canu.readthedocs.io/en/latest/faq.html#my-asm-contigs-fasta-is-empty-why
and I expect you'll get your full genome in a contig. You can also check the asm.unassembled.fasta for your 36kb sequence without re-running the assembly.

**Comment by miles-gene** [comment] 2017-04-05 00:40
I tried setting contigFilter="2 1000 1.0 1.0 2" and repeated trying to -trim-assemble the 80 ~81Kbp corrected reads using mhap that had stuck in the first place. The result was the same, zero in contigs.fasta and unassembled.fasta contains 80 reads. I can't import a .bam alignment of these reads into Geneious so I haven't been able to get even a crude consensus. Do you think it would it be worth trying falconpipe  as an alternative cns caller?
Thanks

**Comment by skoren** [comment] 2017-04-05 19:38
Are you able to share your data, ideally raw fasta? You can upload them here:
ftp://ftp.cbcb.umd.edu/incoming/sergek

**Comment by miles-gene** [comment] 2017-04-06 14:41
Hi
I may have uploaded the raw .fasta data that canu generated the 80 corrected reads from to your ftp site although it's not obvious if I have been successful. I'd appreciate it if you kept the data confidential.
Thanks

**Comment by skoren** [comment] 2017-04-06 15:57
I didn't see any new files on the ftp link so I don't think the upload worked. Could you try it again, any ftp client should work but you won't be able to see the file once it is uploaded (only I can see the folder contents).

**Comment by miles-gene** [comment] 2017-04-06 22:54
ok, the reads should be there. 
Thanks

**Comment by skoren** [comment] 2017-04-10 18:40
So my first run worked and produced a single 90kb contig. The parameters are used are:
```canu -p asm -d test corMinCoverage=0 corMhapSensitivity=high corOutCoverage=1000 overlapper=mhap utgReAlign=true -nanopore-raw *.fasta useGrid=0 genomeSize=100k corPartitions=100 corPartitionMin=100 contigFilter="2 1000 1.0 1.0 2"```

These are essentially low-coverage/sensitive parameters (```corMhapSensitivity=high corMinCoverage=0```) correcting all your data ```corOutCoverage=1000```. This is probably overkill. I'll let you know if there are other parameters that also work but this at least gives you an option to use for other similar datasets.

**Comment by skoren** [comment] 2017-04-12 15:46
I confirmed that adding ```corMinCoverage=0 corOutCoverage=100 contigFilter="2 1000 1.0 1.0 2``` is enough. With ```overlapper=mhap utgReAlign=true```, it runs on our system in about 2hrs. I'd expect ``corMinCoverage=0 contigFilter="2 1000 1.0 1.0 2``` might work as well.

I think your reads are a bit higher error than average, perhaps because the base caller isn't well-trained on your genome which is why corMinCoverage=0 helps. Increasing the corrected coverage for the tiny genome size helps correct more data since otherwise you end up with only a few reads for assembly.

I'm going to close this issue since your original issue, long runtime, is addressed by the overlapper option and you have options you can try on this and other similar datasets.

**Closed by skoren** 2017-04-12 15:46 UTC

**Comment by miles-gene** [comment] 2017-04-12 16:34
Sorry for not replying sooner. I have been trying the settings you suggested on the same data and after many hours canu is still at the read correction stage. I'm pretty sure it's my installation of canu or problems with my Linux VM. Thanks for your help, like you say I now have options I know should work and the original issue was addressed.

**Comment by skoren** [comment] 2017-04-12 16:38
Try also adding ```corPartitions=100 corPartitionMin=100``` assuming you have multiple cores on the system you're running on. By default there will only be one job with 4 cores correcting the reads and if you have more than 4 cores the rest will be idle. The above will parallelize it better.
