### ISSUE TITLE
sbatch: error: Batch job submission failed: Pathname of a file, directory or other parameter too long

### ISSUE THREAD

**Issue by jlim125** [marbl/canu#2149] opened 2022-07-24 01:53 UTC
canu 2.2

Linux, the Yale Cluster (Slurm)
```
canu \
     -p Prefix -d Directory \
     genomeSize=10g \
     maxInputCoverage=100 minInputCoverage=6 stopOnLowCoverage=6 \
     -pacbio-hifi \
     fastq.gz
```
Hello. I have PacBio HiFi reads and tried to run canu 2.2. After creating SeqStore, 0-mercount in unitigging was completed, but 1-overlapper failed with a "sbatch: error: Batch job submission failed: Pathname of a file, directory or other parameter too long".

I have tried to change prefix, --mem-per-cpu, partition, the number of array jobs, etc, but it didn't work. Could you give any advice?

Thank you,
Jaechul

**Comment by skoren** [comment] 2022-07-24 15:18
This sounds like there are too many overlap partitions, how big is the `1-overlapper/overlapper.sh` file? How much coverage do you actually have? The default subset is 50x so running at higher than that will slow down the run/increase partitions and won't help the assembly much.

**Comment by jlim125** [comment] 2022-07-24 15:46
Thank you for prompt response!

Do you mean 1-overlapper/overlap.sh file? It has 679 jobs and ~128 kb. The coverage is ~20.72x. I have attached the examples of jobs in the overlap.sh:

if [ $jobid -eq 1 ] ; then
  bat="001"
  job="001/000001"
  opt="-h 1-87605 -r 1-87605 --hashdatalen 640005822"
fi

...

if [ $jobid -eq 679 ] ; then
  bat="001"
  job="001/000679"
  opt="-h 23388881-23476030 -r 19172233-23476030 --hashdatalen 543847845"
fi

**Comment by skoren** [comment] 2022-07-24 15:49
That seems reasonable, not sure why your slurm scheduler is complaining. Post the overlap.jobSubmit-01.sh/out and canu.out logs here.

**Comment by jlim125** [comment] 2022-07-24 15:59
Thanks. Please find the logs below.

1. overlap.jobSubmit-01.sh

#!/bin/sh

sbatch \
  --cpus-per-task=5 --mem-per-cpu=4915m -o overlap.%A_%a.out \
  -D `pwd` -J "utgovl_Prefix" \
  -a 1-679 \
  `pwd`/overlap.sh 0 \
> ./overlap.jobSubmit-01.out 2>&1

2. overlap.jobSubmit-01.out
sbatch: error: Batch job submission failed: Pathname of a file, directory or other parameter too long

3. canu.out
-- BEGIN ASSEMBLY
-- Meryl finished successfully.  Kmer frequency histogram:
--
--  22-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2 116359215 ******************************************************                 0.1065 0.0016
--       3-     4 128923771 ************************************************************           0.1736 0.0031
--       5-     7 124017516 **********************************************************             0.2664 0.0062
--       8-    11 149216061 ********************************************************************** 0.3720 0.0117
--      12-    16 144503733 *******************************************************************    0.5069 0.0223
--      17-    22  84077279 ***************************************                                0.6242 0.0353
--      23-    29  55944368 **************************                                             0.6927 0.0457
--      30-    37  39730488 ******************                                                     0.7406 0.0553
--      38-    46  31622042 **************                                                         0.7750 0.0642
--      47-    56  29822700 *************                                                          0.8032 0.0732
--      57-    67  31258121 **************                                                         0.8304 0.0839
--      68-    79  25873036 ************                                                           0.8587 0.0973
--      80-    92  16744947 *******                                                                0.8815 0.1100
--      93-   106  12976536 ******                                                                 0.8962 0.1195
--     107-   121  14554963 ******                                                                 0.9080 0.1284
--     122-   137  13227224 ******                                                                 0.9214 0.1399
--     138-   154   9283913 ****                                                                   0.9333 0.1515
--     155-   172   6333270 **                                                                     0.9415 0.1606
--     173-   191   4971417 **                                                                     0.9472 0.1676
--     192-   211   4310828 **                                                                     0.9517 0.1737
--     212-   232   4113210 *                                                                      0.9556 0.1797
--     233-   254   3782123 *                                                                      0.9594 0.1860
--     255-   277   2966946 *                                                                      0.9628 0.1923
--     278-   301   2057567                                                                        0.9655 0.1976
--     302-   326   1909807                                                                        0.9673 0.2016
--     327-   352   3002553 *                                                                      0.9691 0.2058
--     353-   379   4035318 *                                                                      0.9719 0.2130
--     380-   407   2944457 *                                                                      0.9756 0.2231
--     408-   436   1660518                                                                        0.9782 0.2309
--     437-   466   1264319                                                                        0.9797 0.2356
--     467-   497   1190008                                                                        0.9808 0.2396
--     498-   529   1012189                                                                        0.9819 0.2435
--     530-   562   1050344                                                                        0.9829 0.2470
--     563-   596   1077576                                                                        0.9838 0.2510
--     597-   631   1004242                                                                        0.9848 0.2553
--     632-   667    856169                                                                        0.9857 0.2595
--     668-   704    779187                                                                        0.9865 0.2633
--     705-   742    701735                                                                        0.9872 0.2670
--     743-   781    582458                                                                        0.9878 0.2705
--     782-   821    457643                                                                        0.9884 0.2735
--
--           0 (max occurrences)
-- 145535107928 (total mers, non-unique)
--  1092450994 (distinct mers, non-unique)
--           0 (unique mers)
-- Finished stage 'meryl-process', reset canuIteration.
--
-- Removing meryl database 'unitigging/0-mercounts/Prefix.ms22'.
--
-- OVERLAPPER (normal) (assembly) erate=0.01
--
----------------------------------------
-- Starting command on Sat Jul 23 00:20:45 2022 with 65941.035 GB free disk space

    cd unitigging/1-overlapper
    /gpfs/ysm/home/jl2956/bin/canu-2.2/bin/overlapInCorePartition \
     -S  ../../Prefix.seqStore \
     -hl 640000000 \
     -rl 30000000000 \
     -ol 500 \
     -o  ./Prefix.partition \
    > ./Prefix.partition.err 2>&1

-- Finished on Sat Jul 23 00:20:53 2022 (8 seconds) with 65939.972 GB free disk space
----------------------------------------
--
-- Configured 679 overlapInCore jobs.
-- Finished stage 'utg-overlapConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
--
-- Failed to submit compute jobs.  Delay 10 seconds and try again.

CRASH:
CRASH: canu 2.2
CRASH: Please panic, this is abnormal.
CRASH:
CRASH:   Failed to submit compute jobs.
CRASH:
CRASH: Failed at /gpfs/ysm/home/jl2956/bin/canu-2.2/bin/../lib/site_perl/canu/Execution.pm line 1259.
CRASH:  canu::Execution::submitOrRunParallelJob('Prefix', 'utgovl', 'unitigging/1-overlapper', 'overlap', 1, 2, 3, 4, 5, ...) called at /gpfs/ysm/home/jl2956/bin/canu-2.2/bin/../lib/site_perl/canu/OverlapInCore.pm line 394
CRASH:  canu::OverlapInCore::overlapCheck('Prefix', 'utg', 'normal') called at /gpfs/ysm/home/jl2956/bin/canu-2.2/bin/canu line 1012
CRASH:  main::overlap('Prefix', 'utg') called at /gpfs/ysm/home/jl2956/bin/canu-2.2/bin/canu line 1120
CRASH: 
CRASH: Last 50 lines of the relevant log file (unitigging/1-overlapper/overlap.jobSubmit-01.out):
CRASH:
CRASH: sbatch: error: Batch job submission failed: Pathname of a file, directory or other parameter too long
CRASH:

**Comment by skoren** [comment] 2022-07-24 16:07
Everything canu is running seems fine, it's a perfectly valid slurm command. I don't think there's anything we can do to fix it, it's specific to something on your cluster.

Is the assembly in a very deeply nested folder? Try taking the overlap.sh file and editing it to be just a few jobs (remove everything after `if [ $jobid -eq 10 ] ; then` through `if [ $jobid -eq 679 ] ; then .. if`, edit overlap.jobSubmit-01.sh to have `-a 1-9` and run it from inside the 1-overlapper folder to see if it works. If it does, your slurm has a very small limit on job submission script sizes and you'd want to work with your cluster admins to increase it. The workaround would be what I suggested above, editing the file to split it into parts, running each part, waiting for it to finish, and then restart the full command.

**Comment by jlim125** [comment] 2022-07-24 16:57
As you suggested, I tried to remove 10-679 and only run 1-9 in the 1-overlapper folder. It seems like the batch job was successfully submitted without error and each job is running okay. I don't see the sbatch error.

The Canu folder is not deeply nested. Does 1-overlapper need to read raw fastq files? I have 10 different fastq files which have a long filepath.

**Comment by skoren** [comment] 2022-07-27 13:26
The raw reads aren't used by Canu after the initial store building so those paths won't matter. It seems the issue is that a 100kb file is too large for your grid settings. There's no support in Canu for making a smaller file so I think your best option is to manually split the file as I suggested above. Try jobs 1-99, 100-199, 200-299, and so on until the last 600-679 jobs. As long as your previous test of 10 jobs finished, it's safe to re-run the same jobs (they'll see their output is done and do nothing). You probably will only have to do this for the overlapping step as others should have fewer partitions but given your genome size I might be wrong about that.

I'd also suggest asking your grid administrators if they can increase the submit file size limit as it seems quite low.

**Comment by jlim125** [comment] 2022-07-27 18:13
Thank you, Sergey! Yes, I was able to split the jobs (100 or 200) and run them separately. It worked well.

**Comment by skoren** [comment] 2022-08-06 16:26
Resolved by splitting batch script into multiple smaller ones. Won't fix as the file size is not too large and this is the only time it's caused an issue with the submission.

**Closed by skoren** 2022-08-06 16:26 UTC
