### ISSUE TITLE
Canu run errors

### ISSUE THREAD

**Issue by newcanu** [marbl/canu#1108] opened 2018-10-04 23:22 UTC
I managed to install canu successfully on ubuntu v18, however I am having issues trying to run the program.

This is how I start the program:

canu-1.7.1/*/bin/canu -p assem -d canu_outdir genomeSize=100k -nanopore-raw ../data/

Canu starts fine then fails with the following message:
```
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '10.0.2' (from 'java').
-- Detected gnuplot version '5.2 patchlevel 2' (from 'gnuplot') and image format 'png'.
-- Detected 8 CPUs and 16 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------  -----------------------------
-- Local: meryl      8 GB    4 CPUs x   1 job      8 GB    4 CPUs  (k-mer counting)
-- Local: cormhap    6 GB    8 CPUs x   1 job      6 GB    8 CPUs  (overlap detection with mhap)
-- Local: obtovl     4 GB    8 CPUs x   1 job      4 GB    8 CPUs  (overlap detection)
-- Local: utgovl     4 GB    8 CPUs x   1 job      4 GB    8 CPUs  (overlap detection)
-- Local: ovb        2 GB    1 CPU  x   8 jobs    16 GB    8 CPUs  (overlap store bucketizer)
-- Local: ovs        8 GB    1 CPU  x   2 jobs    16 GB    2 CPUs  (overlap store sorting)
-- Local: red        4 GB    4 CPUs x   2 jobs     8 GB    8 CPUs  (read error detection)
-- Local: oea        4 GB    1 CPU  x   4 jobs    16 GB    4 CPUs  (overlap error adjustment)
-- Local: bat       16 GB    4 CPUs x   1 job     16 GB    4 CPUs  (contig construction)
-- Local: gfa        8 GB    4 CPUs x   1 job      8 GB    4 CPUs  (GFA alignment and processing)
--
-- In 'assem.gkpStore', found Nanopore reads:
--   Raw:        1382
--   Corrected:  0
--   Trimmed:    0
--
-- Generating assembly 'assem' in '/minion/software/canu_outdir'
--
-- Parameters:
--
--  genomeSize        100000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1440 ( 14.40%)
--    utgOvlErrorRate 0.1440 ( 14.40%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1440 ( 14.40%)
--    utgErrorRate    0.1440 ( 14.40%)
--    cnsErrorRate    0.1920 ( 19.20%)
--
--
-- BEGIN CORRECTION
--
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Fri Oct  5 09:15:02 2018 with 1396.541 GB free disk space (1 processes; 1 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1

-- Finished on Fri Oct  5 09:15:02 2018 (lickety-split) with 1396.541 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, retry.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cormhap' concurrent execution on Fri Oct  5 09:15:02 2018 with 1396.541 GB free disk space (1 processes; 1 concurrently)

    cd correction/1-overlapper
    ./precompute.sh 1 > ./precompute.000001.out 2>&1

-- Finished on Fri Oct  5 09:15:02 2018 (lickety-split) with 1396.541 GB free disk space
----------------------------------------
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000001.dat FAILED.
--

ABORT:
ABORT: Canu 1.7.1
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```
I am new to linux based systems, can anyone help identify why I am getting this error?

**Comment by skoren** [comment] 2018-10-05 16:02
The issue is your java version (see issue #901 and #909). This is fixed in the tip but not the release. You can either patch the code as described in issue #909 (remove any -d64 you find in the OverlapMhap.pm file) or install java 8 and use that for Canu instead.

**Closed** 2018-10-10 13:22 UTC
