### ISSUE TITLE
Assembler disregards long read

### ISSUE THREAD

**Issue by eleniadam** [marbl/canu#1018] opened 2018-07-25 16:34 UTC
Hello,

While I was trying to use Canu for assembling nanopore 20x coverage data, I am not sure whether I am using the correct parameters for this case. The assembler works but I run into the following issues.

I used the command: 
./canu -p out_folder -d int_folder genomeSize=500k -nanopore-raw input/*.fa

- The output corrected reads (fasta file) of the first stage, when I aligned them (minimap2) and visualized them (genomeribbon), this is what they looked like:
![corrected](https://user-images.githubusercontent.com/31490261/43213315-50ddb822-9004-11e8-8a37-926579bfa02c.png)

- The output trimmed reads (fasta file) of the second stage, were these:
![trimmed](https://user-images.githubusercontent.com/31490261/43213427-981a890e-9004-11e8-8dfc-5d67fbc806cd.png)

* The problem is that, there is a long read that goes to the right side (the one designated with the bold line), which is being trimmed and is not included in the final contig, which makes sense since after the trimming it's covered by the rest of the reads. 
It is really important to keep this read in the final contig and have a much larger assembly (that covers this right side).

To resolve this, I extracted this corrected read (from the fasta file) and replaced it in the trimmed reads (in the fasta file), in order to pass by the trimming stage for this read. However, this did not help. Still, the read was not placed into the final contig and it was defined as "no-5-prime".

I am not sure what the issue is, I tried using different parameters, for example having a greater error, but still it did not help. Could it be that there aren't other reads to overlap with on that right side and that's why it removes it?

Is it possible to keep it in the final contig by changing the parameters in any way? Or by adding more reads on that right side?

Thank you very much,
Eleni

**Comment by skoren** [comment] 2018-07-25 16:45
It isn't surprising the read is being trimmed, there is no other sequence supporting sequences and has no overlaps off one end. This is a signal of a bad sequencing read which is why it's being discarded. I think this is the correct behavior for the general case.

Have you mapped the raw reads and confirmed it's really the only read from that region like your plot shows? I'm not sure why your sequencing would end up with no data from about half your genome. That seems suspicious. 

You could try to force it to assemble by skipping trimming (run ```canu -correct -nanopore-raw <data>``` and ```canu -assemble -nanopore-corrected <first run/correctedReads.fasta.gz>```) and adding ```batOptions="-nofilter spur"``` which will keep reads that have an overlap on only one end. You could also add ```corMinCoverage=0``` to keep more data from correction.

**Comment by eleniadam** [comment] 2018-07-25 17:08
- This is the image of the raw reads and the final contig (in bold):
![rawdata](https://user-images.githubusercontent.com/31490261/43215973-9eb71b18-900b-11e8-9a79-9b299527f550.png)

Unfortunately, there are no other reads in that region. 
If this is the cause of the problem and there is no way to overcome it with parameter changes, I will try to get more reads in order to have more overlaps. 

But first, I will try the batOptions="-nofilter spur" parameter as you suggested, since I have not used it before.

Thank you,
Eleni

**Comment by skoren** [comment] 2018-07-25 17:14
Higher coverage would be ideal since with just one read in the region you'll have a low-quality consensus for half your genome (equal to the raw error rate of the one read).

**Comment by skoren** [comment] 2018-11-07 18:47
Idle, closing since nothing to fix. The trimming of an unsupported single read is intentional.

**Closed by skoren** 2018-11-07 18:47 UTC
