### ISSUE TITLE
Canu iteration too high

### ISSUE THREAD

**Issue by price333** [marbl/canu#515] opened 2017-06-04 20:54 UTC
Hi there,

I'm getting an error on one of my nanopore datasets, the rest assemble just fine.

I'm running canu on a cluster with SLURM as the resource manager.

Here is the command:
canu -p test -d new_canu genomeSize=240k -nanopore-raw test.fastq

This is the error I get at the end of canu.out:
```
-- BEGIN CORRECTION
--
--
-- 1 read correction jobs failed:
--   job correction/2-correction/correction_outputs/0001.fasta FAILED.

ABORT:
ABORT: Canu snapshot v1.5 +54 changes (r8254 f356c2c3f2eb37b53c4e7bf11e927e3fdff4d747)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   canu iteration count too high, stopping pipeline (most likely a problem in the grid-based computes).
ABORT:
```

Restarting the job doesn't seem to solve the problem.

Any help would be greatly appreciated!

**Comment by caonetto** [comment] 2017-06-05 04:43
I had the exact same problem today with the latest unrelease of github,
-- 10 read correction jobs failed:
--   job correction/2-correction/correction_outputs/0001.fasta FAILED.
--   job correction/2-correction/correction_outputs/0002.fasta FAILED.
--   job correction/2-correction/correction_outputs/0003.fasta FAILED.
--   job correction/2-correction/correction_outputs/0004.fasta FAILED.
--   job correction/2-correction/correction_outputs/0005.fasta FAILED.
--   job correction/2-correction/correction_outputs/0006.fasta FAILED.
--   job correction/2-correction/correction_outputs/0007.fasta FAILED.
--   job correction/2-correction/correction_outputs/0008.fasta FAILED.
--   job correction/2-correction/correction_outputs/0009.fasta FAILED.
--   job correction/2-correction/correction_outputs/0010.fasta FAILED.

ABORT:
ABORT: Canu snapshot v1.5 +54 changes (r8254 f356c2c3f2eb37b53c4e7bf11e927e3fdff4d747)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   canu iteration count too high, stopping pipeline (most likely a problem in the grid-based computes).
ABORT:

Anyone found a solution to this problem?

**Comment by skoren** [comment] 2017-06-06 15:38
I don't think this is the same as issue #513 because you're running the unreleased code which would fix that bug. The likeliest issue is insufficient memory being requested for the job. Can you check one of the job output files (```correction/2-correction/correctReads.*.out```), that should have more information on why a specific job stopped.

**Comment by caonetto** [comment] 2017-06-07 00:14
Thanks for you reply Skoren, files 1-10, (correctReads.*.out) have the same output.

```
Running job 9 based on command line options.
Killed
Read layout generation failed.
mv: cannot stat \u2018./correction_outputs/0009.fasta\u2019: No such file or directory
```

Any ideas on what could be the problem??

Thanks!

**Comment by skoren** [comment] 2017-06-07 14:05
Killed implies the grid terminated it so memory is most likely. Try running with ```corMemory=32``` or ```corMemory=64``` (see issue #504).

**Comment by skoren** [comment] 2017-06-13 19:25
I updated issue #504 with more details and info on maximum memory usage, corMemory=35 should be sufficient for reads up to 2mb in size. I'm closing this issue as a duplicate of #504 and will keep that one open until we fix Canu's memory estimate for this step. Open a new issue if you encounter another error with this assembly.

**Closed by skoren** 2017-06-13 19:25 UTC

**Comment by caonetto** [comment] 2017-06-13 21:57
Thanks for your help Sergey.

Sent from my iPhone

On 14 Jun 2017, at 4:55 am, Sergey Koren <notifications@github.com<mailto:notifications@github.com>> wrote:


I updated issue #504<https://github.com/marbl/canu/issues/504> with more details and info on maximum memory usage, corMemory=35 should be sufficient for reads up to 2mb in size. I'm closing this issue as a duplicate of #504<https://github.com/marbl/canu/issues/504> and will keep that one open until we fix Canu's memory estimate for this step. Open a new issue if you encounter another error with this assembly.
