### ISSUE TITLE
gkpStore without correction.

### ISSUE THREAD

**Issue by migrau** [marbl/canu#1233] opened 2019-02-07 02:27 UTC
If I run canu (v1.7 +114 changes (r8806 c875536f014fb9096fb2dc14cbf30a2ca09e7bd6) with the `-nanopore-corrected` parameter,  I can't find the `gkpStore` in the output folder. Is it generated only with `-nanopore-raw`?

Actually I am not interested in the canu correction, the reads are already corrected, but I want to check the coverage per contig using:
`tgStoreDump -G sample.gkpStore -T sample.ctgStore 2 -o OUT -coverage -tig 1-10`

If I run canu using ` -nanopore-raw`, I got an error. This is the output of file `correction/2-correction/results/0001.err`:
```
Processing read 11 of length 2319 with 5 evidence reads.
ALIGN to 0-2319 length 2319
ALIGN to 0-2130 length 2319
ALIGN to 0-1398 length 2319
ALIGN to 0-2319 length 2319
read54221 #2 location 0 to template 39-1273 length 1234 diff 0.123177
mapped 54221     0- 1245 to template     39-  1274 trimmed by      0-     0 TGATACTTAT TGATACTTAT
ALIGN to 787-2103 length 2319
read42756 #4 location 0 to template 109-1209 length 1100 diff 0.158182
mapped 42756     0- 1087 to template    896-  1997 trimmed by      0-     0 CATCCCCTTC CATCCCCTTC
ALIGN to 913-2058 length 2319
read11 #0 location 0 to template 0-2318 length 2318 diff 0.000000
mapped    11     0- 2319 to template      0-  2319 trimmed by      0-     0 GTACCCTATA GTACCCTATA
read13216 #5 location 0 to template 93-1051 length 958 diff 0.191023
mapped 13216     0-  922 to template   1006-  1965 trimmed by      0-     0 TTCTTTAAAT TTCTTTAAAT
read42702 #1 location 0 to template 295-1908 length 1613 diff 0.202108
read42702 #1 location 1 to template 295-1909 length 1614 diff 0.201983
mapped 42702     0- 1653 to template    295-  1909 trimmed by      0-     1 TATTTCATTG CAT---ATTG
read55796 #3 location 0 to template 120-2230 length 2110 diff 0.127488
read55796 #3 location 1 to template 120-2231 length 2111 diff 0.127428
read55796 #3 location 2 to template 120-2232 length 2112 diff 0.127367
read55796 #3 location 3 to template 120-2233 length 2113 diff 0.127307
falconsense: overlapInCore/libedlib/edlib.C:347: void edlibAlignmentToStrings(const unsigned char*, int, int, int, int, int, const char*, const char*, char*, char*): Assertion `strlen(qry_aln_str) == alignmentLength && strlen(tgt_aln_str$

Failed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::97 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
```

I tried the solution from here (https://github.com/marbl/canu/issues/881) but deleting the read from .readsToCorrect didn't work. The fasta file contain ~125k reads, with an averae of 5kbp length, but there are reads very long, ~32kbp. Can it be a problem?

Many thanks,

**Comment by skoren** [comment] 2019-02-07 16:33
You're in between two version, the gkpStore got renamed to seqStore between Canu 1.7 and 1.8 so you may have a seqStore instead. I'd suggest switching to 1.8 or tip instead for your work.

As for the crash, that was caused by non-ACGT sequences in your reads and was also fixed in 1.8 (see #1061).

**Comment by migrau** [comment] 2019-02-08 06:39
Thanks skoren. Using the last canu version it generates the seqStore file but, ctgStore=`<tigStore>`? 
I am running :
`tgStoreDump -S nano.seqStore -T unitigging/nano.ctgStore 2 -coverage -o OUT -tig 1-10`
but not output/error at all.

**Comment by skoren** [comment] 2019-02-08 15:31
The output goes to the files named out* in your case. There should be a ```*.depth``` and a ```*.png`` file for each of the tigs you requested in the current folder.

**Comment by migrau** [comment] 2019-02-09 00:05
Perfect, many thanks!

**Closed** 2019-02-09 00:06 UTC
