### ISSUE TITLE
canu failed with 'Failed to submit batch jobs'.

### ISSUE THREAD

**Issue by agroppi** [marbl/canu#424] opened 2017-03-27 13:00 UTC
Hi,

I suppose it's something like #54 and/or #73 but I'm a bit lost on how to solve this and resume the canu 1.4 pipeline .
```

Please panic.  canu failed, and it shouldn't have.

Stack trace:

 at /module/apps/canu/1.4/Linux-amd64/bin/lib/canu/Execution.pm line 1370.
	canu::Execution::caFailure("Failed to submit batch jobs", undef) called at /module/apps/canu/1.4/Linux-amd64/bin/lib/canu/Execution.pm line 1000
	canu::Execution::submitOrRunParallelJob("vriparia_3kb", "ovS", "correction/vriparia_3kb.ovlStore.BUILDING", "scripts/2-sort", 1, 2, 3, 4, 5, ...) called at /module/apps/canu/1.4/Linux-amd64/bin/lib/canu/OverlapStore.pm line 510
	canu::OverlapStore::overlapStoreSorterCheck("correction", "vriparia_3kb", "cor", "correction/1-overlapper/ovljob.files") called at /module/apps/canu/1.4/Linux-amd64/bin/lib/canu/OverlapStore.pm line 536
	canu::OverlapStore::createOverlapStoreParallel("correction", "vriparia_3kb", "cor", "correction/1-overlapper/ovljob.files") called at /module/apps/canu/1.4/Linux-amd64/bin/lib/canu/OverlapStore.pm line 592
	canu::OverlapStore::createOverlapStore("vriparia_3kb", "cor", "parallel") called at /module/apps/canu/1.4/Linux-amd64/bin/canu line 485
	main::overlap("vriparia_3kb", "cor") called at /module/apps/canu/1.4/Linux-amd64/bin/canu line 504


canu failed with 'Failed to submit batch jobs'.
Exit Code: 1
```

Thanks for your help

Best regards

**Comment by skoren** [comment] 2017-03-27 14:18
There should be more information on why the submit command failed in the
```correction/asm.ovlStore.BUILDING/logs/2-sort.jobSubmit.out```
That will give the specific reason your grid rejected the job. Depending on the reason you may be able to adjust grid options. Otherwise, you'll have to manually run the failed submit script (something like ```correction/asm.ovlStore.BUILDING/logs/2-sort.jobSubmit.out```), wait for it to complete, then run with ```useGrid=remote``` and manually submit/wait for jobs (see issue #421 for details).

**Comment by agroppi** [comment] 2017-03-27 14:25
Thanks for your answer.
But I don't have `correction/asm.ovlStore.BUILDING/logs/2-sort.jobSubmit.out`

Here is the listing of the correction directory : 

```
drwxr-xr-x   2 ag users 4,0K 24 mars  16:01 0-mercounts
drwxr-xr-x   5 ag users  12K 26 mars  13:15 1-overlapper
drwxr-xr-x   2 ag users 4,0K 24 mars  14:37 vriparia_3kb.gkpStore
-rw-r--r--   1 ag users  470 24 mars  14:37 vriparia_3kb.gkpStore.err
-rw-r--r--   1 ag users  232 24 mars  14:20 vriparia_3kb.gkpStore.gkp
drwxr-xr-x 137 ag users 4,0K 26 mars  13:21 vriparia_3kb.ovlStore.BUILDING
```

**Comment by skoren** [comment] 2017-03-27 14:25
Check the ```vriparia_3kb.ovlStore.BUILDING/logs``` and ```scripts``` folders.

**Comment by agroppi** [comment] 2017-03-27 14:28
`vriparia_3kb.ovlStore.BUILDING/log` is empty
In `/scripts` :  `2-sort.jobSubmit.out` : 
`qsub: submit error (Illegal attribute or resource value for  Resource_List.mem)`

**Comment by skoren** [comment] 2017-03-27 14:30
That should be fixable by adjusting your command. What is your full Canu command and how do you request memory on your cluster? What's the submit command in the corresponding sh file (```2-sort.jobSubmit.sh```)

**Comment by agroppi** [comment] 2017-03-27 14:33
In 2-sort.jobSubmit.sh : 
```
#!/bin/sh

qsub \
  -l mem=4-16g -l nodes=1:ppn=1 -V \
  -d `pwd` -N "ovS_vriparia_3kb" \
  -t 1-44 \
  -j oe -o scripts/2-sort.\$PBS_ARRAYID.out \
  ./scripts/2-sort.sh  \
> ./scripts/2-sort.jobSubmit.out 2>&1
```

My PBS job for the whole Canu pipeline : 
```

# Your job name (displayed by the queue)
#PBS -N Canu_pacbio_assembly_Vitireseq_All_SMRT_fasta3kb
# Specify the working directory
#PBS -d /scratch/ag

# Merge ouput and error files
#PBS -j oe

# Put stout and stderr to homedir
#PBS -k oe

# Mail job status at the start and end of a job
#PBS -m abe
#PBS -M alexis.groppi@u-bordeaux.fr

# walltime (hh:mm::ss)
#PBS -l walltime=240:00:00

# Specify the number of nodes(nodes=) and the number of cores per nodes(ppn=) to be used
#PBS -l nodes=1:ppn=16

# fin des directives PBS

#############################

# useful informations to print
echo "#############################" 
echo "User:" $USER
echo "Date:" `date`
echo "Host:" `hostname`
echo "Directory:" `pwd`
echo "PBS_JOBID:" $PBS_JOBID
echo "PBS_O_WORKDIR:" $PBS_O_WORKDIR
echo "PBS_NODEFILE: " `cat $PBS_NODEFILE | uniq`
echo "#############################" 

module load java/1.8.0_72
module load canu/1.4


echo "#############################" 
echo "Canu 1.4 Correct, Trim and Assemble:" `date`
canu gridOptions='-V' -p vriparia_3kb -d $PBS_O_WORKDIR/Vriparia_Canu_1.4_all_reads_fastq_3kb corMhapSensitivity=low corOutCoverage=106 genomeSize=500m -pacbio-raw /scratch/ag/Vitireseq_Fastq_3kb/Vitireseq_All_Fastq_3kb.fastq
```

**Comment by agroppi** [comment] 2017-03-27 14:37
We don't request memory on our cluster.
The maximum memory is 512 Go

**Comment by skoren** [comment] 2017-03-27 14:40
The issue is that Canu didn't translate its range of values (4-16) to a single value (e.g. 4) which caused the error. Edit the script to be ```-l mem=16g``` instead of ```-l mem=4-16g``` and run it manually from inside the ```vriparia_3kb.ovlStore.BUILDING``` folder to see if it completes. 

What version of Canu are you using, ```canu --version```. It's possible you have a repo snapshot between releases that had a bug.

**Comment by agroppi** [comment] 2017-03-27 14:47
Canu v0.0 (+0 commits) r0 unknown-hash-tag-no-repository-available.
Strange  ?
But I know that the version was downloaded and installed from canu-master.zip by mid february (14/02/2017)

**Comment by skoren** [comment] 2017-03-27 14:51
So canu-master.zip is not a release, it's just a snapshot (the version is related to issue #419). There's no guarantee that the master is stable at any given point, you got on around the time that we made some major changes to how Canu runs to enable cloud-service support. I would suggest either using a release version (1.4, but you'd have to restart this assembly from scratch) or using a checkout so and updating the code to the latest and see if the issue is removed (this should work without restarting).

**Comment by agroppi** [comment] 2017-03-27 14:56
OK thanks. I'll will see with our IT team
For the moment, I've launched the modified 2-sort.jobSubmit.sh
After it finishes, I have to re launch the initial canu pipeline ? OK ?
Many thanks for your help

**Comment by skoren** [comment] 2017-03-27 14:57
Yes, once the sort jobs complete, you can re-run the original command and it will resume. This sort step happens 3 times in the pipeline so you can follow the same steps when it fails again if you keep running with this version.

**Comment by agroppi** [comment] 2017-04-05 09:56
@skoren As predicted the pipeline stoped 2 days ago and I relaunched it using the same procedure.
This morning it stops again with the following error : 
```
 at /module/apps/canu/1.4/Linux-amd64/bin/lib/canu/Execution.pm line 1370.
	canu::Execution::caFailure("Failed to submit batch jobs", undef) called at /module/apps/canu/1.4/Linux-amd64/bin/lib/canu/Execution.pm line 1000
	canu::Execution::submitOrRunParallelJob("vriparia_3kb", "ovS", "trimming/vriparia_3kb.ovlStore.BUILDING", "scripts/2-sort", 1, 2, 3, 4, 5, ...) called at /module/apps/canu/1.4/Linux-amd64/bin/lib/canu/OverlapStore.pm line 510
	canu::OverlapStore::overlapStoreSorterCheck("trimming", "vriparia_3kb", "obt", "trimming/1-overlapper/ovljob.files") called at /module/apps/canu/1.4/Linux-amd64/bin/lib/canu/OverlapStore.pm line 536
	canu::OverlapStore::createOverlapStoreParallel("trimming", "vriparia_3kb", "obt", "trimming/1-overlapper/ovljob.files") called at /module/apps/canu/1.4/Linux-amd64/bin/lib/canu/OverlapStore.pm line 592
	canu::OverlapStore::createOverlapStore("vriparia_3kb", "obt", "parallel") called at /module/apps/canu/1.4/Linux-amd64/bin/canu line 485
	main::overlap("vriparia_3kb", "obt") called at /module/apps/canu/1.4/Linux-amd64/bin/canu line 535
```
I correct the file `/trimming/vriparia_3kb.ovlStore.BUILDING/scripts/2-sort.jobSubmit.sh` in the same way as previously (`-l mem=16g` instead of `-l mem=4-16g`)
I launch it manually. It runs.
But when I relaunch the initial Canu Pipeline : its stops immediatly whith the same error. 
And the file `/trimming/vriparia_3kb.ovlStore.BUILDING/scripts/2-sort.jobSubmit.sh` is re created with its original `-l mem=4-16g`

How can I circumvent this issue ?

Thanks 

Alexis

**Comment by brianwalenz** [comment] 2017-04-05 12:27
`ovsMemory=16` will force it to use 16g, instead of trying to pick a value between 4 and 16g.  I think this was fixed in a4f5e943f559303fb4c987e5e1a6678a42a988d8, on Feb 24.

**Comment by agroppi** [comment] 2017-04-05 12:31
Thanks !
Should I replace `-l mem=4-16g` with `ovsMemory=16` in `/trimming/vriparia_3kb.ovlStore.BUILDING/scripts/2-sort.jobSubmit.sh`
Or in another place ?
Thanks again
Alexis

**Comment by agroppi** [comment] 2017-04-05 13:08
OK
1/ I correct the file /trimming/vriparia_3kb.ovlStore.BUILDING/scripts/2-sort.jobSubmit.sh in the same way as previously (-l mem=16g instead of -l mem=4-16g)
2/ I launch it manually
3 / I relaunch the initial Canu Pipeline with the option : `ovsMemory=16`

Can you confirm that this is correct ?

Thanks

**Comment by brianwalenz** [comment] 2017-04-05 13:15
That would work.  Only do step 3 after all jobs in step 2 complete!

**Comment by agroppi** [comment] 2017-04-06 07:47
@brianwalenz Unfortnutaly it doesn't work. Canu stops and the the file /trimming/vriparia_3kb.ovlStore.BUILDING/scripts/2-sort.jobSubmit.sh is re created now with -l mem=16-16g

What can I do ?

Thanks

**Comment by skoren** [comment] 2017-04-06 12:07
Did you manually run the 2-sort.jobSubmit.sh script modified to use -l mem=16g? Did all the jobs complete, are there any errors in any of the logs/2-sort.\*.out files?

**Comment by agroppi** [comment] 2017-04-06 12:34
Yes `I run 2-sort.jobSubmit.sh script modified to use -l mem=16g`
All the jobs were completed
`logs/ `is empty
in `/trimming/vriparia_3kb.ovlStore.BUILDING/scripts` : 
`2-sort.jobSubmit.out` : 
`qsub: submit error (Illegal attribute or resource value for  Resource_List.mem)`

**Comment by skoren** [comment] 2017-04-06 12:36
I am not sure any of your jobs ran if there is a submit error, are you sure the edited 2-sort.jobSubmit.sh script is correct? Do you have any ```2-sort.*.out``` in scripts?

**Comment by agroppi** [comment] 2017-04-06 12:48
in /trimming/vriparia_3kb.ovlStore.BUILDING/scripts :
2-sort.jobSubmit.out :
qsub: submit error (Illegal attribute or resource value for Resource_List.mem)

**Comment by skoren** [comment] 2017-04-06 13:27
If you don't have any ```2-sort.*.out``` in either logs or scripts then I don't think any of your manually submitted jobs ran. Are you sure the edited command in 2-sort.jobSubmit.sh is correct and was submitted/ran on your grid? This should be the exact same process you used to resume the assembly on the previous crash (10 days ago).

**Comment by agroppi** [comment] 2017-04-10 12:02
@skoren @brianwalenz 
After many unsuccessful attempts ... I give up
I restart from scratch with a good version (from git) of Canu 1.4
Thanks for all ! :)

**Comment by skoren** [comment] 2017-04-10 12:27
I would suggest updating to the latest from github, we're testing the next release now so you'd essentially be running the 1.5 release. You can also restart after correction by using ```-pacbio-corrected asm.correctedReads.fasta.gz``` rather than the raw input reads.

I'm going to close the issue since it's drifted a bit from the original bug. Open a new issue if you encounter errors with your run.

**Closed by skoren** 2017-04-10 12:27 UTC
