### ISSUE TITLE
"Kmer counting (meryl-count) jobs failed, tried 2 times, giving up."

### ISSUE THREAD

**Issue by cmaggior** [marbl/canu#1603] opened 2020-01-21 21:18 UTC
Using the command canu -assemble -p prefix -d directory genomeSize=3.4m -nanopore-corrected data.fasta.gz, I'm receiving the following output:

```
Found perl:
   /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/perl/5.22.4/bin/perl
   This is perl 5, version 22, subversion 4 (v5.22.4) built for x86_64-linux-thread-multi

Found java:
   /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/java/13.0.1/bin/java
   openjdk version "13.0.1" 2019-10-15

Found canu:
   /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx512/Compiler/gcc7.3/canu/1.9/bin/canu
   Canu 1.9

-- Canu 1.9
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '13.0.1' (from '/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/java/13.0.1/bin/java') without -d64 support.
-- Detected gnuplot version '5.0 patchlevel 3   ' (from 'gnuplot') and image format 'png'.
-- Detected 40 CPUs and 93 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /opt/software/slurm/bin/sinfo.
-- Detected Slurm with task IDs up to 9999 allowed.
-- 
-- Found 688 hosts with  40 cores and  186 GB memory under Slurm control.
-- Found  12 hosts with  40 cores and  752 GB memory under Slurm control.
-- Found 172 hosts with  40 cores and   92 GB memory under Slurm control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl      9 GB    4 CPUs  (k-mer counting)
-- Grid:  hap        8 GB    4 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap    6 GB   10 CPUs  (overlap detection with mhap)
-- Grid:  obtovl     4 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl     4 GB    8 CPUs  (overlap detection)
-- Grid:  cor        8 GB    4 CPUs  (read correction)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs        8 GB    1 CPU   (overlap store sorting)
-- Grid:  red        9 GB    4 CPUs  (read error detection)
-- Grid:  oea        8 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat       16 GB    4 CPUs  (contig construction with bogart)
-- Grid:  cns      --- GB    4 CPUs  (consensus)
-- Grid:  gfa       16 GB    4 CPUs  (GFA alignment and processing)
--
-- In 'test_assemble2.seqStore', found Nanopore reads:
--   Raw:        0
--   Corrected:  139918
--   Trimmed:    139918
--
-- Generating assembly 'test_assemble2' in '/lustre03/project/6002454/cmaggior/Arctic2018_Trimmed/testFull_3/test_trim/test-assemble2'
--
-- Parameters:
--
--  genomeSize        3400000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1200 ( 12.00%)
--    utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1200 ( 12.00%)
--    utgErrorRate    0.1200 ( 12.00%)
--    cnsErrorRate    0.2000 ( 20.00%)
--
--
-- BEGIN ASSEMBLY
--
-- No change in report.
--
-- Kmer counting (meryl-count) jobs failed, tried 2 times, giving up.
--   job test_assemble2.01.meryl FAILED.
--

ABORT:
ABORT: Canu 1.9
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

```

This is using canu 1.9 on a Linux computer cluster. Any advice?

**Comment by skoren** [comment] 2020-01-21 21:23
Post any out files from that step (```assembly/0-*/*.out```).

**Comment by cmaggior** [comment] 2020-01-21 21:33
Within the unitigging folder?

```
Found perl:
   /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/perl/5.22.4/bin/perl
   This is perl 5, version 22, subversion 4 (v5.22.4) built for x86_64-linux-thread-multi

Found java:
   /cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/java/13.0.1/bin/java
   openjdk version "13.0.1" 2019-10-15

Found canu:
   /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx512/Compiler/gcc7.3/canu/1.9/bin/canu
   Canu 1.9

Running job 1 based on SLURM_ARRAY_TASK_ID=1 and offset=0.
Enabling 4 threads.

Counting 375 (estimated)  million canonical 22-mers from 1 input file:
    canu-seqStore: ../../test_assemble2.seqStore


SIMPLE MODE
-----------

  Disabled for mers larger than 20.


COMPLEX MODE
------------

prefix     # of   struct   kmers/    segs/     data    total
  bits   prefix   memory   prefix   prefix   memory   memory
------  -------  -------  -------  -------  -------  -------
     1     2  P   252 kB   187 MM    15 kS  2017 MB  2017 MB
     2     4  P   246 kB    93 MM  7882  S  1970 MB  1970 MB
     3     8  P   241 kB    46 MM  3847  S  1923 MB  1923 MB
     4    16  P   236 kB    23 MM  1877  S  1877 MB  1877 MB
     5    32  P   232 kB    11 MM   915  S  1830 MB  1830 MB
     6    64  P   230 kB  6004 kM   446  S  1784 MB  1784 MB
     7   128  P   231 kB  3002 kM   217  S  1736 MB  1736 MB
     8   256  P   240 kB  1501 kM   106  S  1696 MB  1696 MB
     9   512  P   264 kB   750 kM    52  S  1664 MB  1664 MB
    10  1024  P   312 kB   375 kM    25  S  1600 MB  1600 MB  Best Value!
    11  2048  P   432 kB   187 kM    13  S  1664 MB  1664 MB
    12  4096  P   640 kB    93 kM     6  S  1536 MB  1536 MB
    13  8192  P  1088 kB    46 kM     3  S  1536 MB  1537 MB
    14    16 kP  2048 kB    23 kM     2  S  2048 MB  2050 MB
    15    32 kP  3840 kB    11 kM     1  S  2048 MB  2051 MB
    16    64 kP  7680 kB  6005  M     1  S  4096 MB  4103 MB
    17   128 kP    15 MB  3003  M     1  S  8192 MB  8207 MB
    18   256 kP    30 MB  1502  M     1  S    16 GB    16 GB
    19   512 kP    60 MB   751  M     1  S    32 GB    32 GB


FINAL CONFIGURATION
-------------------

Configured complex mode for 1.563 GB memory per batch, and up to 1 batch.

kmerCountFileWriter()-- Creating './test_assemble2.01.meryl.WORKING' for 22-mers, with prefixSize 10 suffixSize 34 numFiles 64
Loading kmers from '../../test_assemble2.seqStore' into buckets.
Used 0.284 GB out of 3.000 GB to store         1237 kmers.
Used 0.409 GB out of 3.000 GB to store     31494228 kmers.
Used 0.534 GB out of 3.000 GB to store     63054204 kmers.
Used 0.659 GB out of 3.000 GB to store     94633400 kmers.
Used 0.784 GB out of 3.000 GB to store    126170512 kmers.
Used 0.909 GB out of 3.000 GB to store    157706241 kmers.
Used 1.034 GB out of 3.000 GB to store    189237337 kmers.
Used 1.159 GB out of 3.000 GB to store    220773782 kmers.
Used 1.284 GB out of 3.000 GB to store    252322288 kmers.
Used 1.409 GB out of 3.000 GB to store    283845275 kmers.
Used 1.534 GB out of 3.000 GB to store    315351046 kmers.
Used 1.659 GB out of 3.000 GB to store    346877923 kmers.
Used 1.784 GB out of 3.000 GB to store    378423415 kmers.

Writing results to './test_assemble2.01.meryl.WORKING', using 4 threads.
writeToFile()-- After writing 1 out of 1 'dataBlockLenMax' objects (8 bytes each): Cannot allocate memory
writeToFile()-- After writing 1 out of 1 'dataBlockLenMax' objects (8 bytes each): Cannot allocate memory
```

**Comment by skoren** [comment] 2020-01-21 21:53
Interesting, we've had this out of memory issue pop up in a few issue (#1502, #1600) but we haven't found an exact cause and haven't been able to reproduce it locally. It may be filesystem related or I/O overhead related. Do you know what filesystem you have?

Try restricting meryl to 1 thread (merylThreads=1) and re-run from scratch in a new folder to see if that fixes it. I'd also be curious if you can get a memory report by running the job manually on a compute node (```sh meryl-count.sh 1``` in the ```unitigging/0-mercounts folder``` then ```vmstat -s``` right after the job fails).

**Comment by LesterWYoung** [comment] 2020-01-21 22:07
Getting the same error message, although I'm using version 1.8 and PacBio-raw. 

canu -p PMKlongBACs -d PMKbacs-raw-reads genomeSize=150k -pacbio-raw PMK_PacBio_reads.fasta.gz

[canu.out.txt](https://github.com/marbl/canu/files/4093926/canu.out.txt)

In correction/0-mercounts/meryl-count.34876059_2.out the last line says that some processes may have been killed by an out of memory handler

[meryl-count.34876059_2.out.txt](https://github.com/marbl/canu/files/4093963/meryl-count.34876059_2.out.txt)

**Comment by skoren** [comment] 2020-01-21 22:12
@LesterWYoung the source of your error is not the same, the grid handler is killing your meryl job for exceeding memory requested. I think this may be because you're a bit out of date and memory requests have been updated since then. Add ```gridOptionsmeryl="--mem-per-cpu=12g"```

**Comment by elbourret** [comment] 2020-01-22 12:37
I had the same problem as @cmaggior, on Canu 1.9 SLURM grid, fixed by deleting `results/unitigging/0-mercounts` and restarting with `merylThreads=1`.

Without `merylThreads=1`, this is the tail of one of the failing jobs `results/unitigging/0-mercounts/meryl-count.*_10.out`:
```
[...]
Used 11.413 GB out of 13.000 GB to store   2971824320 kmers.
Used 11.538 GB out of 13.000 GB to store   3006361512 kmers.

Writing results to './Avthrum_canu2.10.meryl.WORKING', using 4 threads.
writeToFile()-- After writing 1 out of 1 'dataBlockLenMax' objects (8 bytes each): Cannot allocate memory
slurmstepd: Exceeded step memory limit at some point.
```

After fixing the problem, the same job finishes:
```
Used 8.645 GB out of 10.000 GB to store   2221823761 kmers.
Used 8.770 GB out of 10.000 GB to store   2257513926 kmers.

Writing results to './Avthrum_canu2.10.meryl.WORKING', using 1 threads.
finishIteration()--

Finished counting.
Bye.
slurmstepd: Exceeded step memory limit at some point.
```

I also tried playing with memory with the options `gridOptionsmeryl` and `merylMemory`, and it didn't solve the problem for me (unsurprisingly). The issue seems to always happen with more than one thread.

**Comment by LesterWYoung** [comment] 2020-01-22 15:26
@skoren Thanks! Updating canu helped overcome the issue I was having, however, I have another issue now with read correction failing (running into a time limit with slurm)! #1605


> @LesterWYoung the source of your error is not the same, the grid handler is killing your meryl job for exceeding memory requested. I think this may be because you're a bit out of date and memory requests have been updated since then. Add `gridOptionsmeryl="--mem-per-cpu=12g"` and I expect your jobs will run. You should also update to the 1.9 release.

**Comment by cmaggior** [comment] 2020-01-22 21:22
@skoren @elbourret Setting merylThreads=1 fixed the issue! Thank you!

**Comment by brianwalenz** [comment] 2020-01-24 16:12
After some digging around in the _actual POSIX spec_ (!!) I think I have a fix.  Change line 81 in src/utility/files.C from:
```
    if (errno)
      fprintf(stderr, "writeToFile()-- After writing %lu out of %lu '%s' objects (%lu bytes each): %s\n",
              nWritten, nObjects, description, objectSize, strerror(errno)), exit(1);
```
to:
```
    if (written != toWrite)
      fprintf(stderr, "writeToFile()-- After writing %lu out of %lu '%s' objects (%lu bytes each): %s\n",
              nWritten, nObjects, description, objectSize, strerror(errno)), exit(1);
```
Note that just the first line changed; I left the error message in for context.

I'd appreciate if you can (a) reproduce the crash using the previous version and (b) get a few successful runs with the fixed version.  We've been unable to reproduce the failures here.

For the nerds, page 947 in http://www.open-std.org/jtc1/sc22/open/n4217.pdf seems to indicate that errno is not guaranteed to be zero on success.

**Comment by cmaggior** [comment] 2020-01-24 18:50
I'm running canu on a server and don't have access to the src files unfortunately. I will keep you posted regarding future canu runs and am happy to provide any files I do have.

**Comment by elbourret** [comment] 2020-01-26 12:52
> Change line 81 in src/utility/files.C from:

Just a detail, but the code to replace starts on [line 88](https://github.com/marbl/canu/blob/833bbfade76e2f163e6f78a9115f10a3d79c6cc2/src/utility/files.C#L88), not 81.

This new code [seems to work for me](https://github.com/marbl/canu/issues/1600#issuecomment-578499011). Thank you @brianwalenz !

**Comment by brianwalenz** [comment] 2020-02-06 19:09
Great!  Thanks for testing.

**Closed by brianwalenz** 2020-02-06 19:09 UTC
