### ISSUE TITLE
Resuming two jobs doing the same thing, one fails to resume

### ISSUE THREAD

**Issue by MattStata** [marbl/canu#617] opened 2017-09-07 15:47 UTC
Hello,

I am running Canu to assemble two different genomes, in separate jobs on a server.  I had both jobs run for 48 hours and run out of walltime, and tried resuming both.  One job has resumed right where it left off with no problems, while the other is giving me an error related to "failed to create the overlap store" (full in the attached text files).

The only thing I can think of is that this is because the job that is failing to resume got a little farther than the job that resumes alright -- the job that resumes is still generating the files in 1-overlapper/results while the job that fails to resume completed this step.

Can you please advise what I need to do to get the other job to resume?

Thanks!

I'm going to provide both the full stderr generated by the first job that ran for 48hrs and the failed attempt to resume it from there.

**[FirstRunSTDERR.txt]**
(https://github.com/marbl/canu/files/1285281/FirstRunSTDERR.txt)

**[AttemptToResumeSTDERR.txt]**(https://github.com/marbl/canu/files/1285282/AttemptToResumeSTDERR.txt)

**Comment by skoren** [comment] 2017-09-07 17:15
It shouldn't matter what step the pipeline is at for resuming. Is there any error in the config file (```correction/AROS.ovlStore.err```). 

I also noticed you have a grid but are running Canu in a single process on a large genome which will take a while. I would suggest instead letting Canu submit itself to the grid which would speed up your run (don't set useGrid=false).

**Comment by MattStata** [comment] 2017-09-07 20:10
There is an error in that file, as follows:

/sgfs1/project3/r/rsage/programs/canu_v1.6/Linux-amd64/bin/ovStoreBuild: /scinet/gpc/Applications/anaconda3/4.4.0/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /sgfs1/project3/r/rsage/programs/canu_v1.6/Linux-amd64/bin/ovStoreBuild)

I actually had just switched my default python module to Anaconda 4.4.0 on the server, I think I did this since submitting the first set of jobs, so that might be the issue.  I've changed this back and submitted again, so we'll see, when the schedule starts them.

Regarding the grid, Canu had trouble submitting jobs on my cluster, and kept crashing with a message about failing to submit jobs, so I just disabled the grid as a simple solution; the amount of time it will take is not a huge factor, as long as resuming isn't going to be a headache -- unless it is going to take weeks... How long would you estimate it will take for this process to run with thread/RAM limits of 32/55gb?

**Comment by skoren** [comment] 2017-09-07 20:17
You can see some runtimes on the FAQ: https://canu.readthedocs.io/en/latest/faq.html#what-resources-does-canu-require-for-a-bacterial-genome-assembly-a-mammalian-assembly. A human genome takes about 25k cpu hours which on 32-cores would be about 4 weeks. Your genome is 1/3 the size so guess 10k cpu hours or 1-2 weeks would be my guess.

If you have info about how the commands were failing it's possible it could be fixed by providing required grid options to Canu. Canu does require that your compute nodes are allowed to submit jobs, if they are not it will not work. So I would check that requirement first and if your compute nodes can submit jobs it might be worth switching to the grid submission instead of the single-machine job.

**Comment by MattStata** [comment] 2017-09-07 21:04
I have checked with the support staff at our cluster and they have told me that no, compute nodes cannot directly submit jobs, however they mentioned that there is a workaround in the form of being able to log into the devel nodes from the compute nodes and submit jobs from there...  So basically before any commands to submit jobs, the program would have to call something like "ssh gpc01".  Is there any way to tell Canu to do this or should I just keep going with a single node per assembly?

**Comment by skoren** [comment] 2017-09-08 18:25
There isn't an easy way to call something before submitting a job, you'd have to modify the code to do that so the easiest on your grid is to use a single node.

**Comment by brianwalenz** [comment] 2017-09-09 08:45
It can be done, but there is a big complication that makes it hard.  The basic idea is to have a wrapper (qsub-wrapper.sh) around your submit command, then tell Canu to use this as the submit command with option gridEngineSubmitCommand=/path/to/bin/qsub-wrapper.sh

The complication is that the the qsub command that runs on the head node must be run from the same directory that the qsub-wrapper.sh command runs from.  An ugly way to do this is to have another wrapper that takes a directory as the first argument (and pass $PWD as the first argument in the wrapper given to canu:

qsub-wrapper.sh:
```
#!/bin/sh
ssh headnode qsub-wrapper-2.sh $PWD "$@"
```
qsub-wrapper-2.sh:
```
#!/bin/sh
cd $1
shift
qsub "$@"
```
I tried doing this years and years ago and couldn't make it work.  Happy to give some help with Canu questions, but you're on your own for making this idea work.

**Comment by MattStata** [comment] 2017-09-10 22:30
Hi Brian and Sergey,

So I actually had a similar idea, and I have managed to make it work.  My wrapper is very simple but seems to work; it contains the following, which submits jobs via the GPC01 node and does so from the current location properly:

**#!/bin/sh
ssh gpc01 cd $PWD\; qsub "$@"**

I've tested and this works -- the job runs in the correct directory, and the submission command sends the job ID back just the same as it would if I had used qsub directly, so now I've tried running Canu with grid support, but now I am running into some discrepancies with the way our grid works and the way Canu expects it to work...  When I try running the command, I get the following relevant error messages:

**-- Starting command on Sun Sep 10 18:05:00 2017 with 198152.128 GB free disk space

    cd /sgfs1/scratch3/r/rsage/stata/Atriplex/GENOMES/A_rosea/cdts-wh.genomics.cn/F16FTSEUHT1159_ATRodhD/data/_ASSEMBLY_/testrungrid
    remote_qsub \
      -l mem=4g \
      -l nodes=1:ppn=1   \
      -N 'canu_AROS' \
      -o canu-scripts/canu.01.out canu-scripts/canu.01.sh
QSUB WARNING: The -l mem=... request is deprecated on SciNet systems; feature flags such m32g, m48g, m64g, m128g and m256g are preferred (command line)
QSUB ERROR: Must specify walltime with -l walltime=...
QSUB ERROR: Batch queue nodes must be requested as 8-core nodes (command line)
QSUB: 1 warning was found.
QSUB: 2 errors were found.
QSUB: Job not submitted because of these errors.**

So it looks like I need to pass some grid configuration options along for thread specification and something to tell it how to indicate the walltime, but I'm not clear on exactly how I would do this...  Any recommendations?

The other thing that I can see being a problem for our grid is the fact that certain types of nodes need to have a special queue requested, with flags such as -q sandy or -q largemem etc.   I don't think Canu would be able to figure this out (correct me if I am wrong).  These are the types of nodes that Canu finds:

**-- Found   2 hosts with  16 cores and  126 GB memory under PBS/Torque control.
-- Found 202 hosts with  16 cores and   31 GB memory under PBS/Torque control.
-- Found  24 hosts with  16 cores and   17 GB memory under PBS/Torque control.
-- Found   2 hosts with  16 cores and   63 GB memory under PBS/Torque control.
-- Found   1 host  with  24 cores and   23 GB memory under PBS/Torque control.
-- Found  48 hosts with  24 cores and   31 GB memory under PBS/Torque control.
-- Found  72 hosts with  32 cores and   63 GB memory under PBS/Torque control.
-- Found   2 hosts with  32 cores and  126 GB memory under PBS/Torque control.
-- Found 3628 hosts with  16 cores and   15 GB memory under PBS/Torque control.
-- Found   2 hosts with  32 cores and  252 GB memory under PBS/Torque control.**

The 3,628 nodes actually have 8 cores, I guess 16 threads, and need to have ppn=8 specified.  These plus the 202 nodes with 8 cores (16 detected by Canu) and 32gb comprise the main cluster that don't require any special -q arguments to run.  The 32gb nodes are requested by using something like:

**qsub -l nodes=1:m32g:ppn=8,walltime=1:00:00**

instead of just:

**qsub -l nodes=1:ppn=8,walltime=1:00:00**

Is it possible to tell Canu to only use those nodes?  I guess if I set an appropriate thread/memory limit that would do the trick?  It might be better to be able to request some of the heftier nodes though (especially the sandybridge nodes with twice as many cores and 64gb RAM), but I think having to specify different queues would be too problematic.

My two jobs without grid support are still running, still doing corrections, and have been resubmitted and resumed properly a few times (with some early hiccups where I had to delete a few output files before it would resume properly).  I would like to try to get it running with grid support if possible though.

Thanks so much for all your assistance.

**Comment by brianwalenz** [comment] 2017-09-11 13:26
Certainly possible, somewhat easy, but might be fiddly to get working.

The easiest might be to extend your wrapper to rewrite the qsub options as needed.  Scan the parameters for the -l option, pull it apart, and insert memory and ppn values to be larger than what canu requests.

You can also try using the various gridOptions options and force the algorithms to fit on specific nodes.  For example, for mhap:
```
gridOptionsMHAP="-l nodes=1:m16g:ppn=8,walltime=1:00:00"
mhapThreads=8
mhapMemory=16
```
(`canu -defaults` will print all these various options, which you can then grep out)

There's a global catch all 'gridOptions' that is passed to every job.  Setting maxThreads=8 maxMemory=16 should limit jobs to 8 threads 16gb memory.  I don't recommend this; 16gb is pretty tight for larger assemblies.

Qsub might complain about getting two different sets of -l options, one from Canu and one from gridOptions.  You can try setting gridEngineThreadsOption=-N THREADS and gridEngineMemoryOption=-N MEMORY.  These two options need to have 'THREADS' and 'MEMORY' in the string -- Canu will replace them with the appropriate values, but all the -N option does is change the name of the job.

OK, maybe not so simple after all...

**Comment by MattStata** [comment] 2017-09-12 19:08
Hi again,

I started trying to implement what you suggested, and then did a little big of digging into how our scheduler works, and was surprised to learn that our consortium has actually rolled out two new clusters (which I didn't think were available yet) and that I have access to them both already.  These clusters use Slurm, and Canu seems to be able to submit jobs to the grid on these without any wrappers or other workarounds needed.  So, that's all great.

However, I am now having a new problem...  And I don't know if I should start a new issue for this since we've now departed rather markedly from my original post, but for now I'll just give the details here.

I've run the command from the head node as follows:

canu -p APRO -d testrungrid gridOptions='-A def-sagetamm' genomesize=1g -pacbio-raw *.fasta

The grid option was necessary as I have two resource allocations and it originally through an error without providing this.

What happens is, the program spawns two jobs, one of which starts right away with 32 CPUs and the other of which waits for it two finish, I presume to check the progress and either restart the same job or move on to the next thing.  The first job runs out of time, as can be seen in the last few lines of the file meryl.1028490_1.out:

    1608.52 Mmers --  0.71 Mmers/second
    1610.61 Mmers --  0.71 Mmers/second
    1612.71 Mmers --  0.70 Mmers/second
    1614.81 Mmers --  0.70 Mmers/second
    1616.90 Mmers --  0.70 Mmers/second
    1619.00 Mmers --  0.70 Mmers/second
slurmstepd: error: *** JOB 1028490 ON cdr100 CANCELLED AT 2017-09-11T18:19:02 DUE TO TIME LIMIT ***

It tries to spawn another job it seems, presumably to resume this, but all of the job output files in this directory start from the same thing (as if they're not resuming so much as starting over from the top) and they all time out between 1600 and 2050 Mmers, and then Canu just stops submitting any more jobs, and the canu.out file reads as follows at the end (entire file attached):

-- BEGIN CORRECTION
--
--
-- Meryl failed, tried 2 times, giving up.
--

ABORT:
ABORT: Canu 1.6
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:

I tried restarting with the same command and it started over, creating all the output files in the correction/0-mercounts folder over again, and again timed out before finishing, and again stopped  spawning new jobs with the same output in canu.out.

Can you offer any suggestions on what might be going wrong here?  It seems something may be going haywire when it tries to pick up where it left off?

Thanks in advance for your help.

[canu.out.txt](https://github.com/marbl/canu/files/1297091/canu.out.txt)

**Comment by skoren** [comment] 2017-09-12 19:19
Each job in the parallel array in Canu is essentially an atomic unit, if it doesn't complete it has to be re-run from scratch. The resume tries to re-run any failed jobs in the array, in this case there is only one job and so it will fail again and Canu gives up. You can add a time request to your options with ```gridOptions=--time=72:00:00``` or similar based on what your cluster allows.

**Comment by MattStata** [comment] 2017-09-12 19:23
Ah, okay, I didn't realize they were so atomic, given that it only requests 1 hour for the first tasks.  I guess it is underestimating the time it will need a little...  Going from 1hr to 72hrs seems like a big leap though and would cause the jobs Canu requests to take quite a bit longer to start I would imagine...  And wouldn't this mean that all jobs submitted would request 72 hours?

**Comment by skoren** [comment] 2017-09-12 19:26
Canu doesn't request any time, that's currently up to the user, it just gets whatever is default on your queue. All jobs would request 72 hours, yes. That is how we typically run on our Slurm cluster, it might delay the start somewhat but it's usually not significant enough to bother customizing the times. There are grid options for every step (```canu -options |grep grid```) but for a first run, I'd set the time for all jobs to be large and then you could potentially look at actual time taken for the jobs and adjust accordingly for other runs.

**Comment by MattStata** [comment] 2017-09-12 19:27
Ah okay, I see.  I will give it a shot, thanks!

**Comment by MattStata** [comment] 2017-09-26 14:20
Hello again,

I've made some progress.  Asking for 72 hours made my jobs take ages to start, so I reduced it to 24, which still took a long time, and then 12, which starts very quickly.  I'm told be the folks at the HPC center that this is because jobs get binned based on requested time, with very low preference for longer jobs.

Then I started running into memory issues, with Canu reporting that it had exceeded the allotted memory.  The folks at the server suggested that I try requesting whole nodes and set the threads and RAM limits accordingly, both to address this issue and to help things start faster (I guess the server is set up so that the per-core requests can use about half of the nodes, and that half is heavily over-subscribed right now).  So, I added the following:

--nodes=1
minMemory=128000M 
maxMemory=128000M 
minThreads=32 
maxThreads=32 
merylMemory=128000M 
merylThreads=32

And things progressed quite well.  The correction step seems to be completely finished and the trimming step has begun.

However, now both of my assemblies have gotten stuck, with the following message:

> -- BEGIN TRIMMING
> --
> --
> -- Overlap store sorting jobs failed, tried 2 times, giving up.
> --   job trimming/APRO.ovlStore.BUILDING/0001 FAILED.
> --
> 
> ABORT:
> ABORT: Canu 1.6
> ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
> ABORT: Try restarting.  If that doesn't work, ask for help.
> ABORT:

I've tried restarting, and they fail immediately with the same error message.  Do you have any suggestions for what the issue might be now?

Thanks!

**Comment by MattStata** [comment] 2017-10-05 15:24
Hi again,

I managed to resolve my previous issue after searching through these pages and finding that others had encountered similar problems (sorry for posting before looking for a solution first!).

One of my two assembly projects has finished now, so that's great, however the other one is hitting a snag repeatedly.  During the unitigging/4-unitigger stage I am receiving the following error:

../AROS.ctgStore/seqDB.v001.sizes.txt: No such file or directory

I see that others on here have encountered this issue, but the solution seems to have always been that it is simply fixed in Canu 1.6 -- however I am running 1.6, as a clean installation and have never had an earlier version installed before, and yet I'm still encountering this error.  Canu tries to do this twice, both times hits the same error, both times does a massive core dump, and then the whole pipeline quits.  I've tried deleting this folder and a couple of the previous stages' outputs and restarting and it still hits the same issue at this step.  I'm at a bit of a loss to understand why one of my assembly projects completed fine while the other keeps hitting this problem, running on the same server with identical commands/arguments and with identically produced data from related species with a similar genome size/complexity.  Any suggestions would be most appreciated.

**Comment by skoren** [comment] 2017-10-19 14:10
Sorry for the late reply, I didn't notice your response till now. What is the output in ```4-unitigger/unitigger.err```? Have you tried removing both the 4-unitigger and the asm.[ctg|utg]Store folders on a restart and seen if that fixes is?

**Comment by MattStata** [comment] 2017-10-19 14:16
Hi Sergey,

Actually, I downloaded the latest source code at the time (**Canu snapshot v1.6 +90 changes (r8502 cce9f5d6ca10f94e67560b48addb7bc91010a457)**), recompiled it, and started over from scratch, and it ran start to finish without any errors or restarts along the way.  I also reran the one that had already finished, since it did require some restarts and deleting of output along the way and I wanted to see if it did any better if it ran without errors.  Interestingly, the second run resulted in a larger number of contigs; the first run with restarts generated an assembly with 744 megabases in 1012 contigs, while the second run resulted in 734 megabases in 1580 contigs.  Do you know why this might be?  I am going to try running sspace-longread to see if it can put things together a bit more.

Cheers,
Matt

**Comment by skoren** [comment] 2017-10-19 14:27
We relaxed the filter for what is a contig since 1.6 to avoid missing short plasmids and repeat sequences in the assembly. The number of contigs might increase but the continuity shouldn't change so I would compare stats on the continuity not just counts. There were also some large code changes around the time of your checkout, you can see that this negatively affected some assemblies in the regression tests:
https://github.com/marbl/canu-regression/blob/master/results

For example for arabidopsis, the NG50 was 6.1mb:
https://github.com/marbl/canu-regression/blob/master/results/2017-08-24-0051/arabidopsis_thaliana.pacbio.p4c2.report

dropped to 5.3mb:
https://github.com/marbl/canu-regression/blob/master/results/2017-09-20-1513/arabidopsis_thaliana.pacbio.p4c2.report

and recovered back to 5.8mb:
https://github.com/marbl/canu-regression/blob/master/results/2017-10-11-1435/arabidopsis_thaliana.pacbio.p4c2.report

The number of contigs also increased to 267 from 244 due to the filter change I described.

**Comment by MattStata** [comment] 2017-10-19 14:47
So, was the version I compiled the one with the poor NG50 results?  Would it be worth it to compile the latest and run it again?

What is the most important thing to compare between the first and second runs here, to determine which is better and if Canu behaved well both times?  I also wanted to ask, I seem to be missing some info in my html files, for instance in the unitigging.html the last few fields (Initial Tig Sizes, Final Tig Sizes, Consensus, Final Outputs) have no info.  Did something go wrong in generating these?  I'm attaching my .report files here for both runs of this genome (APRO) as well as the one successful run for the other genome (AROS).


[APRO.secondrun.report.txt](https://github.com/marbl/canu/files/1398817/APRO.secondrun.report.txt)
[APRO.firstrun.report.txt](https://github.com/marbl/canu/files/1398818/APRO.firstrun.report.txt)
[AROS.report.txt](https://github.com/marbl/canu/files/1398819/AROS.report.txt)

**Comment by skoren** [comment] 2017-10-19 14:54
It is likely you did check out during the bug. The second run definitely seems like a worse assembly from the report. The NG50 for the AROS and APRO second run are quite similar so it may be worth checking out latest code and re-running AROS as it may likely improve with the bug fixes.

**Comment by skoren** [comment] 2017-10-20 19:04
I'm going to close the issue as it's drifted a bit from the original question. If you have issues with runs with the latest tip, open a new issue.

**Closed by skoren** 2017-10-20 19:04 UTC
