### ISSUE TITLE
CANU v1.6 Error in ecoli quick start tutorial -  ERROR: File supplied on command line; use -s, -pacbio-raw, -pacbio-corrected, -nanopore-raw, or -nanopore-corrected

### ISSUE THREAD

**Issue by KnudNorNielsen** [marbl/canu#616] opened 2017-09-07 08:09 UTC
I have tried to run the tutorial on ecoli supplied on the CANU readthedocs http://canu.readthedocs.io/en/latest/quick-start.html. I downloaded the supplied pacbio file and run the script, and then: 
**ERROR: File supplied on command line; use -s, -pacbio-raw, -pacbio-corrected, -nanopore-raw, or -nanopore-corrected.** 
Have anyone experienced this before or have a explanation?

The code was not pasted in, I tried both US and non-US keyboard setup for typing.
CANU v1.6 +13
Java runtime environment build 1.8.0_141b16.

```
[sjz457@compute12 ~]$ curl -L -o pacbio.fastq 

http://gembox.cbcb.umd.edu/mhap/raw/ecoli_p6_25x.filtered.fastq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current  Dload  Upload   Total   Spent    Left  Speed
100  222M  100  222M    0     0  21.2M      0  0:00:10  0:00:10 --:--:-- 24.2M

[sjz457@compute12 ~]$ canu -p ecoli -d ecoli genomeSize=4.8m -pacbio-raw pacbio.fastq           

usage:   canu [-version] [-citation] \
              [-correct | -trim | -assemble | -trim-assemble] \
              [-s <assembly-specifications-file>] \
               -p <assembly-prefix> \
               -d <assembly-directory> \
               genomeSize=<number>[g|m|k] \
              [other-options] \
              [-pacbio-raw |
               -pacbio-corrected |
               -nanopore-raw |
               -nanopore-corrected] file1 file2 ...

example: canu -d run1 -p godzilla genomeSize=1g -nanopore-raw reads/*.fasta.gz


  To restrict canu to only a specific stage, use:
    -correct       - generate corrected reads
    -trim          - generate trimmed reads
    -assemble      - generate an assembly
    -trim-assemble - generate trimmed reads and then assemble them

  The assembly is computed in the -d <assembly-directory>, with output files named
  using the -p <assembly-prefix>.  This directory is created if needed.  It is not
  possible to run multiple assemblies in the same directory.

  The genome size should be your best guess of the haploid genome size of what is being
  assembled.  It is used primarily to estimate coverage in reads, NOT as the desired
  assembly size.  Fractional values are allowed: '4.7m' equals '4700k' equals '4700000'

  Some common options:
    useGrid=string
      - Run under grid control (true), locally (false), or set up for grid control
        but don't submit any jobs (remote)
    rawErrorRate=fraction-error
      - The allowed difference in an overlap between two raw uncorrected reads.  For lower
        quality reads, use a higher number.  The defaults are 0.300 for PacBio reads and
        0.500 for Nanopore reads.
    correctedErrorRate=fraction-error
      - The allowed difference in an overlap between two corrected reads.  Assemblies of
        low coverage or data with biological differences will benefit from a slight increase
        in this.  Defaults are 0.045 for PacBio reads and 0.144 for Nanopore reads.
    gridOptions=string
      - Pass string to the command used to submit jobs to the grid.  Can be used to set
        maximum run time limits.  Should NOT be used to set memory limits; Canu will do
        that for you.
    minReadLength=number
      - Ignore reads shorter than 'number' bases long.  Default: 1000.
    minOverlapLength=number
      - Ignore read-to-read overlaps shorter than 'number' bases long.  Default: 500.
  A full list of options can be printed with '-options'.  All options can be supplied in
  an optional sepc file with the -s option.

  Reads can be either FASTA or FASTQ format, uncompressed, or compressed with gz, bz2 or xz.
  Reads are specified by the technology they were generated with:
    -pacbio-raw         <files>
    -pacbio-corrected   <files>
    -nanopore-raw       <files>
    -nanopore-corrected <files>

Complete documentation at http://canu.readthedocs.org/en/latest/

ERROR:  File supplied on command line; use -s, -pacbio-raw, -pacbio-corrected, -nanopore-raw, or -nanopore-corrected.
```

**Comment by brianwalenz** [comment] 2017-09-07 10:20
I think this is related to https://rt.cpan.org/Public/Bug/Display.html?id=13851

The problem is that perl is trying to read all the directories up to pacbio.fastq (to find the full path to the file) but it can't read one directory, canusing Canu to fail (long story omitted).

A solution is to add the middle line below to src/pipelines/canu/Defaults.pm at line 512
```
    $file = "$dir/$file"      if (defined($dir));     #  If $dir defined, assume file is in there.                                                            
    return($file)             if ($file =~ m!/!);     #  If already a full path, use that.                                                                    
    return(abs_path($file))   if (-e $file);          #  If found, return the full path.                                                                      
```
then using a full path to the reads, $PWD/pacbio.fastq worked for me.

I'll get this committed to github later today.

**Comment by brianwalenz** [comment] 2017-09-08 07:11
I've updated the github code.  You can just 'git update' or [download the latest zip](https://github.com/marbl/canu/archive/master.zip).  Don't forget to recompile!

**Comment by skoren** [comment] 2017-09-11 16:47
This should be fixed in the latest in the repo. Please open a new issue if you encounter errors running the updated code.

**Closed by skoren** 2017-09-11 16:47 UTC
