### ISSUE TITLE
Canu failed -- Bogart failed

### ISSUE THREAD

**Issue by cardiandra** [marbl/canu#1599] opened 2020-01-16 15:47 UTC
Hi all,

I am using Canu to assemble reads from PacBio. The correction and trimming steps went through and complete, but the assembly step failed due to the Bogart failed issue. I run the program on our HPC cluster and the version I used is v1.9. 

Here's the command that I used for running the program: 

`canu -p Draba_Canu -d run1 genomeSize=300m correctedErrorRate=0.105 corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" -pacbio-raw data.fasta
`

And here's the error part from the output file:
```
-- Starting command on Thu Jan 16 05:13:15 2020 with 7617.656 GB free disk space

    cd unitigging/3-overlapErrorAdjustment
    /gpfs/apps/haswell/software/gcc-6.2.0/canu/1.9/Linux-amd64/bin/loadErates \
      -S ../../Draba_Canu.seqStore \
      -O ../Draba_Canu.ovlStore \
      -L ./oea.files \
    > ./oea.apply.err 2>&1

-- Finished on Thu Jan 16 05:13:19 2020 (4 seconds) with 7616.304 GB free disk space
----------------------------------------
-- No report available.
-- Report changed.
-- Finished stage 'updateOverlapStore', reset canuIteration.
-- Finished stage 'unitig', reset canuIteration.
-- No change in report.
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'bat' concurrent execution on Thu Jan 16 05:13:19 2020 with 7616.308 GB free disk space (1 processes; 1 concurrently)

    cd unitigging/4-unitigger
    ./unitigger.sh 1 > ./unitigger.000001.out 2>&1

-- Finished on Thu Jan 16 05:16:53 2020 (214 seconds) with 7616.171 GB free disk space
----------------------------------------
--
-- Bogart failed, retry
--
-- No change in report.
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'bat' concurrent execution on Thu Jan 16 05:16:53 2020 with 7616.171 GB free disk space (1 processes; 1 concurrently)

    cd unitigging/4-unitigger
    ./unitigger.sh 1 > ./unitigger.000001.out 2>&1

-- Finished on Thu Jan 16 05:20:23 2020 (210 seconds) with 7616.171 GB free disk space
----------------------------------------
--
-- Bogart failed, tried 2 times, giving up.
--

ABORT:
ABORT: Canu snapshot ()
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT: Disk space available:  7616.171 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/4-unitigger/unitigger.err):
ABORT:
ABORT:   optimizePositions()--     Reset zero.
ABORT:   optimizePositions()--     Checking convergence.
ABORT:   optimizePositions()--     converged: 1633817 reads
ABORT:   optimizePositions()--     changed:   761857 reads
ABORT:   optimizePositions()--   Recomputing positions, iteration 4, with 8 threads.
ABORT:   optimizePositions()--     Reset zero.
ABORT:   optimizePositions()--     Checking convergence.
ABORT:   optimizePositions()--     converged: 1634167 reads
ABORT:   optimizePositions()--     changed:   761507 reads
ABORT:   optimizePositions()--   Recomputing positions, iteration 5, with 8 threads.
ABORT:   optimizePositions()--     Reset zero.
ABORT:   optimizePositions()--     Checking convergence.
ABORT:   optimizePositions()--     converged: 1634319 reads
ABORT:   optimizePositions()--     changed:   761355 reads
ABORT:   optimizePositions()--   Expanding short reads with 8 threads.
ABORT:   optimizePositions()--   Updating positions.
ABORT:   optimizePositions()--   Finished.
ABORT:   splitDiscontinuous()-- Tested 11013 tigs, split 12 tigs into 24 new tigs.
ABORT:   detectSpur() done.
ABORT:   tested         1626
ABORT:   nEdges      5'  135   3'  137
ABORT:   nPotential       37        23
ABORT:   nVerified        11        11
ABORT:   
ABORT:   ==> PLACE CONTAINED READS.
ABORT:   
ABORT:   computeErrorProfiles()-- Computing error profiles for 49768 tigs, with 8 threads.
ABORT:   computeErrorProfiles()-- Finished.
ABORT:   
ABORT:   placeContains()-- placing 1519893 contained and 806899 unplaced reads, with 8 threads.
ABORT:   placeContains()-- Placed 1009840 contained reads and 8955 unplaced reads.
ABORT:   placeContains()-- Failed to place 510053 contained reads (too high error suspected) and 797944 unplaced reads (lack of overlaps suspected).
ABORT:   optimizePositions()-- Optimizing read positions for 2395674 reads in 49768 tigs, with 8 threads.
ABORT:   optimizePositions()--   Allocating scratch space for 2395674 reads (149729 KB).
ABORT:   optimizePositions()--   Initializing positions with 8 threads.
ABORT:   bogart: bogart/AS_BAT_OptimizePositions.C:261: void Unitig::optimize_initPlace(uint32, optPos*, optPos*, bool, std::set<unsigned int>&, bool): Assertion `cnt > 0' failed.
ABORT:   
ABORT:   Failed with 'Aborted'; backtrace (libbacktrace):
ABORT:   utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP7siginfoPv()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   bogart/AS_BAT_OptimizePositions.C::261 in _ZN6Unitig18optimize_initPlaceEjP6optPosS1_bRSt3setIjSt4lessIjESaIjEEb()
ABORT:   bogart/AS_BAT_OptimizePositions.C::520 in _ZN9TigVector17optimizePositionsEPKcS1_._omp_fn.0()
ABORT:   ../../../gcc-6.2.0/libgomp/team.c::119 in gomp_thread_start()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:
```

Here is the unitigger.err file content:
```

==> PARAMETERS.

Resources:
  Memory                64 GB
  Compute Threads       8 (command line)

Lengths:
  Minimum read          0 bases
  Minimum overlap       500 bases

Overlap Error Rates:
  Graph                 0.105 (10.500%)
  Max                   0.105 (10.500%)

Deviations:
  Graph                 3.000
  Bubble                3.000
  Repeat                1.000

Edge Confusion:
  Absolute              500
  Percent               50.0000

Unitig Construction:
  Minimum intersection  500 bases
  Maxiumum placements   2 positions

Debugging Enabled:
  (none)

==> LOADING AND FILTERING OVERLAPS.

ReadInfo()-- Using 2395673 reads, no minimum read length used.

OverlapCache()-- limited to 65536MB memory (user supplied).

OverlapCache()--      18MB for read data.
OverlapCache()--      91MB for best edges.
OverlapCache()--     237MB for tigs.
OverlapCache()--      63MB for tigs - read layouts.
OverlapCache()--      91MB for tigs - error profiles.
OverlapCache()--   16384MB for tigs - error profile overlaps.
OverlapCache()--       0MB for other processes.
OverlapCache()-- ---------
OverlapCache()--   16932MB for data structures (sum of above).
OverlapCache()-- ---------
OverlapCache()--      45MB for overlap store structure.
OverlapCache()--   48557MB for overlap data.
OverlapCache()-- ---------
OverlapCache()--   65536MB allowed.
OverlapCache()--
OverlapCache()-- Retain at least 61 overlaps/read, based on 30.88x coverage.
OverlapCache()-- Initial guess at 1328 overlaps/read.
OverlapCache()--
OverlapCache()-- Adjusting for sparse overlaps.
OverlapCache()--
OverlapCache()--               reads loading olaps          olaps               memory
OverlapCache()--   olaps/read       all      some          loaded                 free
OverlapCache()--   ----------   -------   -------     ----------- -------     --------
OverlapCache()--         1328   2251659    144014       398666233  56.78%      42474 MB
OverlapCache()--        20656   2395491       182       701753094  99.94%      37850 MB
OverlapCache()--      13650011   2395673         0       702180234 100.00%      37843 MB
OverlapCache()--
OverlapCache()-- Loading overlaps.
OverlapCache()--
OverlapCache()--          read from store           saved in cache
OverlapCache()--   ------------ ---------   ------------ ---------
OverlapCache()--       22383965 (003.19%)       22285044 (003.17%)
OverlapCache()--       45097056 (006.42%)       44832127 (006.38%)
OverlapCache()--       69172029 (009.85%)       68743138 (009.79%)
OverlapCache()--       91287937 (013.00%)       90743409 (012.92%)
OverlapCache()--      113650596 (016.19%)      112980957 (016.09%)
OverlapCache()--      136182735 (019.39%)      135366338 (019.28%)
OverlapCache()--      159483484 (022.71%)      158474979 (022.57%)
OverlapCache()--      183359118 (026.11%)      182186646 (025.95%)
OverlapCache()--      212689595 (030.29%)      211322081 (030.10%)
OverlapCache()--      242954670 (034.60%)      241428611 (034.38%)
OverlapCache()--      273569441 (038.96%)      271889454 (038.72%)
OverlapCache()--      304590094 (043.38%)      302753219 (043.12%)
OverlapCache()--      334616720 (047.65%)      332618718 (047.37%)
OverlapCache()--      366578127 (052.21%)      364406298 (051.90%)
OverlapCache()--      401431725 (057.17%)      399056528 (056.83%)
OverlapCache()--      432971930 (061.66%)      430406564 (061.30%)
OverlapCache()--      464752926 (066.19%)      461979528 (065.79%)
OverlapCache()--      497463050 (070.85%)      494485278 (070.42%)
OverlapCache()--      530533376 (075.56%)      527371361 (075.10%)
OverlapCache()--      564954387 (080.46%)      561574611 (079.98%)
OverlapCache()--      598716852 (085.27%)      595127002 (084.75%)
OverlapCache()--      631235231 (089.90%)      627465376 (089.36%)
OverlapCache()--      666913114 (094.98%)      662924768 (094.41%)
OverlapCache()--   ------------ ---------   ------------ ---------
OverlapCache()--      702180234 (100.00%)      697973559 (099.40%)
OverlapCache()--
OverlapCache()-- Ignored 3098610 duplicate overlaps.
OverlapCache()--
OverlapCache()-- Symmetrizing overlaps.
OverlapCache()--   Finding missing twins.
OverlapCache()--   Found 278081 missing twins in 697973559 overlaps, 20828 are strong.
OverlapCache()--   Dropping weak non-twin overlaps; allocated 0 MB scratch space.
OverlapCache()--   Dropped 46283 overlaps; scratch space released.
OverlapCache()--   Adding 231798 missing twin overlaps.
OverlapCache()--   Finished.

BestOverlapGraph()-- allocating best edges (73MB)

BestOverlapGraph()-- finding initial best edges.

BestOverlapGraph()-- filtering suspicious reads.
BestOverlapGraph()-- marked 759532 reads as suspicious.

BestOverlapGraph()-- filtering high error edges.

BestOverlapGraph()-- filtering reads with lopsided best edges.

BestOverlapGraph()-- filtering spur reads.
BestOverlapGraph()-- detected 35734 spur reads and 773965 singleton reads.
BestOverlapGraph()-- detected 1175 zombie reads.

BestOverlapGraph()-- removing best edges for contained reads.

==> BUILDING GREEDY TIGS.

breakSingletonTigs()-- Removed 37906 singleton tigs; reads are now unplaced.
optimizePositions()-- Optimizing read positions for 2395674 reads in 49744 tigs, with 8 threads.
optimizePositions()--   Allocating scratch space for 2395674 reads (149729 KB).
optimizePositions()--   Initializing positions with 8 threads.
optimizePositions()--   Recomputing positions, iteration 1, with 8 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 1625158 reads
optimizePositions()--     changed:   770516 reads
optimizePositions()--   Recomputing positions, iteration 2, with 8 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 1632559 reads
optimizePositions()--     changed:   763115 reads
optimizePositions()--   Recomputing positions, iteration 3, with 8 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 1633817 reads
optimizePositions()--     changed:   761857 reads
optimizePositions()--   Recomputing positions, iteration 4, with 8 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 1634167 reads
optimizePositions()--     changed:   761507 reads
optimizePositions()--   Recomputing positions, iteration 5, with 8 threads.
optimizePositions()--     Reset zero.
optimizePositions()--     Checking convergence.
optimizePositions()--     converged: 1634319 reads
optimizePositions()--     changed:   761355 reads
optimizePositions()--   Expanding short reads with 8 threads.
optimizePositions()--   Updating positions.
optimizePositions()--   Finished.
splitDiscontinuous()-- Tested 11013 tigs, split 12 tigs into 24 new tigs.
detectSpur() done.
tested         1626
nEdges      5'  135   3'  137
nPotential       37        23
nVerified        11        11

==> PLACE CONTAINED READS.

computeErrorProfiles()-- Computing error profiles for 49768 tigs, with 8 threads.
computeErrorProfiles()-- Finished.

placeContains()-- placing 1519893 contained and 806899 unplaced reads, with 8 threads.
placeContains()-- Placed 1009840 contained reads and 8955 unplaced reads.
placeContains()-- Failed to place 510053 contained reads (too high error suspected) and 797944 unplaced reads (lack of overlaps suspected).
optimizePositions()-- Optimizing read positions for 2395674 reads in 49768 tigs, with 8 threads.
optimizePositions()--   Allocating scratch space for 2395674 reads (149729 KB).
optimizePositions()--   Initializing positions with 8 threads.
bogart: bogart/AS_BAT_OptimizePositions.C:261: void Unitig::optimize_initPlace(uint32, optPos*, optPos*, bool, std::set<unsigned int>&, bool): Assertion `cnt > 0' failed.

Failed with 'Aborted'; backtrace (libbacktrace):
utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
bogart/AS_BAT_OptimizePositions.C::261 in _ZN6Unitig18optimize_initPlaceEjP6optPosS1_bRSt3setIjSt4lessIjESaIjEEb()
bogart/AS_BAT_OptimizePositions.C::520 in _ZN9TigVector17optimizePositionsEPKcS1_._omp_fn.0()
../../../gcc-6.2.0/libgomp/team.c::119 in gomp_thread_start()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
```
For some reason, the `canu --version` returns ```Canu snapshot ()``` from our cluster. 

I've read several previous issue discussion, and not sure which one would be the best solution to my case. One potential issue of my assembly is that we do not really know what would be the ploidy level and the genome size of our organism. I used its close relative's information and guess it might be somewhere around several hundred mbs. Could that cause the failure of the assembler? 

Thanks for any help. Please let me know if you need more information. 

>

**Comment by skoren** [comment] 2020-01-16 17:28
I'm not sure you're using 1.9, the previous time we saw this same error (#1576) it was because the user had an outdated version installed. Can you try downloading the 1.9 release from the releases page on GitHub and running that to see if the assembly completes? It should be able to continue your existing assembly.

**Comment by cardiandra** [comment] 2020-01-16 17:55
Hi, 

Thanks for the prompt reply. I did saw the #1576 issue, but I think we installed the version 1.9 from the release page, since that is the webpage that I sent to our HPC to request the installation. I can ask them to re-install it or double-check the version. Is there any other possible reason to cause the error other than the version issue? 

For resuming the run, I checked #917.  Do I just simply use the same command that I posted in the pbs file to re-submit it again to the cluster?  The program will recognize the point it broke and resume over there? Thanks again.

**Comment by skoren** [comment] 2020-01-16 17:58
It could be caused by a bug but I think that is unlikely since we haven't seen it in 1.9 from other users, while we did encounter it in older versions. The fix for that would be to try the post-1.9 updates to this code which aren't yet in a release.

Yes, the same command will work to re-submit and resume the run.

**Comment by cardiandra** [comment] 2020-01-16 18:30
Got it. I ask our HPC to re-install the v1.9 and see if that solves the issue. This is the webpage that I sent to them. Is this the correct version? 

https://github.com/marbl/canu/releases

Thanks.

**Comment by cardiandra** [comment] 2020-01-20 14:58
Hi again,

Our cluster people have re-installed the Canu on the HPC, and they downloaded from the latest release (v1.9). However, the same error happened again. Here's the output content:

```
-- Canu 1.9
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
-- 
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
-- 
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
-- 
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
-- 
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
-- 
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
-- 
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
-- 
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_92' (from '/apps/compilers/java-jdk/1.8.0_92/bin/java') with -d64 support.
-- Detected gnuplot version '4.2 patchlevel 6 ' (from 'gnuplot') and image format 'png'.
-- Detected 28 CPUs and 1262 gigabytes of memory.
-- No grid engine detected, grid disabled.
--
--                            (tag)Concurrency
--                     (tag)Threads          |
--            (tag)Memory         |          |
--        (tag)         |         |          |     total usage     algorithm
--        -------  ------  --------   --------  -----------------  -----------------------------
-- Local: meryl     24 GB    7 CPUs x   4 jobs    96 GB   28 CPUs  (k-mer counting)
-- Local: hap       12 GB   14 CPUs x   2 jobs    24 GB   28 CPUs  (read-to-haplotype assignment)
-- Local: cormhap   13 GB   14 CPUs x   2 jobs    26 GB   28 CPUs  (overlap detection with mhap)
-- Local: obtovl     8 GB    7 CPUs x   4 jobs    32 GB   28 CPUs  (overlap detection)
-- Local: utgovl     8 GB    7 CPUs x   4 jobs    32 GB   28 CPUs  (overlap detection)
-- Local: cor       16 GB    4 CPUs x   7 jobs   112 GB   28 CPUs  (read correction)
-- Local: ovb        4 GB    1 CPU  x  28 jobs   112 GB   28 CPUs  (overlap store bucketizer)
-- Local: ovs       16 GB    1 CPU  x  28 jobs   448 GB   28 CPUs  (overlap store sorting)
-- Local: red       16 GB    4 CPUs x   7 jobs   112 GB   28 CPUs  (read error detection)
-- Local: oea        8 GB    1 CPU  x  28 jobs   224 GB   28 CPUs  (overlap error adjustment)
-- Local: bat       64 GB    8 CPUs x   1 job     64 GB    8 CPUs  (contig construction with bogart)
-- Local: cns      --- GB    8 CPUs x --- jobs   --- GB  --- CPUs  (consensus)
-- Local: gfa       16 GB    8 CPUs x   1 job     16 GB    8 CPUs  (GFA alignment and processing)
--
-- In 'Draba_Canu.seqStore', found PacBio reads:
--   Raw:        2395673
--   Corrected:  1695532
--   Trimmed:    1636467
--
-- Generating assembly 'Draba_Canu' in '/gpfs/data/bergelson-lab/draba/RunCanu/Plant1/Draba_P1_01092020_High'
--
-- Parameters:
--
--  genomeSize        300000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.2400 ( 24.00%)
--    obtOvlErrorRate 0.1050 ( 10.50%)
--    utgOvlErrorRate 0.1050 ( 10.50%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.3000 ( 30.00%)
--    obtErrorRate    0.1050 ( 10.50%)
--    utgErrorRate    0.1050 ( 10.50%)
--    cnsErrorRate    0.1050 ( 10.50%)
--
--
-- BEGIN ASSEMBLY
--
-- No change in report.
-- No change in report.
-- No change in report.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'bat' concurrent execution on Mon Jan 20 02:11:35 2020 with 7392.265 GB free disk space (1 processes; 1 concurrently)

    cd unitigging/4-unitigger
    ./unitigger.sh 1 > ./unitigger.000001.out 2>&1

-- Finished on Mon Jan 20 02:15:06 2020 (211 seconds) with 7392.261 GB free disk space
----------------------------------------
--
-- Bogart failed, retry
--
-- No change in report.
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'bat' concurrent execution on Mon Jan 20 02:15:06 2020 with 7392.261 GB free disk space (1 processes; 1 concurrently)

    cd unitigging/4-unitigger
    ./unitigger.sh 1 > ./unitigger.000001.out 2>&1

-- Finished on Mon Jan 20 02:18:38 2020 (212 seconds) with 7392.261 GB free disk space
----------------------------------------
--
-- Bogart failed, tried 2 times, giving up.
--

ABORT:
ABORT: Canu 1.9
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT: Disk space available:  7392.261 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/4-unitigger/unitigger.err):
ABORT:
ABORT:   optimizePositions()--     Checking convergence.
ABORT:   optimizePositions()--     converged: 1633817 reads
ABORT:   optimizePositions()--     changed:   761857 reads
ABORT:   optimizePositions()--   Recomputing positions, iteration 4, with 8 threads.
ABORT:   optimizePositions()--     Reset zero.
ABORT:   optimizePositions()--     Checking convergence.
ABORT:   optimizePositions()--     converged: 1634167 reads
ABORT:   optimizePositions()--     changed:   761507 reads
ABORT:   optimizePositions()--   Recomputing positions, iteration 5, with 8 threads.
ABORT:   optimizePositions()--     Reset zero.
ABORT:   optimizePositions()--     Checking convergence.
ABORT:   optimizePositions()--     converged: 1634319 reads
ABORT:   optimizePositions()--     changed:   761355 reads
ABORT:   optimizePositions()--   Expanding short reads with 8 threads.
ABORT:   optimizePositions()--   Updating positions.
ABORT:   optimizePositions()--   Finished.
ABORT:   splitDiscontinuous()-- Tested 11013 tigs, split 12 tigs into 24 new tigs.
ABORT:   detectSpur() done.
ABORT:   tested         1626
ABORT:   nEdges      5'  135   3'  137
ABORT:   nPotential       37        23
ABORT:   nVerified        11        11
ABORT:   
ABORT:   ==> PLACE CONTAINED READS.
ABORT:   
ABORT:   computeErrorProfiles()-- Computing error profiles for 49768 tigs, with 8 threads.
ABORT:   computeErrorProfiles()-- Finished.
ABORT:   
ABORT:   placeContains()-- placing 1519893 contained and 806899 unplaced reads, with 8 threads.
ABORT:   placeContains()-- Placed 1009840 contained reads and 8955 unplaced reads.
ABORT:   placeContains()-- Failed to place 510053 contained reads (too high error suspected) and 797944 unplaced reads (lack of overlaps suspected).
ABORT:   optimizePositions()-- Optimizing read positions for 2395674 reads in 49768 tigs, with 8 threads.
ABORT:   optimizePositions()--   Allocating scratch space for 2395674 reads (149729 KB).
ABORT:   optimizePositions()--   Initializing positions with 8 threads.
ABORT:   bogart: bogart/AS_BAT_OptimizePositions.C:261: void Unitig::optimize_initPlace(uint32, optPos*, optPos*, bool, std::set<unsigned int>&, bool): Assertion `cnt > 0' failed.
ABORT:   
ABORT:   Failed with 'Aborted'; backtrace (libbacktrace):
ABORT:   utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP7siginfoPv()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   bogart/AS_BAT_OptimizePositions.C::261 in _ZN6Unitig18optimize_initPlaceEjP6optPosS1_bRSt3setIjSt4lessIjESaIjEEb()
ABORT:   bogart/AS_BAT_OptimizePositions.C::520 in _ZN9TigVector17optimizePositionsEPKcS1_._omp_fn.0()
ABORT:   ../../../gcc-6.2.0/libgomp/parallel.c::168 in GOMP_parallel()
ABORT:   bogart/AS_BAT_OptimizePositions.C::508 in _ZN9TigVector17optimizePositionsEPKcS1_()
ABORT:   bogart/bogart.C::481 in main()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:
```

The version shows Canu 1.9 this time, so I think the version should be the correct one. Any other way that I can try to solve this issue? Thanks for any help.

**Comment by skoren** [comment] 2020-01-21 16:46
You can try the suggestions in #1284 to see if you can get past the error:
 - decrease the -M option
 - increasing db/db options
 - decreasing db/dg options

If those don't work, are you able to share the data (the ovlStore and seqStores should be enough).

**Comment by cardiandra** [comment] 2020-01-22 14:20
It works!! I reduced memory from 128G to 64G, increased db from 3 to 4 and decreased dg from 3 to 2. It went through the final part of the assembly. Thanks for all your help.

**Comment by skoren** [comment] 2020-01-22 15:35
Glad that it worked, if you have a chance it would be interesting to run the assembly step using the tip version rather than 1.9 to see if this is still a bug there. You'd have to run something like ```canu -assemble -p Draba_Canu -d run2 genomeSize=300m correctedErrorRate=0.105 corOutCoverage=200 "batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50" -pacbio-corrected run1/Draba_Canu.trimmedReads.fasta.gz```. 

Feel free to post an update if you run that, I'm going to close the issue pending it failing past 1.9.

**Closed by skoren** 2020-01-22 15:35 UTC
