### ISSUE TITLE
Getting Started with canu

### ISSUE THREAD

**Issue by clarkaduab** [marbl/canu#119] opened 2016-04-25 21:05 UTC
Hi,
-warning I am not code savvy or competent at building programs. I stumbled my way through a poretools installation successfully.

I have gotten the files needed to install canu on the computer and ive input

cd canu/src in command prompt.
when I attempt to make -j (8)

I get the following message:

C:\Users\clarkad\canu\src>make -j 8
makefile:504: *** multiple target patterns.  Stop.

**Comment by skoren** [comment] 2016-04-26 13:24
It looks like you're on a windows machine, we've never tested/compiled Canu on Windows. Google reports your error is caused by windows paths being incompatible with cygwin and make 3.8.1: https://software.sandia.gov/trac/acro/ticket/2835

You can either try an older version of make or the patched version. The issue is that Canu is auto-generating dependency lists for its files which contain the windows-style path ```C:\``` and make is being confused by the ```:``` since that's a special character.

**Comment by clarkaduab** [comment] 2016-04-26 14:30
Wonderful, I will attempt to try an older version of make and if not, I'll attempt installation on mac. Thanks!

**Comment by skoren** [comment] 2016-04-26 16:11
I tried building the current version on cygwin and had to make a few code modifications but it ran on a test set. Until I commit that code you won't be able to build/run on windows so I suggest using OS X. Windows will always not be our primary supported environment.

**Comment by skoren** [comment] 2016-04-26 16:58
Commited/tested basic assembly in cygwin with latest code (4f67ce9680b5450d1f629676e236dcf4afee2bb4). Closing.

**Closed by skoren** 2016-04-26 16:58 UTC
