### ISSUE TITLE
very slow falconsense

### ISSUE THREAD

**Issue by mschatz** [marbl/canu#1202] opened 2019-01-04 04:58 UTC
Hi Adam, Sergey, et al,

Im assembling a 2GB plant genome sequenced with Nanopore using canu-1.8 from the precompiled Linux binaries. We have about 40x coverage in reads over 20kbp that Im using for the assembly. I used very standard options (-nanopore-raw), and in the correction phase it splits the data into 142 batches. All but one of these finished in a few hours, but one of the batches has been running for several days, and the WORKING.cns file size shows that it is crawling along and could go for another week or more. I tried launching this batch on a second node and it is showing the same slow performance so Im guessing there are some bad reads in this batch that just take forever. 

Do you have any suggestions on how to identify & exclude bad reads? I guess it wouldnt be the end of the world to exclude 1/142 of the coverage by skipping this batch entirely, but maybe you have another suggestion. I dumped the reads in this batch using sqStoreDumpFASTQ and see the longest read is 2,097,151 (mean=30kbp) so maybe that is confusing everything. Ive encountered this sort of problem in a few different assemblies now so it might be something systematic, like having some extremely long (~1Mbp) reads in the batch

Thanks in advance

Mike

**Comment by mattloose** [comment] 2019-01-04 09:41
As an aside - a 2 Mb read is nice if it is real. Depending on the age of the data that you are looking at here do you have any way of verifying if that read is real without assembly?

**Comment by brianwalenz** [comment] 2019-01-04 14:19
Logging in results/*.err will report the read ID being processed (warning: this isn't flushed, so the last line might be buffered; it's just stderr/stdout if you want to rerun by hand without a redirect to a file).  Removing the read ID from *.readsToCorrect will skip this read.

If you can share the data, I wouldn't mind seeing what it's doing.  The -export option can be used to dump all the data for this read to a file -- set -r to just the troublesome read, and don't include the -R option.

**Comment by skoren** [comment] 2019-01-04 15:14
It would be strange if one read slowed it down that much, and once a read is processed there's no reason other reads would be slower. Is it possible there is something different about the node this job landed on? What's the job look like in top? Swapping and/or I/O wait? 

If you have scratch space you could turn on staging the gkpStore so the random seek is faster (whether this helps varies by FS). Also, 142 jobs for a 2gb genome seems a bit low, we typically use 1000 partition for that sized genome so perhaps also increasing the number of partitions would help.

**Comment by mschatz** [comment] 2019-01-04 19:09
Thanks guys! I isolated one of the bad reads: it consisted of GTGTGTGT... repeated for a total 1.35 million bases. Pruning it from the readsToCorrect made it move right along. And looking at the data, looks like there are a few of these junky reads in this batch, so it must have been a coincidence that only this batch had the slowdown.

Thanks again!

Mike

**Closed** 2019-01-04 19:14 UTC

**Comment by conchoecia** [comment] 2019-05-05 17:21
Is there any way to automate the process of removing bad reads that are holding up falconsense as discussed above? 

I encountered the same problem in a set of 1.7 million reads. I had some long reads > 1mbp and falconsense was stuck on the same reads for over one month. I then removed all of the reads longer than 100kbp and re-ran the correction step. It turns out that the program is still getting stuck and I am having a hard time pinpointing the offending reads.

**Comment by skoren** [comment] 2019-05-06 13:29
We routinely use 1mb reads since most of our nanopore assemblies use the ultra-long protocol. I don't think the issue is length as it is pure noise simple sequence repeats output by the base caller. These reads are usually completely artificial. You can try running sdust on the reads and filtering any where they are completely masked. You can also see exactly which read is being processed based the err logs from falcon-sense, that will report the last completed read so the next read is the offending one.

**Comment by conchoecia** [comment] 2019-08-05 14:34
I thought of a solution - what if you just flush the buffer every time a new read is being processed so that the read that is causing `falconsense` to hang is always the most recent one in the `.err` file for that job? Like you said, I found that many reads around 1mb had been processed without a hitch, and I still haven't figured out which reads are causing things to hang.

**Comment by mchaisso** [comment] 2020-01-21 22:26
I'm also hitting a case with a very slow overlapInCore step. This is running re-assembly of sequences already mapped to a genome. Could it be possible assembling lots of reads that all overlap each other in a centromere slow assembly in a way that is different from, say randomly shuffling reads?

**Comment by skoren** [comment] 2020-01-22 15:39
It's likely the source of this is a high error rate and/or high k-mer threshold. 

overlapInCore is the slowest step in Canu. First, I'd check what k-mer threshold it is setting by looking at ```0-mercounts/*.dump```, the lowest count integer there is the threshold. Limiting it manually to 5 or 10 times your coverage if it's higher than that will likely speed it up significantly (```OvlMerThreshold=<limit>```). Not sure what datatype this is but you could also try lowering the correctedErrorRate (for nanopore from the default of 12 to 10% and for PacBio to 4% for recent SequelII data).

**Comment by mchaisso** [comment] 2020-01-22 15:53
Actually I'm pretty sure there as an effect of order on runtime. When I
shuffled the reads randomly it took a few hours to run instead of days.
Unfortunately I deleted the old run with the reference-ordered contigs. If
this reference assisted assembly is a use case you're interested in, I can
regenerate and check the k-mer thresholds for you.
