### ISSUE TITLE
ovStoreSorter step failed for all of buckets

### ISSUE THREAD

**Issue by S-111** [marbl/canu#2033] opened 2021-09-29 16:03 UTC
Hi all,
I was running Canu 2.2 and ovStoreSorter step failed.
There are 271 buckets and all of those failed.
How to solve this problem?

Execution command is
```
canu \
    -p assemble -d canu \
    genomeSize=1g \
    gridEngineResourceOption='-pe def_slot THREADS -l mem_req=MEMORY' \
    gridOptions='-l medium -V -v MALLOC_ARENA_MAX=2' \
    merylMemory=200g \
    -pacbio SequelII_marged.fasta
```
One of the output file '2-sort.1.out'
All of the error in '2-sort.***.out' are the same with '2-sort.1.out'
```
Found perl:
   /usr/bin/perl
   This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi

Found java:
   /usr/bin/java
   openjdk version "1.8.0_161"

Found canu:
   /usr/bin/canu
   canu 2.2

Running job 1 based on SGE_TASK_ID=1 and offset=0.

Attempting to increase maximum allowed processes and open files.
  Max processes per user limited to 8192, no increase possible.
  Max open files limited to 8192, no increase possible.


Finding overlaps.
  found  334361160 overlaps in './assemble.ovlStore.BUILDING/bucket0001/sliceSizes'.
  found  308643962 overlaps in './assemble.ovlStore.BUILDING/bucket0002/sliceSizes'.
  found  303173517 overlaps in './assemble.ovlStore.BUILDING/bucket0003/sliceSizes'.
  found  289585522 overlaps in './assemble.ovlStore.BUILDING/bucket0004/sliceSizes'.

Loading 1235764161 overlaps using 27.62 GB of allowed (-M) 29 GB memory.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Failed with 'Aborted'; backtrace (libbacktrace):
utility/src/utility/system-stackTrace.C::82 in _Z17AS_UTL_catchCrashiP7siginfoPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
../../gcc-8.3.0/libstdc++-v3/libsupc++/vterminate.cc::95 in _ZN9__gnu_cxx27__verbose_terminate_handlerEv()
../../gcc-8.3.0/libstdc++-v3/libsupc++/eh_terminate.cc::47 in _ZN10__cxxabiv111__terminateEPFvvE()
../../gcc-8.3.0/libstdc++-v3/libsupc++/eh_terminate.cc::57 in _ZSt9terminatev()
../../gcc-8.3.0/libstdc++-v3/libsupc++/eh_throw.cc::95 in __cxa_throw()
../../gcc-8.3.0/libstdc++-v3/libsupc++/new_op.cc::54 in _Znwm()
stores/ovStoreSorter.C::200 in main()
(null)::0 in (null)()
(null)::0 in (null)()
/var/spool/uge/m03/job_scripts/13872954: Line 111: 28257 Aborted                  (core dumped) $bin/ovStoreSorter -deletelate -O ./assemble.ovlStore.BUILDING -S ../assemble.seqStore -C ./assemble.ovlStore.config -f -s $jobid -M 29
```

**Comment by skoren** [comment] 2021-09-29 16:12
This is often the result of the way memory is managed/reserved on the cluster (e.g. limiting VM) which causes the jobs to run out of memory (see #1980). As in that issue: "To confirm, you can running one of the failing jobs by hand on an interactive session with more memory reserved (currently you're using 32, try reserving 40 or 45g) and running the sort job by hand inside the BUILDING folder (sh scripts/2-sort.sh 35). If that works, you should be able to increase the ovsMemory (by adding ovsMemory=45 to your canu command)."

**Comment by S-111** [comment] 2021-09-29 16:34
Thank you very much for your response!
I tried to execute this command with 45g memory request.
'sh scripts/2-sort.sh 1'
But I got the same error message.

**Comment by skoren** [comment] 2021-09-29 16:40
Just to confirm, you started an interactive session on a compute node with 45gb memory reserved? How much memory did the job actually use before exiting (both virtual/resident)? How much free memory did the node have? Also run `qconf -sc |grep mem_req` to confirm how the memory is being reserved on the cluster.

**Comment by S-111** [comment] 2021-09-29 17:17
I made test.sh and I executed 'qsub -l mem_req=45g test.sh'
test.sh
```
#!/bin/sh
#$ -S /bin/sh
#$ -cwd
qconf -sc |grep mem_req
sh scripts/2-sort.sh 1
```
In this case, the result of the command 'qconf -sc |grep mem_req' is
```
mem_req               mem_req     MEMORY      <=       YES            YES           8          0          YES      0.000000
```
And I executed 'qreport' command, then I got these information
```
mem                  3.8                                                         
maxvmem              0.9G                                                        
r_mem                4.000G 
```
Sorry, I don't know the command to examine free memory in the executed node.

**Comment by skoren** [comment] 2021-09-29 17:45
All of that looks OK, the memory is consumable and requestable so the node should hold it as reserved on the system. The other time we've seen this error is when the previous step has corrupted output data but I don't think that's the case here because you wouldn't expect all the sort jobs to fail. 

What if you allocate a very large memory node (say 200g), does it still fail? If it still fails, are you able to share your data (the seqStore folder, assemble.ovlStore.config, and the assemble.ovlStore.BUILDING/bucket000[1-4] buckets) to reproduce the sort crash locally.

**Comment by S-111** [comment] 2021-09-30 02:55
I tried with 200g memory, I got the same error.
So, I want to share seqStore folder, assemble.ovlStore.config, and bucket000[1-4], but the total file size is 149GB.
How do I share these files...
I tried to use Google drive, but it was size over.

**Comment by skoren** [comment] 2021-09-30 11:21
Follow the FAQ: https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you to send data.

**Comment by S-111** [comment] 2021-10-01 12:14
Great!
Now I am uploading my files 'S-111_files.tar.gz', but it is taking a long time.
I will send a message here, when it finishes.

**Comment by S-111** [comment] 2021-10-05 04:25
Hi!
File upload was finished.
Can you confirm the file 'S-111_files.tar.gz'?
Thank you for your help.

**Comment by skoren** [comment] 2021-10-05 11:42
Yes, here's the file info:
```
152G Oct  4 17:24 S-111_files.tar
```

**Comment by skoren** [comment] 2021-10-05 18:53
I was able to run on the data w/o any error on a node with 60gb reserved. The jobs actually never used more than 29gb though:
```
/usr/bin/time canu-2.2/bin/ovStoreSorter -O asm.ovlStore.BUILDING/ -S assemble.seqStore/ -C assemble.ovlStore.config -M 29 -f -s 1

Finding overlaps.
  found  334361160 overlaps in 'asm.ovlStore.BUILDING//bucket0001/sliceSizes'.
  found  308643962 overlaps in 'asm.ovlStore.BUILDING//bucket0002/sliceSizes'.
  found  303173517 overlaps in 'asm.ovlStore.BUILDING//bucket0003/sliceSizes'.
  found  289585522 overlaps in 'asm.ovlStore.BUILDING//bucket0004/sliceSizes'.

Loading 1235764161 overlaps using 27.62 GB of allowed (-M) 29 GB memory.
  loading  334361160 overlaps from 'asm.ovlStore.BUILDING//bucket0001/slice0001'.
  loading  308643962 overlaps from 'asm.ovlStore.BUILDING//bucket0002/slice0001'.
  loading  303173517 overlaps from 'asm.ovlStore.BUILDING//bucket0003/slice0001'.
  loading  289585522 overlaps from 'asm.ovlStore.BUILDING//bucket0004/slice0001'.

Sorting.

Writing sorted overlaps.

  created 'asm.ovlStore.BUILDING//0001' with 1235764161 overlaps for reads 1 to 36000.
Success!
1812.78user 131.12system 32:46.04elapsed 98%CPU (0avgtext+0avgdata 29875056maxresident)k
37093008inputs+48756840outputs (5major+71303300minor)pagefaults 0swaps
```

I was also able to run partitions 2/3 in under 28gb of memory but I'm not sure those were complete since they might have some overlaps in other buckets. That said, I don't see any issues with the data or the canu sort jobs. There must be something incomplete in the grid config/memory request that's causing the jobs to fail even though they're not using more memory than you're requesting. You may need to get help from your IT group to see if there are other memory request options that should be used/included besides mem_req. Do you have a non-SGE node (or a node you can reserve exclusively for yourself that won't enforce grid memory limits) so you can run the sort jobs to confirm they work on your end?

**Comment by skoren** [comment] 2021-11-12 15:50
Idle, unable to reproduce locally so closing until we encounter a similar error again.

**Closed by skoren** 2021-11-12 15:50 UTC

**Comment by S-111** [comment] 2021-12-09 17:25
I succeeded in performing ovStoreSorter step!
In my environment, it was succeeded by specifying the same memory in qsub and -M option of 2-sort.sh.
Thank you for your kind help!

**Comment by Bordeterre** [comment] 2023-02-02 14:57
If someone else has a similar problem, increasing the genomesize argument solved the problem (
"Attempting to increase maximum allowed processes and open files.") for me
