### ISSUE TITLE
Canu 1.6 very slow compared to Canu 1.5

### ISSUE THREAD

**Issue by agroppi** [marbl/canu#613] opened 2017-09-05 09:46 UTC
As a benchmark I have launched the assembly of a vegetal genome (~270 Mb) with Canu 1.5 and Canu 1.6
With the same parameters, the same data and on the same cluster node (20 CPUs and 252 gigabytes of memory)

My commande (in a bash script) : 

`canu useGrid=false -p Sibirica_3kb -d $SLURM_SUBMIT_DIR/Sibirica_Canu_1.6_fasta_3kb corMhapSensitivity=normal corOutCoverage=50 genomeSize=270m -pacbio-raw $SLURM_SUBMIT_DIR/Sibirica_fasta_3kb/*.fasta`

The assembly with Canu 1.5 ended after 2 days

The assembly with Canu 1.6 (Canu snapshot v1.6 +13 changes (r8425 e234bb3253e280837d2d62bbdb5c1212168bcda8) is still running after almost 7 days ...
Here attached the output log
[Canu_1.6.out.zip](https://github.com/marbl/canu/files/1276891/Canu_1.6.out.zip)

Thanks for your help

**Comment by brianwalenz** [comment] 2017-09-05 11:33
Thanks for reporting.  This bit of code had a lot of work done on it just after the 1.6 release.  It looks like it is running only one job at a time, where 1.5 was (probably) running 7 to 10 jobs at a time.  Setting corThreads=2 corConcurrency=10 should fix the problem.

You'll need to remove correction/2-correction/correctReads.sh to get the number of threads change to take effect before restarting.

On the restart, it should report "10 concurrently" instead of just "1 concurrently" as below:
```
-- Starting 'cor' concurrent execution on Wed Aug 30 04:32:29 2017 with 61192.221 GB free disk space (140 processes; 1 concurrently)
```

**Comment by agroppi** [comment] 2017-09-11 09:22
Hi @brianwalenz 

Thanks for your answer.
I think I'd rather let with assembly going til the end (no time limited on my cluster)
But for the future assemblies with Canu 1.6, if I update my install from github, will the problemn be fixed ?
Or should I add the options you've suggested : `corThreads=2 corConcurrency=10`

Thanks

Bests regards

**Comment by skoren** [comment] 2017-10-20 15:57
I can confirm this is fixed in tip:
```
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'cor' concurrent execution on Fri Oct 20 11:57:13 2017 with 636907.743 GB free disk space (9 processes; 7 concurrently)
```

without manually requesting the concurrency.

**Closed by skoren** 2017-10-20 15:57 UTC
