### ISSUE TITLE
Correcting a correction

### ISSUE THREAD

**Issue by bruce-boles** [marbl/canu#588] opened 2017-08-08 15:14 UTC
Hello,

I am running the latest version of canu, and in an effort to reduce the number of contigs of a nanopore run, I have been attempting to correct a previously corrected set of reads. Is this something that is possible? I have attempted to run this multiple times, but with no success. Here was my original input:

canu -correct -p shew1correct2 -d correct2out genomeSize=4.7m -nanopore-corrected ~/Documents/bruce/correct1out/shew1correct1.correctedReads.fasta.gz'''

The program runs for a couple seconds, begins the correction and then gives me this message:
```
''' BEGIN CORRECTION
--
-- Removing empty or incomplate gkpStore 'correction/shew1correct2.gkpStore'
-- WARNING:
-- WARNING:  Existing sequence inputs used.
-- WARNING:
----------------------------------------
-- Starting command on Tue Aug  8 11:02:19 2017 with 577.078 GB free disk space

    cd correction
    /home/mikuckilab/software/canu/Linux-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o ./shew1correct2.gkpStore.BUILDING \
      ./shew1correct2.gkpStore.gkp \
    > ./shew1correct2.gkpStore.BUILDING.err 2>&1

-- Finished on Tue Aug  8 11:02:19 2017 (lickety-split) with 577.078 GB free disk space
----------------------------------------

ABORT:
ABORT: Canu snapshot v1.5 +154 changes (r8354 5e082e7ce553532e47aca7aec576bb9fc53a4809)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   gatekeeper store exists, but contains no reads.
```
I am pretty sure my file contains reads, but why would it tell me "gatekeeper store exists, but contains no reads"? Does the issue lie with the .gz being corrected? Do I need to convert it to something else? 

Thanks,

Bruce

**Comment by skoren** [comment] 2017-08-08 15:18
Possible and documented:
http://canu.readthedocs.io/en/latest/faq.html#what-parameters-should-i-use-for-my-reads

I think the issue is you are asking for correction but providing corrected reads, you should provide the corrected reads using -nanopore-raw since you want them to be treated as raw reads needing correction.

**Comment by bruce-boles** [comment] 2017-08-08 17:12
Hello skoren,

I did what it said on the website. I pretty much typed it straight in from there and its still giving me the same error message.

Original Input:
'''canu -correct -correctedErrorRate=0.075 -p shew1correct2 -d correct2out genomeSize=4.7m -nanopore-raw ~/Documents/bruce/correct1.1out/shew1correct1.1.correctedReads.fasta.gz'''

Error Message:
''' BEGIN CORRECTION
--
----------------------------------------
-- Starting command on Tue Aug  8 13:09:07 2017 with 571.973 GB free disk space

    cd correction
    /home/mikuckilab/software/canu/Linux-amd64/bin/gatekeeperCreate \
      -minlength 1000 \
      -o ./shew1correct2.gkpStore.BUILDING \
      ./shew1correct2.gkpStore.gkp \
    > ./shew1correct2.gkpStore.BUILDING.err 2>&1

-- Finished on Tue Aug  8 13:09:07 2017 (lickety-split) with 571.973 GB free disk space
----------------------------------------

ABORT:
ABORT: Canu snapshot v1.5 +154 changes (r8354 5e082e7ce553532e47aca7aec576bb9fc53a4809)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT:   gatekeeper store exists, but contains no reads.'''

**Comment by skoren** [comment] 2017-08-08 17:13
Did you remove the correct2out folder before trying the command to make sure nothing is left over from the previous run with -nanopore-corrected? What is the output in ```correct2out/correction/shew1correct2.gkpStore.BUILDING.err```

**Comment by bruce-boles** [comment] 2017-08-08 17:27
Here is what is in the folder '''correct2out/correction/shew1correct2.gkpStore.err''' :

'''Starting file './shew1correct2.gkpStore.gkp'.

  Loading reads from '/mnt/c/Users/Mikucki Lab/Documents/bruce/correct1.1out/shew1correct1.1.correctedReads.fasta.gz'
gzip: /mnt/c/Users/Mikucki.gz: No such file or directory
gzip: Lab/Documents/bruce/correct1.1out/shew1correct1.1.correctedReads.fasta.gz: No such file or directory
    Processed 0 lines.
    Loaded 0 bp from:

Finished with:
  0 warnings (bad base or qv, too short, too long)

Loaded into store:
  0 bp.
  0 reads.

Skipped (too short):
  0 bp (0.0000%).
  0 reads (0.0000%).


gatekeeperCreate finished successfully.'''

The previous correct2out was deleted before the next run. I created it so that I could keep track of my corrections.

**Comment by skoren** [comment] 2017-08-08 20:05
I think the space is confusing the run when the ~ is expanded to /mnt/c/Users/Mikucki Lab/. I'm guessing you're working on a windows machine in cygwin or similar bash emulation on windows which does a terrible job handling paths. I would try moving your input to a non-space folder and see if it runs.

**Comment by brianwalenz** [comment] 2017-08-09 12:37
Ah, no, it's even easier than that.  Supply the file of reads without a full path, just `correct1.1out/shew1correct1.1.correctedReads.fasta.gz` or wherever it is.

**Comment by brianwalenz** [comment] 2017-08-09 13:15
And it's fixed in the code now.

**Closed by brianwalenz** 2017-08-09 13:15 UTC

**Comment by bruce-boles** [comment] 2017-08-10 15:11
Thanks guy!
