### ISSUE TITLE
Canu runs but then can't find cnsjob.files

### ISSUE THREAD

**Issue by dcopetti** [marbl/canu#32] opened 2016-01-19 23:19 UTC
Hello,
I am running Canu on a small dataset of bacterial sequences (~22k short reads, from a custom library prep) using this command: canu -d /opt/Sma_Processing/Dario_Analysis/wasp_corinne -p canu_test1 genomeSize=950m minReadLength=200 minOverlapLength=100 errorRate=0.15 -pacbio-raw 017481-data-aligned_reads.fq

It crashes with this error:

/opt/Sma_Processing/Dario_Analysis/wasp_corinne/unitigging/5-consensus/consensus.sh 76 > /opt/Sma_Processing/Dario_Analysis/wasp_corinne/unitigging/5-consensus/consensus.000076.out 2>&1
--
-- Finished on Tue Jan 19 14:11:13 2016 (0 seconds) with 606.8 GB free disk space
================================================================================
Don't panic, but a mostly harmless error occurred and canu failed.

canu failed with 'can't find '/opt/Sma_Processing/Dario_Analysis/wasp_corinne/unitigging/5-consensus/cnsjob.files' for loading tigs into store: No such file or directory'.

Earlier we had issues with Gatekeeper (that now seem to be fixed): can it be that this is still related to it?
Thanks,
Dario

**Comment by brianwalenz** [comment] 2016-01-20 06:09
At least one of the consensus.sh jobs failed, but the pipeline failed to stop due to a flaw in the non-grid run mode.  The flaw was fixed a few moments ago (in e9175d86c82e122539853d093ca1cec0fef9e5db), but the consensus problem is (probably) still there.

First, in unitigging/5-consensus/, save the *.out files somewhere (mkdir old-out ; mv *.out old-out).

Then, restart canu with the same command line.  It will report which jobs failed and try to run them again.  With the list of jobs to redo, you can scan the saved *.out files for any errors (or just post them here).

**Comment by dcopetti** [comment] 2016-01-20 19:04
Hi,
The latest version installed smoothly, now there is a different error:
> /opt/canu_assembler/Linux-amd64/bin/canu 
Can't locate canu/Defaults.pm in @INC (@INC contains: /opt/canu_assembler/Linux-amd64/bin/lib/canu/lib64/perl5 /opt/canu_assembler/Linux-amd64/bin/lib/canu/lib/perl5/x86_64-linux /opt/canu_assembler/Linux-amd64/bin/lib/canu/lib/perl5 /opt/canu_assembler/Linux-amd64/bin/lib /usr/local/lib/perl5/site_perl/5.12.4/x86_64-linux /usr/local/lib/perl5/site_perl/5.12.4 /usr/local/lib/perl5/5.12.4/x86_64-linux /usr/local/lib/perl5/5.12.4 .) at /opt/canu_assembler/Linux-amd64/bin/canu line 48.

And this is what my sys admin says:
The executable is looking for this perl module inside canu perl libraries. I've searched the perl repositories and Defaults.pm is not found, so it must be a custom perl module for canu.
There is a module  Df.pm in /opt/canu_assembler/Linux-amd64/bin/lib/canu/lib/perl5/x86_64-linux/Filesys

Maybe that's the one that is needed?

**Comment by brianwalenz** [comment] 2016-01-21 02:02
Have you done a clean reinstall - remove all of /opt/canu_assembler/Linux-amd64 before 'make'?  It looks like the install is incomplete.

Defaults.pm is part of canu itself, and is (supposed to be) installed in /opt/canu_assembler/Linux-amd64/bin/lib/canu/Defaults.pm.  That path is in the @INC list (the 4th one, minus 'canu').

**Comment by alipirani88** [comment] 2016-01-21 18:02
Hi,
I am experiencing the same problem with consensus.sh. I followed the steps you mentioned in the comment "At least one of the consensus.sh jobs failed...". I couldn't find any *.cns jobs in  /unitigging/5-consensus/ but found out all the *.out files in /unitigging/5-consensus/ reports an error: "/usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found"
I ran canu on 12 samples successfully but failed for this one sample.
I was wondering if the problem is with glib version or something else.

**Comment by dcopetti** [comment] 2016-01-21 18:10
Hi Canu_developers,


We're running java 8 SE on non-grid linux server.

From a fresh download of https://github.com/marbl/canu/archive/e9175d86c82e122539853d093ca1cec0fef9e5db.zip

this is the output from doing make -j 12:

make install
ar rv ../Linux-amd64/bin/libleaff.a ../Linux-amd64/obj/libleaff.a/meryl/libleaff/fastaFile.o ../Linux-amd64/obj/libleaff.a/meryl/libleaff/fastaStdin.o ../Linux-amd64/obj/libleaff.a/meryl/libleaff/fastqFile.o ../Linux-amd64/obj/libleaff.a/meryl/libleaff/fastqStdin.o ../Linux-amd64/obj/libleaff.a/meryl/libleaff/gkStoreFile.o ../Linux-amd64/obj/libleaff.a/meryl/libleaff/merStream.o ../Linux-amd64/obj/libleaff.a/meryl/libleaff/seqCache.o ../Linux-amd64/obj/libleaff.a/meryl/libleaff/seqFactory.o ../Linux-amd64/obj/libleaff.a/meryl/libleaff/seqStore.o ../Linux-amd64/obj/libleaff.a/meryl/libleaff/seqStream.o ../Linux-amd64/obj/libleaff.a/meryl/libleaff/sffFile.o
ar: creating ../Linux-amd64/bin/libleaff.a
a - ../Linux-amd64/obj/libleaff.a/meryl/libleaff/fastaFile.o
a - ../Linux-amd64/obj/libleaff.a/meryl/libleaff/fastaStdin.o
a - ../Linux-amd64/obj/libleaff.a/meryl/libleaff/fastqFile.o
a - ../Linux-amd64/obj/libleaff.a/meryl/libleaff/fastqStdin.o
a - ../Linux-amd64/obj/libleaff.a/meryl/libleaff/gkStoreFile.o
a - ../Linux-amd64/obj/libleaff.a/meryl/libleaff/merStream.o
a - ../Linux-amd64/obj/libleaff.a/meryl/libleaff/seqCache.o
a - ../Linux-amd64/obj/libleaff.a/meryl/libleaff/seqFactory.o
a - ../Linux-amd64/obj/libleaff.a/meryl/libleaff/seqStore.o
a - ../Linux-amd64/obj/libleaff.a/meryl/libleaff/seqStream.o
a - ../Linux-amd64/obj/libleaff.a/meryl/libleaff/sffFile.o
AS_global.C: In function 'int AS_configure(int, char**)':
AS_global.C:106: error: 'CANU_VERSION_MAJOR' was not declared in this scope
AS_global.C:107: error: 'CANU_VERSION_MINOR' was not declared in this scope
AS_global.C:108: error: 'CANU_VERSION_COMMITS' was not declared in this scope
AS_global.C:109: error: 'CANU_VERSION_REVISION' was not declared in this scope
AS_global.C:110: error: 'CANU_VERSION_HASH' was not declared in this scope
AS_global.C:161: error: 'CANU_VERSION_MAJOR' was not declared in this scope
AS_global.C:162: error: 'CANU_VERSION_MINOR' was not declared in this scope
AS_global.C:163: error: 'CANU_VERSION_COMMITS' was not declared in this scope
AS_global.C:164: error: 'CANU_VERSION_REVISION' was not declared in this scope
AS_global.C:165: error: 'CANU_VERSION_HASH' was not declared in this scope
make: *** [../Linux-amd64/obj/libcanu.a/AS_global.o] Error 1
make: *** Waiting for unfinished jobs....
[root@sma src]

Tried this twice, just to be sure download was complete.
Thanks for your continued support!

All best, Ann
?
Ann Danowitz
Systems Administrator, Sr.
Arizona Genomics Institute
Sanderson Laboratories
University of Arizona
danowitz@email.arizona.edu
520.631.8727

**Comment by brianwalenz** [comment] 2016-01-22 06:30
@dcopetti @alipirani88 next time, please make new issues.  It's a lot easier for us to figure out that the problem is similar to some other problem than it is for us to keep track of which of the three or four slightly different problems we're talking about here.

@dcopetti this is fixed in 60bcb23810a559b2a03e4c5df7ec628a699ca742, thanks for reporting.  I'd also suggest cloning the repo instead of using the zip download - we're doing a lot of bugfixes and this will make reporting new ones and patching fixed ones much easier.

@alipirani88 if you were able to run on 12 other datasets, but are failing on just this one with this error, then the machine you're running on is missing the correct version of that library - perhaps an older OS install?  You can test easily by running (at the command line) the 'utgcns' program found in the same directory as the 'canu' program.  No options needed, if it runs, it'll print out the usage statement; if it fails, it'll give the error.

**Comment by dcopetti** [comment] 2016-01-22 19:03
Great news:
we were able to run Canu! we followed your latest recommendations and it run successfully on a small dataset. Thanks a lot for your prompt assistance.

Now, what are the limits of this assembler? Up to what genome size can I use it reliably? and do you know how it will compare to Falcon, or how it will behave with heterozygosity and polyploidy?
Thanks again,
Dario

**Comment by cliu6688** [comment] 2016-01-29 03:12
Dear dcopetti/dario: 

We have run into very similar problems with yours. Would you please give us more details as how you resolved this problem. The thread is little bit messy above. Did you just reinstalled a new version or did you follow the owner's instruction "
First, in unitigging/5-consensus/, save the *.out files somewhere (mkdir old-out ; mv *.out old-out).

Then, restart canu with the same command line. It will report which jobs failed and try to run them again. With the list of jobs to redo, you can scan the saved *.out files for any errors (or just post them here)."

Thanks advance for your prompt response. 

best, 

chang

**Comment by brianwalenz** [comment] 2016-01-29 16:30
Hi, Dario-

Sorry for not responding earlier.  I didn't notice your questions till now.

Limits: we've run up to 4gbp with around 60x of coverage, but it needed some attention to make it work.  3gbp runs with no issues.

It generally merges close differences into a single contig.  Some separation can be achieved by fiddling with the error rates, however, the read correction process is expected to mask many of the smaller variants.  Large differences typically end up assembled into different contigs ('bubbles').  We're currently working on GFA format output, and labeling of which output sequences are 'bubbles', 'contigs', 'repeats' and 'unassembled crud'.

Drop me an email if you want more, I'm closing this issue because it's out of control.

**Closed by brianwalenz** 2016-01-29 16:30 UTC

**Comment by dcopetti** [comment] 2016-01-29 17:15
Hi Chang,

We were able to run the software by cloning the latest repo from Github 
(60bcb23 back then), hopefully that will work for you too, or maybe in a 
newest version.
As Brian said, it is better to clone it (right click on the "copy to 
clipboard" button jus tleft of "Download ZIP") since the zip file is not 
always updated.
Best,

Dario

On 01/28/2016 08:12 PM, cliu6688 wrote:
>
> Dear dcopetti/dario:
>
> We have run into very similar problems with yours. Would you please 
> give us more details as how you resolved this problem. The thread is 
> little bit messy above. Did you just reinstalled a new version or did 
> you follow the owner's instruction "
> First, in unitigging/5-consensus/, save the *.out files somewhere 
> (mkdir old-out ; mv *.out old-out).
>
> Then, restart canu with the same command line. It will report which 
> jobs failed and try to run them again. With the list of jobs to redo, 
> you can scan the saved *.out files for any errors (or just post them 
> here)."
>
> Thanks advance for your prompt response.
>
> best,
>
> chang
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/marbl/canu/issues/32#issuecomment-176547914>.
>

-- 
Dario Copetti, PhD
Research Associate | Arizona Genomics Institute
University of Arizona | BIO5

1657 E. Helen St.
Tucson, AZ  85721, USA
www.genome.arizona.edu

**Comment by dcopetti** [comment] 2016-02-01 20:35
hi Brian,

Thanks for the feedback and the precious insights.
So it looks like Canu now would collapse small differences, like the 
ones from a heterozygous organism - good to know. I will test it with a 
selfed 380 Mb genome on our cluster.
Thanks,

Dario



On 01/29/2016 09:30 AM, brianwalenz wrote:
>
> Hi, Dario-
>
> Sorry for not responding earlier. I didn't notice your questions till now.
>
> Limits: we've run up to 4gbp with around 60x of coverage, but it 
> needed some attention to make it work. 3gbp runs with no issues.
>
> It generally merges close differences into a single contig. Some 
> separation can be achieved by fiddling with the error rates, however, 
> the read correction process is expected to mask many of the smaller 
> variants. Large differences typically end up assembled into different 
> contigs ('bubbles'). We're currently working on GFA format output, and 
> labeling of which output sequences are 'bubbles', 'contigs', 'repeats' 
> and 'unassembled crud'.
>
> Drop me an email if you want more, I'm closing this issue because it's 
> out of control.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/marbl/canu/issues/32#issuecomment-176849383>.
>

-- 
Dario Copetti, PhD
Research Associate | Arizona Genomics Institute
University of Arizona | BIO5

1657 E. Helen St.
Tucson, AZ  85721, USA
www.genome.arizona.edu
