### ISSUE TITLE
Questions about GridOptions

### ISSUE THREAD

**Issue by stopalopa** [marbl/canu#1331] opened 2019-04-17 16:03 UTC
Hi, 
I'm new to Canu and I'm a little bit confused about the grid options.  I'm using slurm and usually I submit batch jobs using a script with something like the following: 

```
#!/bin/bash
#SBATCH --job-name=canu
#SBATCH --output=canu_%j.out
#SBATCH --error=canu_%j.err
#SBATCH --mem=500G
#SBATCH --ntasks=64

canu -correct -p error_corrected -d error_corrected_reads genomeSize=3.2g -nanopore-raw nanopore_reads.fastq  useGrid=false
```
I'd like to be able to more fully use the grid, but I don't fully understand all of the options. If I submit a command with `useGrid=true and gridOptions="--mem=some value" ` then the values I put for #SBATCH tags won't matter because that only applies for the job that will be created to submit other jobs?   

According to Canu, our cluster has the following resources: 
```
-- Found   2 hosts with  64 cores and  252 GB memory under Slurm control.
-- Found  12 hosts with  64 cores and  504 GB memory under Slurm control.
-- Found   7 hosts with   8 cores and   15 GB memory under Slurm control.
-- Found   1 host  with  48 cores and  252 GB memory under Slurm control.
-- Found   2 hosts with   8 cores and   31 GB memory under Slurm control.
```

I share this cluster with other people and I'm not sure if there are any partitions set up, so what is the best way to submit jobs under grid control that won't take over the whole grid? gridEngineArrayMaxJobs? 

Last night I tried to run:
`canu -correct -p error_corrected -d error_corrected_reads genomeSize=3.2g -nanopore-raw nanopore_reads.fastq  useGrid=true gridOptions="--time=8:00:00"` so that if it did take over the whole grid then it would end hopefully before people woke up.  However, after I submitted this job, this job seemed to finish and I didn't see any other jobs start running.  Canu had output the following: 

```
-- Starting command on Tue Apr 16 23:15:05 2019 with 32213.386 GB free disk space

    cd /error_corrected_nanopore/error_corrected_reads
    sbatch \
      --depend=afterany:304880:304881 \
      --mem-per-cpu=4g \
      --cpus-per-task=1 \
      --time=8:00:00  \
      -D `pwd` \
      -J 'canu_error_corrected' \
      -o canu-scripts/canu.01.out  canu-scripts/canu.01.sh

-- Finished on Tue Apr 16 23:15:05 2019 (in the blink of an eye) with 32213.386 GB free disk space
```
Why didn't my job run? Is it just because the mem-per-cpu and cpu-per-task were lower than all of the tasks that needed to be run? 
```
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     31 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       16 GB   16 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   31 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    24 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl    24 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       15 GB    8 CPUs  (read error detection)
-- Grid:  oea        8 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      504 GB   32 CPUs  (contig construction with bogart)
-- Grid:  gfa       32 GB   32 CPUs  (GFA alignment and processing)
```

 I just tried to pick up the execution again by turning the grid off. Will that cause problems?  The other thing that I find confusing about this is that the documentation says that "Canu will auto-detect available resources and configure job sizes based on the resources and genome size you’re assembling." Why didn't Canu just figure out to use a higher mem-per-cpu? Is because of some defaults on our system (something similar to https://github.com/marbl/canu/issues/869)?

**Comment by skoren** [comment] 2019-04-17 17:12
You can't mix grid and off grid runs, you need to either run completely on the grid or off the grid. A human runs isn't going to finish overnight anyway on your cluster. Canu will request slots and its up to the cluster to manage them, it should schedule other jobs in addition to yours. If you want you can add custom grid options to lower your job priority so you can't get scheduled over other users via gridOptions.

The log you posted above has no errors so the job was submitted to your queue. If it didn't run it's possible your PBS requires some different parameters/config that is missing in the latter submit commands. Can you post the canu.out log in the grid run folder, it will have information on what happened with the latest job?

**Comment by stopalopa** [comment] 2019-04-18 14:05
So if I did mix runs, does that mean I need to restart? Will the canu.out show details of the job currently running or the last run that had stopped?  I'm still running the job that I started after resetting gridOptions back to false.  

```
Found perl:
   /home/conda/nanopore/bin/perl
   This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi

Found java:
   /home/conda/nanopore/bin/java
   openjdk version "1.8.0_192"

Found canu:
   /home/conda/nanopore/libexec/bin/canu
   Canu snapshot (snapshot)

-- Canu snapshot (snapshot)
--
-- CITATIONS
--
-- Koren S, Walenz BP, Berlin K, Miller JR, Phillippy AM.
-- Canu: scalable and accurate long-read assembly via adaptive k-mer weighting and repeat separation.
-- Genome Res. 2017 May;27(5):722-736.
-- http://doi.org/10.1101/gr.215087.116
--
-- Koren S, Rhie A, Walenz BP, Dilthey AT, Bickhart DM, Kingan SB, Hiendleder S, Williams JL, Smith TPL, Phillippy AM.
-- De novo assembly of haplotype-resolved genomes with trio binning.
-- Nat Biotechnol. 2018
-- https//doi.org/10.1038/nbt.4277
--
-- Read and contig alignments during correction, consensus and GFA building use:
--   Šošic M, Šikic M.
--   Edlib: a C/C ++ library for fast, exact sequence alignment using edit distance.
--   Bioinformatics. 2017 May 1;33(9):1394-1395.
--   http://doi.org/10.1093/bioinformatics/btw753
--
-- Overlaps are generated using:
--   Berlin K, et al.
--   Assembling large genomes with single-molecule sequencing and locality-sensitive hashing.
--   Nat Biotechnol. 2015 Jun;33(6):623-30.
--   http://doi.org/10.1038/nbt.3238
--
--   Myers EW, et al.
--   A Whole-Genome Assembly of Drosophila.
--   Science. 2000 Mar 24;287(5461):2196-204.
--   http://doi.org/10.1126/science.287.5461.2196
--
-- Corrected read consensus sequences are generated using an algorithm derived from FALCON-sense:
--   Chin CS, et al.
--   Phased diploid genome assembly with single-molecule real-time sequencing.
--   Nat Methods. 2016 Dec;13(12):1050-1054.
--   http://doi.org/10.1038/nmeth.4035
--
-- Contig consensus sequences are generated using an algorithm derived from pbdagcon:
--   Chin CS, et al.
--   Nonhybrid, finished microbial genome assemblies from long-read SMRT sequencing data.
--   Nat Methods. 2013 Jun;10(6):563-9
--   http://doi.org/10.1038/nmeth.2474
--
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_192' (from '/home/conda/nanopore/bin/java') with -d64 support.
-- Detected gnuplot version '5.2 patchlevel 6   ' (from 'gnuplot') and image format 'png'.
-- Detected 8 CPUs and 16 gigabytes of memory.
-- Detected Slurm with 'sinfo' binary in /usr/bin/sinfo.
-- Detected Slurm with 'MaxArraySize' limited to 1000 jobs.
--
-- Found   2 hosts with   8 cores and   31 GB memory under Slurm control.
-- Found  12 hosts with  64 cores and  504 GB memory under Slurm control.
-- Found   2 hosts with  64 cores and  252 GB memory under Slurm control.
-- Found   1 host  with  48 cores and  252 GB memory under Slurm control.
-- Found   7 hosts with   8 cores and   15 GB memory under Slurm control.
--
--                     (tag)Threads
--            (tag)Memory         |
--        (tag)         |         |  algorithm
--        -------  ------  --------  -----------------------------
-- Grid:  meryl     31 GB    8 CPUs  (k-mer counting)
-- Grid:  hap       16 GB   16 CPUs  (read-to-haplotype assignment)
-- Grid:  cormhap   31 GB    8 CPUs  (overlap detection with mhap)
-- Grid:  obtovl    24 GB    8 CPUs  (overlap detection)
-- Grid:  utgovl    24 GB    8 CPUs  (overlap detection)
-- Grid:  ovb        4 GB    1 CPU   (overlap store bucketizer)
-- Grid:  ovs       32 GB    1 CPU   (overlap store sorting)
-- Grid:  red       15 GB    8 CPUs  (read error detection)
-- Grid:  oea        8 GB    1 CPU   (overlap error adjustment)
-- Grid:  bat      504 GB   32 CPUs  (contig construction with bogart)
-- Grid:  gfa       32 GB   32 CPUs  (GFA alignment and processing)
--
-- In 'error_corrected.seqStore', found Nanopore reads:
--   Raw:        2813726
--   Corrected:  0
--   Trimmed:    0
--
-- Generating assembly 'error_corrected' in '/error_corrected_nanopore/error_corrected_reads'
--
-- Parameters:
--
--  genomeSize        3200000000
--
--  Overlap Generation Limits:
--    corOvlErrorRate 0.3200 ( 32.00%)
--    obtOvlErrorRate 0.1200 ( 12.00%)
--    utgOvlErrorRate 0.1200 ( 12.00%)
--
--  Overlap Processing Limits:
--    corErrorRate    0.5000 ( 50.00%)
--    obtErrorRate    0.1200 ( 12.00%)
--    utgErrorRate    0.1200 ( 12.00%)
--    cnsErrorRate    0.2000 ( 20.00%)
--
--
-- BEGIN CORRECTION
--
--
-- Mhap precompute jobs failed, tried 2 times, giving up.
--   job correction/1-overlapper/blocks/000036.dat FAILED.
--   job correction/1-overlapper/blocks/000038.dat FAILED.
--   job correction/1-overlapper/blocks/000039.dat FAILED.
--   job correction/1-overlapper/blocks/000040.dat FAILED.
--   job correction/1-overlapper/blocks/000041.dat FAILED.
--   job correction/1-overlapper/blocks/000042.dat FAILED.
--   job correction/1-overlapper/blocks/000043.dat FAILED.
--   job correction/1-overlapper/blocks/000044.dat FAILED.
--

ABORT:
ABORT: Canu snapshot (snapshot)
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
```

**Comment by skoren** [comment] 2019-04-18 14:29
Typically if you use the same prefix/folder and switch from grid to off-grid it will cause errors as the shell scripts are written to use grid environment variables which don't exist off grid. However, if it is running without error in the same folder and is outputting progress, you can leave it running

It looks from the logs like a small subset of the jobs failed, even after retries. It is possible they ran out of time, the individual logs would have more details but those could have been overwritten when you resumed off grid. Do you have files named ```correction/1-overlapper/*44*.out```?

**Comment by stopalopa** [comment] 2019-04-18 16:40
Yes.  Within the correction/1-overlapper folder I have the following: 

```
blocks		       precompute.000014.out  precompute.000042.out
mhap.000001.out        precompute.000015.out  precompute.000043.out
mhap.000002.out        precompute.000016.out  precompute.000044.out
mhap.000003.out        precompute.000017.out  precompute.304880_36.out
mhap.000004.out        precompute.000018.out  precompute.304881_38.out
mhap.000005.out        precompute.000019.out  precompute.304881_39.out
mhap.000006.out        precompute.000020.out  precompute.304881_40.out
mhap.000007.out        precompute.000021.out  precompute.304881_41.out
mhap.000008.out        precompute.000022.out  precompute.304881_42.out
mhap.000009.out        precompute.000023.out  precompute.304881_43.out
mhap.000010.out        precompute.000024.out  precompute.304881_44.out
mhap.000011.out        precompute.000025.out  precompute.304889_36.out
mhap.000012.out        precompute.000026.out  precompute.304890_38.out
mhap.sh		       precompute.000027.out  precompute.304890_39.out
partitioning.log       precompute.000028.out  precompute.304890_40.out
precompute.000001.out  precompute.000029.out  precompute.304890_41.out
precompute.000002.out  precompute.000030.out  precompute.304890_42.out
precompute.000003.out  precompute.000031.out  precompute.304890_43.out
precompute.000004.out  precompute.000032.out  precompute.304890_44.out
precompute.000005.out  precompute.000033.out  precompute.files
precompute.000006.out  precompute.000034.out  precompute.jobSubmit-01.out
precompute.000007.out  precompute.000035.out  precompute.jobSubmit-01.sh
precompute.000008.out  precompute.000036.out  precompute.jobSubmit-02.out
precompute.000009.out  precompute.000037.out  precompute.jobSubmit-02.sh
precompute.000010.out  precompute.000038.out  precompute.sh
precompute.000011.out  precompute.000039.out  queries
precompute.000012.out  precompute.000040.out  queries.tar
precompute.000013.out  precompute.000041.out  results
```
precompute.000044.out contains: 
```
Found perl:
   /galaxy/home/nzs208/conda/nanopore/bin/perl
   This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi

Found java:
   /galaxy/home/nzs208/conda/nanopore/bin/java
   openjdk version "1.8.0_192"

Found canu:
   /nfs/thumper.galaxyproject.org/home/nzs208/conda/nanopore/libexec/bin/canu
   Canu snapshot (snapshot)

Running job 44 based on command line options.
Dumping reads from 2786401 to 2813726 (inclusive).

Starting mhap precompute.

Running with these settings:
--filter-threshold = 1.0E-7
--help = false
--max-shift = 0.2
--min-olap-length = 500
--min-store-length = 0
--no-rc = false
--no-self = false
--no-tf = false
--num-hashes = 768
--num-min-matches = 2
--num-threads = 16
--ordered-kmer-size = 12
--ordered-sketch-size = 1536
--repeat-idf-scale = 10.0
--repeat-weight = 0.9
--settings = 0
--store-full-id = true
--supress-noise = 0
--threshold = 0.78
--version = false
-f = ../../0-mercounts/error_corrected.ms16.ignore.gz
-h = false
-k = 16
-p = ./000044.input.fasta
-q = .
-s =

Reading in filter file ../../0-mercounts/error_corrected.ms16.ignore.gz.
Read in values for repeat 320184 and 0
Warning, k-mer filter file has zero elements.
Initializing
Trying size 320184 and it was successfull
Initialized
Time (s) to read filter file: 3.0263650970000002
Read in k-mer filter for sizes: [16]
Processing FASTA files for binary compression...
Current # sequences loaded and processed from file: 5000...
Current # sequences loaded and processed from file: 10000...
Current # sequences loaded and processed from file: 15000...
Current # sequences loaded and processed from file: 20000...
Current # sequences loaded and processed from file: 25000...
Current # sequences loaded and processed from file: 30000...
Current # sequences loaded and processed from file: 35000...
Current # sequences loaded and processed from file: 40000...
Current # sequences loaded and processed from file: 45000...
Current # sequences loaded and processed from file: 50000...
Processed 54652 sequences (fwd and rev).
Read, hashed, and stored file ./000044.input.fasta to ./000044.input.dat.
Time (s): 2835.9791387190003
Total time (s): 2835.9794711900004
```


precompute.304890_44.out contains: 
```
Found perl:
   /galaxy/home/nzs208/conda/nanopore/bin/perl
   This is perl 5, version 26, subversion 2 (v5.26.2) built for x86_64-linux-thread-multi

Found java:
   /galaxy/home/nzs208/conda/nanopore/bin/java
   openjdk version "1.8.0_192"

Found canu:
   /nfs/thumper.galaxyproject.org/home/nzs208/conda/nanopore/libexec/bin/canu
   Canu snapshot (snapshot)

Running job 0 based on command line options.
Job partitioning error. jobid 0 is invalid.
```

**Comment by skoren** [comment] 2019-04-18 17:39
This looks like you launched the off-cluster run while the cluster run was still retrying.  The errors are all in the last few jobs and the message means it couldn't figure out which partition which would be consistent if the script was updated for the off-grid run. It is possible there was another error like a timeout on the first try but that's been overwritten by the new output. Given that the job finished in < 1hr though, I can't imagine it would hit an 8-hr time limit. Can you post precompute.sh or mhap.sh or both to confirm that?

The off-cluster run seems to be going fine and is generating files from the next step but I expect it will be quite slow on a human genome on a single node.

**Comment by stopalopa** [comment] 2019-04-18 18:39
Both the mhap.sh and precompute.sh are in the attached zip.  

This is the first time I've done this so I don't have much context.  For a human genome on a node with 500G and 64 processors, how long do you estimate it would take to just run Canu's error correcting step?  It sounds like you'd probably recommend just killing this job and restarting with the grid options?

[canu.zip](https://github.com/marbl/canu/files/3095748/canu.zip)

**Comment by skoren** [comment] 2019-04-18 19:09
Yep, this is a local shell script, the key bits of it:
```
if [ x$CANU_LOCAL_JOB_ID = x -o x$CANU_LOCAL_JOB_ID = xundefined -o 
```

So I think your cluster jobs failed due to this start of a local run which made them unable to finish. I expect the rest of the failed jobs (```precompute.30*_*.out```) will have similar errors to what you saw above. Can you upload them as a zip as well just to confirm?

The runtime will vary with coverage and read length a bit, a recent ultra-long nanopore dataset with 50x coverage took 25k cpu hours for correction. On 64 cores, that'd be a couple of weeks. In your case you've finished 12 mhap jobs, that is usually the longest compute step. The partitioning.log or the canu stdout output will tell you how many total partitions it is running (I'd guess you have about 100 or so) so you can estimate what fraction of the jobs finished since you started the local runs to estimate when all of them will finish.

**Comment by stopalopa** [comment] 2019-04-18 19:46
[precompute.30*.zip](https://github.com/marbl/canu/files/3095905/precompute.30.zip)

The data I'm working with has less coverage, but that is a long time...  

What's the difference between running with the `useGrid=true and gridOptions="--nodes=5"` vs. submitting a batch script to slurm that requests 5 nodes and has useGrid=false?  

If it's going to take that long on one node with useGrid=false and it's problematic to switch between useGrid=true and useGrid=false, I'm just wondering if there's a way for me to keep the work that's currently been done without having to wait such a long time to get results (assuming there aren't errors that require restarting anyway). 

Also, thanks so much for taking the time to look at this and get back to me!

**Comment by skoren** [comment] 2019-04-18 20:06
OK confirmed all your jobs failed for the same reason, the local job launch while the grid one was still running. It should be OK to kill the local run, remove all the shell scripts (mhap.sh/precompute.sh) and re-launch the grid run. It should resume the run. You'll have to use the job queue to monitor the job from then on or the canu.out file which will keep being updated as it runs.

You should not specify nodes in either case. Canu can only run a single compute task on shared-memory systems. When you run off grid with useGrid=false nodes=5 will just use one of your 5 nodes. When you run on the grid, Canu will submit an array to get parallelism where each job will still use one node but multiple jobs can be scheduled at the same time. Asking for more than one node will still use 1 node per job so you'd just over-reserve the cluster. It will request all the jobs it needs at once (so if you have 44 precompute jobs it will request 44 nodes). It's up to the scheduler to decide how many to schedule. You may be able to add ```gridEngineArrayOption="-a ARRAY_JOBS%50"``` or whatever value you want instead of 50 to limit the maximum number of concurrent jobs that can run simultaneously.

**Comment by stopalopa** [comment] 2019-04-19 16:27
Ok, great. So I will kill my current job, delete the bash scripts, set useGrid=true and then set gridOptions with the gridEngineArrayOption to speed up the run time while not tying up our whole cluster.  

One job can run on multiple cpus, correct? 

The last point I'm a little hazy about is that since I will now be using gridOptions, do I need to set additional parameters for the cores and memory within gridOptions, or will Canu be able to automatically figure what to request for each job? 

The documentation says that "the default gridEngineResourceOption for... Slurm it is “–cpus-per-task=THREADS –mem-per-cpu=MEMORY”. Canu will replace “THREADS” and “MEMORY” with the specific values needed for each job", which suggests to me that Canu will be able to figure it out, but it also says that "to run on the grid, each stage needs to be configured - to tell the grid how many cores it will use and how much memory it needs. Some support for this is automagic (for example, overlapInCore and mhap know how to do this), others need to be manually configured."

**Comment by skoren** [comment] 2019-04-20 17:35
One job can run on multiple CPUs as long as they share memory, yes. 

Canu will request the parameters for you so you don't need to set gridOptions for each job. Let it run with defaults as a start. It may sometimes get the request wrong in which case it will report and error and you may have to explicitly request more resources like memory.

I'm going to close the issue since it's drifted a bit from the original question so if you encounter errors in the grid run, feel free to open a new issue.

**Closed by skoren** 2019-04-20 17:35 UTC

**Comment by stopalopa** [comment] 2019-04-21 01:36
Sounds good. Thanks, Sergey!
