### ISSUE TITLE
Canu hangs at assembly stage

### ISSUE THREAD

**Issue by ggstatgen** [marbl/canu#1022] opened 2018-07-31 14:21 UTC
Hi,

I'm attempting to perform a local assembly of a complex and possibly repetitive 5mb mammal locus for which we have 13x pacbio coverage. A .5mb portion of this region does not map at all to the reference using either minimap2 or ngmlr. I have extracted all reads mapped to the region by ngmlr, as well as the 15% of the reads that were not mapped at all anywhere. I have fed the resulting fasta file to Canu 1.6. 

Canu's 'read correction' and 'read trimming' stages have successfully completed, or at least I would assume so based on the fact that the output directory now contains the folllowing two files
-local_assembl.correctedReads.fasta.gz
-local_assembly.trimmedReads.fasta.gz

However, the tool is now unable to proceed and has been stuck for a 4 days at (what I believe is) assembly stage.

This is how the final portion of the STDERR log looks like:
```----------------------------------------
-- Reset utgOvlMerThreshold from auto to 14422.
--
-- Found 921156652 22-mers; 60686529 distinct and 40057494 unique.  Largest count 1565955.
-- Finished stage 'utg-meryl', reset canuIteration.
--
-- OVERLAPPER (normal) (assembly) erate=0.045
--
----------------------------------------
-- Starting command on Mon Jul 30 10:11:41 2018 with 22747.046 GB free disk space

    cd unitigging/1-overlapper
    /scratch/canu-1.6/Linux-amd64/bin/overlapInCorePartition \
     -g  ../local_assembly.gkpStore \
     -bl 100000000 \
     -bs 0 \
     -rs 2000000 \
     -rl 0 \
     -ol 500 \
     -o  ./local_assembly.partition \
    > ./local_assembly.partition.err 2>&1

-- Finished on Mon Jul 30 10:11:41 2018 (lickety-split) with 22747.046 GB free disk space
----------------------------------------
--
-- Configured 10 overlapInCore jobs.
-- Finished stage 'utg-overlapConfigure', reset canuIteration.
--
-- Running jobs.  First attempt out of 2.
----------------------------------------
-- Starting 'utgovl' concurrent execution on Mon Jul 30 10:11:41 2018 with 22747.046 GB free disk space (10 processes; 10 concurrently)

    cd unitigging/1-overlapper
    ./overlap.sh 1 > ./overlap.000001.out 2>&1
    ./overlap.sh 2 > ./overlap.000002.out 2>&1
    ./overlap.sh 3 > ./overlap.000003.out 2>&1
    ./overlap.sh 4 > ./overlap.000004.out 2>&1
    ./overlap.sh 5 > ./overlap.000005.out 2>&1
    ./overlap.sh 6 > ./overlap.000006.out 2>&1
    ./overlap.sh 7 > ./overlap.000007.out 2>&1
    ./overlap.sh 8 > ./overlap.000008.out 2>&1
    ./overlap.sh 9 > ./overlap.000009.out 2>&1
    ./overlap.sh 10 > ./overlap.000010.out 2>&1
```
Any suggestions would be welcome.

Output of canu -version:
`Canu 1.6`

Commands attempted:
`canu  -p local_assembl -d local_assembl genomesize=350000000 -pacbio-raw reads.fa -maxMemory=250G -maxThreads=80`
`canu  -p local_assembl -d local_assembl genomesize=350000000 -pacbio-raw reads.fa -correctedErrorRate=0.105 -maxMemory=250G -maxThreads=80`
`canu  -p local_assembl -d local_assembl genomesize=350000000 -pacbio-raw reads.fa -correctedErrorRate=0.105 -corMaxEvidenceErate=0.15 -maxMemory=1000G -maxThreads=80`

System: Linux 64bits; no grid; custom computational cluster. Sample configuration log from one run (STDERR)
```
-- CONFIGURE CANU
--
-- Detected Java(TM) Runtime Environment '1.8.0_172' (from 'java').
-- Detected gnuplot version '5.0 patchlevel 5' (from 'gnuplot') and image format 'png'.
-- Detected 128 CPUs and 1007 gigabytes of memory.
-- Limited to 500G gigabytes from maxMemory option.
-- Limited to 80 CPUs from maxThreads option.
-- No grid engine detected, grid disabled.
```

**Comment by skoren** [comment] 2018-07-31 14:59
First, 13x isn't really enough do to assembly so you're not going to get a very continuous result. I'm guessing you have a WGS dataset since you're subsetting reads by mapping. If the unmapped reads are randomly distributed across the genome, you'd end up with <1x coverage of the region from 15%. Why not include all unmapped reads?

If the jobs getting CPU, then they're running and likely just slow because most of your data is from repeats. The ovlMerThreshold picked is quite high, try limit it with ovlMerThreshold=500. You can restart from the trimmed reads using ```canu -assemble ...```.

**Comment by skoren** [comment] 2018-07-31 15:29
Your original issue said "as well as the 15% of the reads that were not mapped at all anywhere", that's why I was asking where the 15% came from and why not use all unmapped reads. If you are using all unmapped reads then that makes sense to me.

The options from your commands I think makes the most sense would be:
```canu -p local_assembl -d local_assembl genomesize=350000000 -pacbio-raw reads.fa -correctedErrorRate=0.105 -maxMemory=250G -maxThreads=80
```
so just restart that command from the trimmed reads and a lowered mer threshold:
```
canu -assemble -p local_assembl -d local_assemblv2 genomesize=350000000 -pacbio-corrected local_assembl/asm.trimmedReads.fasta.gz -correctedErrorRate=0.105 -maxMemory=250G -maxThreads=80 ovlMerThreshold=100
```

**Comment by ggstatgen** [comment] 2018-07-31 15:34
Thanks - I will do that and report back

**Comment by ggstatgen** [comment] 2018-08-03 12:35
Hi again,

Unfortunately the run still hangs for days after running as above. 

As a side experiment, I launched a run where the input fasta only contained the reads mapping to the region, and did not contain the 15% of unmapped reads. This seems to suggest that some property of the unmapped reads might influence Canu runtime?

Is there any suggested filtering/pruning step you'd apply to the unmapped reads before merging them with the reads at the locus and attempting another Canu run? For example would it make sense to remove all unmapped reads shorter than say the 30 percentile of the distribution of read lengths. Also, how about removing any duplicate unmapped reads if found? Thanks!!

**Comment by skoren** [comment] 2018-08-03 16:54
I think the issue is just amount of sequencing data. I presume there are a lot more bases when you include the unmapped reads. Typically we run with the full dataset. Canu already filters reads <1kb. You could set a higher filter to get to lower input size but I expect it to still be order of 3.5g genome vs a few mb for just the reads from the targeted region.

You're running essentially a 3gb genome assembly at low coverage on a single node. That's likely to take some time (e.g. a human assembly takes 20-40k cpu hours which translates to >2 weeks at 80 cores). You could also switch to the quick option (```overlapper=mhap utgReAlign=true```) but that may give you a less contiguous assembly. Otherwise, probably easiest to just let it run.

**Comment by brianwalenz** [comment] 2018-08-08 21:35
If you get a chance, I wouldn't mind an update on what eventually worked and how the assembly turned out.

**Comment by skoren** [comment] 2018-11-07 18:47
Idle, closing.

**Closed by skoren** 2018-11-07 18:47 UTC
