### ISSUE TITLE
Low corrected data on PacBio data due to high percentage of simple repeat

### ISSUE THREAD

**Issue by baozg** [marbl/canu#1767] opened 2020-07-27 12:20 UTC
Hi Canu Developers,

I sequenced a fish genome with 100 G PacBio Sequel II data (1 SMRT cells, subreads N50 20kb)，the `genomescope` showed that the genome size was 1g with 2.1% heterozygosity and 60% repeat. But when I use the canu default parameters, it only have 16x corrected reads. Since I have assembled a high heter genome (1.8%), the canu corrected the longest 40x reads with default parameters. So I used the `wtdbg2` assembled the genome, the RepeatMasker showed the genome have 11.92 % sequence are simple repeat. Do you have any advice on how to assemble such complex genome (Or how can I tune the parameters to have more corrected data to do assembly)

Thank you

- Canu command && report
```bash
canu -correct \
-p fish -d fish \
genomeSize=1000m \
-pacbio-raw pacbio.subreads.fasta.gz \
useGrid=true \
gridOptions="-V -S /bin/bash -q all.q" \
gridEngineThreadsOption="-pe smp THREADS" \
gridEngineMemoryOption="-l mem_free=MEMORY" \
minReadLength=5000 \
minOverlapLength=1000 \
ovsThreads=8 \

[CORRECTION/READS]
--
-- In sequence store './fish.seqStore':
--   Found 5515328 reads.
--   Found 95710664400 bases (95.71 times coverage).
--
--   Read length histogram (one '*' equals 23739.08 reads):
--     5000   9999 1661736 **********************************************************************
--    10000  14999 1238008 ****************************************************
--    15000  19999 858931 ************************************
--    20000  24999 593518 *************************
--    25000  29999 422269 *****************
--    30000  34999 306308 ************
--    35000  39999 200317 ********
--    40000  44999 116888 ****
--    45000  49999  61290 **
--    50000  54999  29910 *
--    55000  59999  13635 
--    60000  64999   6302 
--    65000  69999   2909 
--    70000  74999   1542 
--    75000  79999    775 
--    80000  84999    472 
--    85000  89999    229 
--    90000  94999    122 
--    95000  99999     59 
--   100000 104999     34 
--   105000 109999     24 
--   110000 114999     13 
--   115000 119999      6 
--   120000 124999      8 
--   125000 129999      5 
--   130000 134999      5 
--   135000 139999      2 
--   140000 144999      1 
--   145000 149999      1 
--   150000 154999      2 
--   155000 159999      2 
--   160000 164999      1 
--   165000 169999      2 
--   170000 174999      0 
--   175000 179999      0 
--   180000 184999      1 
--   185000 189999      0 
--   190000 194999      0 
--   195000 199999      0 
--   200000 204999      0 
--   205000 209999      1

[CORRECTION/MERS]
--
--  16-mers                                                                                           Fraction
--    Occurrences   NumMers                                                                         Unique Total
--       1-     1         0                                                                        0.0000 0.0000
--       2-     2  25562491 *****                                                                  0.0120 0.0005
--       3-     4  96185098 **********************                                                 0.0312 0.0018
--       5-     7 214342991 *************************************************                      0.0879 0.0076
--       8-    11 296930427 ********************************************************************   0.1936 0.0241
--      12-    16 301336044 ********************************************************************** 0.3283 0.0555
--      17-    22 263077683 *************************************************************          0.4617 0.0998
--      23-    29 215645565 **************************************************                     0.5783 0.1527
--      30-    37 170536545 ***************************************                                0.6743 0.2101
--      38-    46 130909032 ******************************                                         0.7506 0.2684
--      47-    56  98221263 **********************                                                 0.8094 0.3244
--      57-    67  73059348 ****************                                                       0.8537 0.3759
--      68-    79  54389937 ************                                                           0.8867 0.4221
--      80-    92  40724435 *********                                                              0.9114 0.4630
--      93-   106  30710986 *******                                                                0.9300 0.4989
--     107-   121  23345688 *****                                                                  0.9441 0.5302
--     122-   137  17918767 ****                                                                   0.9548 0.5576
--     138-   154  13893980 ***                                                                    0.9630 0.5815
--     155-   172  10861976 **                                                                     0.9694 0.6024
--     173-   191   8557212 *                                                                      0.9744 0.6207
--     192-   211   6828535 *                                                                      0.9784 0.6368
--     212-   232   5525795 *                                                                      0.9815 0.6510
--     233-   254   4540307 *                                                                      0.9841 0.6638
--     255-   277   3772823                                                                        0.9862 0.6752
--     278-   301   3138512                                                                        0.9879 0.6856
--     302-   326   2629991                                                                        0.9894 0.6951
--     327-   352   2206667                                                                        0.9906 0.7036
--     353-   379   1879724                                                                        0.9916 0.7114
--     380-   407   1613975                                                                        0.9925 0.7186
--     408-   436   1398144                                                                        0.9933 0.7252
--     437-   466   1214762                                                                        0.9939 0.7313
--     467-   497   1057070                                                                        0.9945 0.7370
--     498-   529    923344                                                                        0.9950 0.7424
--     530-   562    813964                                                                        0.9954 0.7473
--     563-   596    723117                                                                        0.9958 0.7519
--     597-   631    644578                                                                        0.9961 0.7563
--     632-   667    579241                                                                        0.9964 0.7604
--     668-   704    522169                                                                        0.9967 0.7643
--     705-   742    472819                                                                        0.9969 0.7681
--     743-   781    425858                                                                        0.9972 0.7716
--     782-   821    384783                                                                        0.9974 0.7750
--
--           0 (max occurrences)
-- 95616164104 (total mers, non-unique)
--  2132748428 (distinct mers, non-unique)
--           0 (unique mers)

[CORRECTION/LAYOUT]
--                             original      original
--                            raw reads     raw reads
--   category                w/overlaps  w/o/overlaps
--   -------------------- ------------- -------------
--   Number of Reads            4878699        636629
--   Number of Bases        87299153735    7102927308
--   Coverage                    87.299         7.103
--   Median                       14983          9244
--   Mean                         17893         11157
--   N50                          22619         15492
--   Minimum                       5000             0
--   Maximum                     208969        108670
--   
--                                        --------corrected---------  ----------rescued----------
--                             evidence                     expected                     expected
--   category                     reads            raw     corrected            raw     corrected
--   -------------------- -------------  ------------- -------------  ------------- -------------
--   Number of Reads            5067406        1463612       1463612          80758         80758
--   Number of Bases        90684748756    42664979641   40000014090      872510268     851701997
--   Coverage                    90.685         42.665        40.000          0.873         0.852
--   Median                       14962          27013         25187          10506         10301
--   Mean                         17895          29150         27329          10804         10546
--   N50                          22562          30068         27640          12156         12027
--   Minimum                       5000          17814         17813           5002          5001
--   Maximum                     208969         180071        169582          37711         17813
--   
--                        --------uncorrected--------
--                                           expected
--   category                       raw     corrected
--   -------------------- ------------- -------------
--   Number of Reads            3970958       3970958
--   Number of Bases        50864591134   23081423087
--   Coverage                    50.865        23.081
--   Median                       11150          5073
--   Mean                         12809          5812
--   N50                          14736         11821
--   Minimum                          0             0
--   Maximum                     208969        208968
--   
--   Maximum Memory          2701973732

[TRIMMING/READS]
--
-- In sequence store './fish.seqStore':
--   Found 777838 reads.
--   Found 16302663042 bases (16.3 times coverage).
--
--   Read length histogram (one '*' equals 2236.88 reads):
--        0   4999  50443 **********************
--     5000   9999  83215 *************************************
--    10000  14999  77557 **********************************
--    15000  19999 156582 **********************************************************************
--    20000  24999 152724 ********************************************************************
--    25000  29999 111652 *************************************************
--    30000  34999  74547 *********************************
--    35000  39999  40755 ******************
--    40000  44999  18575 ********
--    45000  49999   7619 ***
--    50000  54999   2684 *
--    55000  59999    847 
--    60000  64999    304 
--    65000  69999    134 
--    70000  74999     75 
--    75000  79999     44 
--    80000  84999     26 
--    85000  89999     15 
--    90000  94999      8 
--    95000  99999      3 
--   100000 104999      3 
--   105000 109999      3 
--   110000 114999      2 
--   115000 119999      3 
--   120000 124999      6 
--   125000 129999      3 
--   130000 134999      2 
--   135000 139999      2 
--   140000 144999      1 
--   145000 149999      0 
--   150000 154999      1 
--   155000 159999      2 
--   160000 164999      0 
--   165000 169999      1



```

- RepeatMasker result

```bash
Total Length: 1325690634 bp
Class                  Count        bpMasked    %masked
=====                  =====        ========     =======
                      ---------------------------------
    total interspersed 0            0            0.00%

Low_complexity         135619       13829252     1.04%
Simple_repeat          1828985      157962811    11.92%
---------------------------------------------------------
Total                  1964604      171792063    12.96%


```

Best wishes
Zhigui Bao

**Comment by skoren** [comment] 2020-07-27 19:47
I'd guess the issue isn't repeats but data quality/high heterozygosity which essentially means your genome size is lower to 2gb not 1gb. For heterozygous genomes we recommend increasing the reads to be corrected. I'd re-run with ```corMhapSensitivity=normal corOutCoverage=80```

**Comment by skoren** [comment] 2020-09-02 14:11
Idle, should be fixed by heterozygous parameters.

**Closed by skoren** 2020-09-02 14:11 UTC
