### ISSUE TITLE
How do I get a separate gkpStore database?

### ISSUE THREAD

**Issue by wynhhh** [marbl/canu#2064] opened 2021-12-10 07:50 UTC
Hi, many thanks for developing Canu.

My question is how do I get a separate gkpStore database by performing the following step: load read into read database to get gkpStore.

We are using canu v1.6 and working in a Linux environment.

Any input would be appreciated.
Thanks!

**Comment by skoren** [comment] 2021-12-10 18:46
I'm not sure what you're asking. A separate gkpStore from what? The store is built using the `gatekeeperCreate` command, run it w/o options to see usage. You can't just replace a gkpStore in the middle of a run of Canu though, that wouldn't work. I'd also advice against using 1.6 as it's very old.

**Comment by wynhhh** [comment] 2021-12-11 13:27
Hello @skoren :
I am an absolute beginner.I am planning to try canu(v.2.2) using the B.taurus dataset to do trio binning assembly. 

There are Illumina short-read sequencing pair-end files for parents (Angus_1.fasta, Angus_2.fasta and Brahman_1.fasta, Brahman_2.fasta). I merger these two fasta file into a single Angus (Brahman) fasta file, i use Angus.fasta(~52X Illumina coverage) and Brahman.fasta(~56X Illumina coverage), and F1_Sequel.fasta(~68× PacBio coverage for their male F1 offspring) as input files of TrioCanu. 

For this command:
canu \ 
-p BOS -d bosTrio \ 
genomeSize=3g \ 
-haplotypeBrahman Brahman.fasta \ 
-haplotypeAngus Angus.fasta \ 
-pacbio F1_Sequel.fasta

My output directory looks like this:

![image](https://user-images.githubusercontent.com/28442418/145677300-b56f29a3-5f14-41f5-a365-d4ca8e38d750.png)

At present, the program is stuck in the place 'meryl' (meryl-count) and has not output any files for a long time. I would like to ask you whether my input parameters are missing or what other problems may exist. 

![1](https://user-images.githubusercontent.com/28442418/145678264-6eef2359-d112-45f4-8b43-bef0f4e694cd.png)

![微信图片_20211211212146](https://user-images.githubusercontent.com/28442418/145678267-89f2a5a6-0b86-40df-a288-459a79f77e0f.png)

Any input would be appreciated.
Thanks!

**Comment by skoren** [comment] 2021-12-18 01:22
If there's no error reported, then the jobs are running and there's nothing to do. You can look at their individual output files and/or the load on your system to see how much CPU they are using.

**Comment by skoren** [comment] 2021-12-19 01:28
Duplicate of #2067

**Closed by skoren** 2021-12-19 01:28 UTC
