### ISSUE TITLE
Consensus jobs failed

### ISSUE THREAD

**Issue by Lutri22** [marbl/canu#1159] opened 2018-11-15 14:52 UTC
Hi, I am using Canu 1.6 and after 10 days of running I am getting the following error: 

```
 Using slow alignment for consensus (iteration '1').
-- Configured 77 contig and 43 unitig consensus jobs.
--
-- Consensus jobs failed, retry.
--   job ctgcns/0007.cns FAILED.
--   job ctgcns/0009.cns FAILED.
--   job ctgcns/0011.cns FAILED.
--   job ctgcns/0015.cns FAILED.
--   job ctgcns/0016.cns FAILED.
--   job ctgcns/0019.cns FAILED.
--   job ctgcns/0046.cns FAILED.
--   job ctgcns/0051.cns FAILED.
--   job utgcns/0007.cns FAILED.
--   job utgcns/0009.cns FAILED.
--   job utgcns/0012.cns FAILED.
--
--
-- Running jobs.  Second attempt out of 2.
----------------------------------------
-- Starting 'cns' concurrent execution on Thu Nov 15 13:26:53 2018 with 1473.097 GB free disk space (11 processes; 10 concurrently)

    cd unitigging/5-consensus
    ./consensus.sh 7 > ./consensus.000007.out 2>&1
    ./consensus.sh 9 > ./consensus.000009.out 2>&1
    ./consensus.sh 11 > ./consensus.000011.out 2>&1
    ./consensus.sh 15 > ./consensus.000015.out 2>&1
    ./consensus.sh 16 > ./consensus.000016.out 2>&1
    ./consensus.sh 19 > ./consensus.000019.out 2>&1
    ./consensus.sh 46 > ./consensus.000046.out 2>&1
    ./consensus.sh 51 > ./consensus.000051.out 2>&1
    ./consensus.sh 84 > ./consensus.000084.out 2>&1
    ./consensus.sh 86 > ./consensus.000086.out 2>&1
    ./consensus.sh 89 > ./consensus.000089.out 2>&1

-- Finished on Thu Nov 15 13:36:22 2018 (569 seconds) with 1486.461 GB free disk space
----------------------------------------
-- Using slow alignment for consensus (iteration '2').
-- Configured 77 contig and 43 unitig consensus jobs.
--
-- Consensus jobs failed, tried 2 times, giving up.
--   job ctgcns/0007.cns FAILED.
--   job ctgcns/0009.cns FAILED.
--   job ctgcns/0011.cns FAILED.
--   job ctgcns/0015.cns FAILED.
--   job ctgcns/0016.cns FAILED.
--   job ctgcns/0019.cns FAILED.
--   job ctgcns/0046.cns FAILED.
--   job ctgcns/0051.cns FAILED.
--   job utgcns/0007.cns FAILED.
--   job utgcns/0009.cns FAILED.
--   job utgcns/0012.cns FAILED.
--

ABORT:
ABORT: Canu 1.6

The involved consensus.*.out files contain the following error message: 

ailed with 'Aborted'; backtrace (libbacktrace):
AS_UTL/AS_UTL_stackTrace.C::102 in _Z17AS_UTL_catchCrashiP9siginfo_tPv()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
overlapInCore/libedlib/edlib.C::387 in createReverseCopy()
overlapInCore/libedlib/edlib.C::254 in _Z10edlibAlignPKciS0_i16EdlibAlignConfig()
utgcns/libcns/unitigConsensus.C::410 in _Z22generateTemplateStitchP8abAbacusP10tgPositionjdb()
utgcns/libcns/unitigConsensus.C::744 in _ZN15unitigConsensus13generatePBDAGEcbP5tgTigPSt3mapIjP6gkReadSt4lessIjESaISt4pairIKjS4_EEEPS2_IjP10gkReadDataS6_SaIS7_IS8_SE_EEE()
utgcns/utgcns.C::581 in main()
(null)::0 in (null)()
(null)::0 in (null)()
(null)::0 in (null)()
./consensus.sh: line 84: 28216 Aborted
```
I already tried to set the cnsErrorRate=0.25 but It is still failing. 

Can anyone help with this problem?

**Comment by skoren** [comment] 2018-11-15 17:34
1.6 is quite old and there have been several large changes to consensus since then that could fix this. When changing the cnsErrorRate, make sure you remove the consensus.sh script from the 5-consensus folder before re-running. Try also letting each job have more memory by setting cnsConcurrency=2.

If neither of those work, I'd suggest installing 1.8 and re-starting from the trimmed reads (```canu -assemble -pacbio-corrected oldasm/*.trimmedReads.fasta.gz```)

**Comment by Lutri22** [comment] 2018-11-16 13:37
Thank you for your suggestions. Unfortunately, I tried both of them and I couldn't beat the issue. We saw the stats of the contigs and it seems really good. It would be great if we can avoid rerunning it. Is there any way to create the contigs from the .cns files? We don't mind even if we lose those which are stopping the process.

**Comment by skoren** [comment] 2018-11-16 17:03
You've got a large number of failing jobs so I expect you can't just ignore those contigsas you'd lose some regions of the genome. 

The crash is in the early step of consensus so there isn't a way to skip it and get an intermediate result. The actual line of the error is a memory allocation, how much memory is the consensus job using and how much is available on your system in total? Try running just one failing job by hand (from the ```unitigging/5-consensus.sh``` folder run ```sh consensus.sh 7```) and monitor its memory usage.

**Comment by Lutri22** [comment] 2018-11-23 08:13
Hi, I updated to 1.8 and started a new assembly from scratch but I have a similar error. Have you got any suggestion what can be the problem? I also tested the ram issue and I don't think that is the problem. It has 1 TB ram and it is only using around 3% of it before it is failing.

The new error message is the following: 

----------------------------------------
--
-- Bogart failed, tried 2 times, giving up.
--

ABORT:
ABORT: Canu 1.8
ABORT: Don't panic, but a mostly harmless error occurred and Canu stopped.
ABORT: Try restarting.  If that doesn't work, ask for help.
ABORT:
ABORT: Disk space available:  1181.475 GB
ABORT:
ABORT: Last 50 lines of the relevant log file (unitigging/4-unitigger/unitigger.err):
ABORT:
ABORT:   optimizePositions()--     changed:   984340 reads
ABORT:   optimizePositions()--   Recomputing positions, iteration 2, with 16 threads.
ABORT:   optimizePositions()--     Reset zero.
ABORT:   optimizePositions()--     Checking convergence.
ABORT:   optimizePositions()--     converged: 5991738 reads
ABORT:   optimizePositions()--     changed:   434714 reads
ABORT:   optimizePositions()--   Recomputing positions, iteration 3, with 16 threads.
ABORT:   optimizePositions()--     Reset zero.
ABORT:   optimizePositions()--     Checking convergence.
ABORT:   optimizePositions()--     converged: 6280097 reads
ABORT:   optimizePositions()--     changed:   146355 reads
ABORT:   optimizePositions()--   Recomputing positions, iteration 4, with 16 threads.
ABORT:   optimizePositions()--     Reset zero.
ABORT:   optimizePositions()--     Checking convergence.
ABORT:   optimizePositions()--     converged: 6364955 reads
ABORT:   optimizePositions()--     changed:    61497 reads
ABORT:   optimizePositions()--   Recomputing positions, iteration 5, with 16 threads.
ABORT:   optimizePositions()--     Reset zero.
ABORT:   optimizePositions()--     Checking convergence.
ABORT:   optimizePositions()--     converged: 6388387 reads
ABORT:   optimizePositions()--     changed:    38065 reads
ABORT:   optimizePositions()--   Expanding short reads with 16 threads.
ABORT:   optimizePositions()--   Updating positions.
ABORT:   optimizePositions()--   Finished.
ABORT:
ABORT:   ==> PLACE CONTAINED READS.
ABORT:
ABORT:   computeErrorProfiles()-- Computing error profiles for 388900 tigs, with 16 threads.
ABORT:   computeErrorProfiles()-- Finished.
ABORT:
ABORT:   placeContains()-- placing 239350 contained and 775516 unplaced reads, with 16 threads.
ABORT:   placeContains()-- Placed 183962 contained reads and 160381 unplaced reads.
ABORT:   placeContains()-- Failed to place 55388 contained reads (too high error suspected) and 615135 unplaced reads (lack of overlaps suspected).
ABORT:   optimizePositions()-- Optimizing read positions for 6426452 reads in 388900 tigs, with 16 threads.
ABORT:   optimizePositions()--   Allocating scratch space for 6426452 reads (401653 KB).
ABORT:   optimizePositions()--   Initializing positions with 16 threads.
ABORT:   bogart: bogart/AS_BAT_OptimizePositions.C:202: void Unitig::optimize_initPlace(uint32, optPos*, optPos*, bool, std::set<unsigned int>&, bool): Assertion `cnt > 0' failed.
ABORT:
ABORT:   Failed with 'Aborted'; backtrace (libbacktrace):
ABORT:   utility/system-stackTrace.C::89 in _Z17AS_UTL_catchCrashiP7siginfoPv()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()
ABORT:   bogart/AS_BAT_OptimizePositions.C::202 in _ZN6Unitig18optimize_initPlaceEjP6optPosS1_bRSt3setIjSt4lessIjESaIjEEb()
ABORT:   bogart/AS_BAT_OptimizePositions.C::449 in _ZN9TigVector17optimizePositionsEPKcS1_()
ABORT:   bogart/bogart.C::468 in main()
ABORT:   (null)::0 in (null)()
ABORT:   (null)::0 in (null)()

**Comment by brianwalenz** [comment] 2018-11-23 17:03
Are you able to share this data?  I'd like to debug in detail - this was supposed to have been fixed in the 1.7.1. release, but we've seen two crashes since (yours and one here).  I'd need both the *.seqStore/ and unitigging/*ovlStore/ directories.  The seqStore has all your read data, and the ovlStore has all the overlap data.

**Comment by Lutri22** [comment] 2018-12-03 13:13
Hi, Yes I can share the data with you. Could you give me some details about how should I do it?

**Comment by brianwalenz** [comment] 2018-12-03 14:57
```
tar -cf s1159.tar *.seqStore
tar -cf o1159.tar unitigging/*.ovlStore
```
Then upload to our private FTP: https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you.  Write back when they're uploaded.

Compressing the two tar files (gzip -1 *.tar) before uploading might save some time.

(Nothing magic about the names of the tar files, just something unique.)

**Comment by Lutri22** [comment] 2018-12-04 12:20
Hey, Thank you for your help. I managed to update them. The file names are the following: o1159.tar.gz s_1159.tar.gz

**Comment by brianwalenz** [comment] 2018-12-11 00:16
Fixed, thanks for the data.  Grab the latest unreleased version from git and restart.  It should pick up with the unitig stage.

I'm interested in what you're trying to do here.  The reads are a little strange, and it didn't really assemble.  Email works if you'd rather not tell the world.

**Comment by Lutri22** [comment] 2018-12-13 11:50
Thank you for your help. I restarted it and now it is failing with the same error as the 1.6 version before (consensus step). The thing what we tried to do is combine our chromium assembly with corrected nanopore reads (~8x coverage) to get a better assembly. So I used a read simulator to fragment down the scaffolds from the chromium assembly to 5Kb and make around 20x coverage from it. Then we did the same for our nanopore data and combine them together. Now I am a bit concerned about if it can work at all with canu. Have you got any suggestion or should we just give up on it?

**Comment by skoren** [comment] 2018-12-13 16:44
Hopefully we have enough to reproduce locally from the bogart fix, we should still fix the crash in consensus even if the data is not "standard"

We considered the best ways to combine 10x and PacBio assemblies for the vertebrate genome project but never had good luck trying to merge the two assemblies (though we never tried the shredded assembly strategy). We ended up taking the PacBio assembly and scaffolding it with the 10x data (using Scaff10x) and the filling gaps either by running Arrow again or PBJelly with the option to only fill spanned gaps.

**Comment by brianwalenz** [comment] 2018-12-17 18:04
It's not fixed, but a workaround exists.  Update your code, then edit `unitigging/5-consensus/consensus.sh` to change option `-pbdagcon` to `-norealign`.  This uses the same core algorithms, but disables a currently-under-development feature.

The root cause is that your reads have large stretches of N's in them -- the reads seem to have been created from scaffolds.  Changing this option will prevent the crash, but I fear Canu will do (or has done) the wrong thing at these blocks of N, for example, assembling them out (merging two contigs in the original scaffold), or completely misassembling (jumping between scaffolds) in that area.

**Closed** 2019-03-06 22:41 UTC
Labels: bogart
