### ISSUE TITLE
Parts of pipeline where Canu is not asking for enough memory

### ISSUE THREAD

**Issue by JohnUrban** [marbl/canu#5] opened 2015-12-21 12:52 UTC
Hi,

There is no real emergency here - just documenting some areas where Canu fails in case it is of interest to you.

I have been running Canu a lot (with Slurm), and it almost never makes it all the way through by itself due to asking for too little memory at some stages (i.e. needs manual intervention). I just thought I'd create a thread to document the stages where this happens. 

Recently I cleaned out a lot of runs without noting where this happened, but I think it was mostly or entirely confined to unitigging stages. For the runs going right now, the 3-overlapErrorAdjustment stage is the offender:

SLURM PROLOG ###############################################################
Job ID : 10517491
Job Name : oea_sciara_g310m-t1[1-7]
Nodelist : node024
CPUs : 
Mem/Node : 4096 MB
Directory : /gpfs/scratch/jurban/canu/g310m/t1/sciara/unitigging/3-overlapErrorAdjustment
Started : Mon Dec 21 04:43:44 EST 2015

Initializing.
Opening gkpStore '/users/jurban/scratch/canu/g310m/t1/sciara/unitigging/sciara.gkpStore'.
Correcting reads 1 to 180871.
Reading 7334680 corrections from '/users/jurban/scratch/canu/g310m/t1/sciara/unitigging/3-overlapErrorAdjustment/red.red'.
Correcting 1183528474 bases with 5345712 indel adjustments.
Corrected 1182709611 bases with 124894 substitutions, 818971 deletions and 108 insertions.
Read_Olaps()--  Loading 34932437 overlaps from '/users/jurban/scratch/canu/g310m/t1/sciara/unitigging/sciara.ovlStore' for reads 1 to 180871
Read_Olaps()--  Loaded 34932437 overlaps -- 17613972 normal and 17318465 innie.
slurmstepd: Job 10517491 exceeded memory limit (4194412 > 4194304), being killed
slurmstepd: Exceeded job memory limit
slurmstepd: *** JOB 10517491 CANCELLED AT 2015-12-21T07:00:44 *** on node024

It is now on the second Canu iteration and the OEA jobs were called with the same parameters. So they will all undoubtedly fail due to exceeding the memory limit again. I will just manually cancel all the jobs and relaunch them with more memory.

Anyway, if this happens at other stages in these or future runs, I will let you know about them here. Thank you for the awesome tool. Enjoy your holidays!

best,

 John

**Comment by brianwalenz** [comment] 2015-12-21 13:18
Yes, this has been annoying us to no end too.

We've accounted for most of the memory usage in the algorithms, but are needing to add adjustments for stuff like the program binary itself, buffers, and all the little allocations that would be tedious to account for.

I just updated both components of this to allow 25% overhead from what it thinks it needs.

**Comment by JohnUrban** [comment] 2015-12-21 21:51
Thanks for the update. Nonetheless, a currently running job just failed for exceeding memory at the same unitigging 3-oea stage using even the updated script -- i.e. still needs even more overhead apparently.

**Comment by JohnUrban** [comment] 2015-12-21 23:15
I just found another area in the pipeline not requesting enough memory:

meryl.jobSubit.sh/meryl.sh in the trimming/0-mercounts stage.

Canu requested ~19GB.

The job went up to a little over 26GB before being canceled by Slurm (<3 minutes into job). Canu tried this 3 times total before stopping (as expected).

**Comment by JohnUrban** [comment] 2015-12-22 11:32
A 3rd area of the pipeline that just failed due to exceeding the memory limit on the same run as above (that failed in trimming/0-mercounts/meryl) is the meryl job in unitigging/0-mercounts. 

In summary, so far (even with the latest updates), the areas that fail for exceeding memory are:
1. unitigging/3-overlapErrorAdjustment
2. trimming/0-mercounts/meryl
3. unitigging/0-mercounts/meryl

**Comment by brianwalenz** [comment] 2016-01-29 19:42
Are these still causing problems for you?  How much have you had to adjust?  I've not had problems here (possible that our config is more tolerant) but can increase the adjustments for you.

**Comment by JohnUrban** [comment] 2016-01-29 19:46
There are still memory issues.
I have to add these options to ensure Canu can complete without manually having to step in:
 merylMemory=30 \
 oeaMemory=8 \
 cnsMemory=30

**Comment by brianwalenz** [comment] 2016-01-29 22:12
Meryl should be fixed (in 7133228564d8113d08508a30367c0e0c9b6ebb15).  I was failing to account for some per-thread memory usage.

For now, stick with your hard coded constants for oea and consensus.  Both of these can't be limited, and we'll have to figure out better estimates.

**Comment by kehey** [comment] 2016-02-09 09:52
Okay, I think I identified the problem. Could be that it is something to do with our cluster but anyway. Submitting a single job to the cluster indeed failed:

```
qsub -pe make 16 -l vf=3.125g,h_vmem=3.125g -> requested 50g, FAILED
```

But when I boosted the memory requested, it ran fine:

```
qsub -pe make 16 -l vf=6.125g,h_vmem=6.125g -> requested 98g, SUCCESS
```

However, lowering the memory requested by java (-Xmx) inside the precompute.sh script and leaving the memory at 30g (where it failed in the pipeline), also worked fine:

```
qsub -pe make 16 -l vf=3.125g,h_vmem=3.125g -> requested 50g, SUCCESS when lowering java -Xmx to 40g
```

**Conclusion**: the java command adds 5g requested memory on top of the -Xmx40g command, as the virtual memory was nicely 45g. The tool itself only required 18.9g (see screenshot of htop of this run), but since the virtual memory reserved immediately violated the -l h_vmem=40g, it crashed instanteanously when -Xmx was 50g and h_vmem was 50g.

Solution: make the memory in the -Xmx flag lower than the memory requested on the grid

![canumemory](https://cloud.githubusercontent.com/assets/13170085/12912685/71b3c9d6-cf1a-11e5-8154-0b5d64dccd88.png)

**Comment by JohnUrban** [comment] 2016-03-03 16:13
Just updating this issue.

It does seem like using merylMemory is no longer necessary.

As you might expect, it does seem like oeaMemory is still needed.

cnsMemory was not needed on a recent run (and perhaps that means in general for my runs as this was the first time I tried excluding cnsMemory=30).

As being discussed in issue #57, I now need corMemory=30, but just for a single job out of ~149 jobs. The others do fine with the default 10-12g given.

**Comment by JohnUrban** [comment] 2016-03-16 13:47
Is there any chance of a fix (if its small) that does the following (?):
- Canu uses default corMemory for the first iteration (at which point the single job would fail).
- Then it uses corMemory=30 for the second iteration for the job that failed in the first iter.

i.e.
if Canu iter == 2:
    corMemory=30g

I've been running a bunch of Canu jobs at the same time. Using corMemory=30 significantly extends the length of that step since it can only do ~3x less jobs in parallel than default (when it only asks for 1012g). On the other hand, when running all the separate Canu jobs without corMemory=30, it inevitably iterates and crashes… This is fine since I can go back and make the change to corMemory=30 at that point and restart Canu. Nonetheless, I was thinking it would be cool if there was a Canu option anticipating that change for the second iteration.

**Comment by skoren** [comment] 2016-03-30 14:57
Th oea memory should be fixed in a recent commit f3f77b7d026b90408efbac5c3e5725d90976d98d, the sort it was using was not in place and was thus overflowing the memory requested. I've switched to in-place sorting. This should show up within 1-2 releases.

**Comment by JohnUrban** [comment] 2016-04-20 21:07
I just tried an assembly (with the most recent code) without specifying oeaMemory=8 for the first time in a long time. By default, it asked for 2g - and all oea jobs failed 3x in a row. 

So it looks like I still have to specify oeaMemory=8 (or maybe 4).

**Comment by skoren** [comment] 2016-04-20 21:08
I assume most recent code from master? The sort is only fixed in a branch.

**Comment by JohnUrban** [comment] 2016-04-20 21:09
Oh I see. Yes your assumption is correct.

**Comment by JohnUrban** [comment] 2016-05-16 16:38
Just an update to this thread:
I just submitted a job where there was not enough memory for the first meryl step in the correction phase. I think this is not something I reported before -- but if it is, please ignore.

Error in meryl.out:
```
slurmstepd: Job 12666658 exceeded memory limit (19923416 > 19922944), being killed
slurmstepd: *** JOB 12666658 ON node448 CANCELLED AT 2016-05-16T08:43:40 ***
slurmstepd: Exceeded step memory limit at some point.
```

Canu version:
```
Commit ID:
97fdb8f9d35486ddbe302efccfe4cc0d731009b9
Downloaded on:
Sat Apr 16 09:41:51 EDT 2016
```

I will try setting merylMemory to something higher than is being asked for by default.

**Comment by brianwalenz** [comment] 2016-05-17 12:27
Do you still have the logging output for this?  I think all I'd need to reproduce is the length of the reads.  I'll assume they're free of N's.

**Comment by JohnUrban** [comment] 2016-05-17 13:43
I have everything. Do you just want correction/asm.gkpStore/readlengths.txt ?

**Comment by brianwalenz** [comment] 2016-05-17 13:53
That'll work.  I don't think the logging will help, but might as well paste it in.  What was the command line used - in particular, the -M value?  Did it run with higher merylMemory?

**Comment by JohnUrban** [comment] 2016-05-17 13:58
I'm afraid to say that I am not sure which particular log you want to see.

**Comment by JohnUrban** [comment] 2016-05-17 14:01
This was the meryl command:

meryl \
  -B -C -L 2 -v -m 16 -threads 8 -memory 15564 \
  -s asm/correction/asm.gkpStore \
  -o asm/correction/0-mercounts/asm.ms16.WORKING \

It has not yet run with the higher memory due to priority issues in queue.

**Comment by brianwalenz** [comment] 2016-05-17 14:02
Whoops, sorry.  Somewhere there is a meryl.err or some such log.  Possibly the only logging in 0-mercounts.

**Comment by JohnUrban** [comment] 2016-05-17 14:07
I see. The only things in 0-mercounts are the meryl.out files. 

The last 10 lines:
```
 Creating bucket pointers.
 Releasing 512MB from counting the size of each bucket./second
Opened '/users/jurban/scratch/canu/hybrid/pb_ontevery/g310-default-all-every/correction/g310-default-all-every.gkpStore' with 2696332 reads
 Counting mers in buckets: 2303.85 Mmers --  1.88 Mmers/second
 Creating bucket pointers.
 Releasing 512MB from counting the size of each bucket./second
Opened '/users/jurban/scratch/canu/hybrid/pb_ontevery/g310-default-all-every/correction/g310-default-all-every.gkpStore' with 2696332 reads
slurmstepd: Job 12666658 exceeded memory limit (19923416 > 19922944), being killed
slurmstepd: *** JOB 12666658 ON node448 CANCELLED AT 2016-05-16T08:43:40 ***
slurmstepd: Exceeded step memory limit at some point.
```

There is nothing seemingly useful in the canu.out.
Is there something posisbly useful in the canu-logs/ dir ?

**Comment by brianwalenz** [comment] 2016-05-17 14:32
Nope, that's the log I was after.  I was trying to see how far it got.  Multiple files of this?  Tar and xz (or whatever) the log(s) with the lengths at you leisure.  I'll attempt to reproduce here.

**Comment by JohnUrban** [comment] 2016-05-17 16:02
[forBrian.tar.gz](https://github.com/marbl/canu/files/268635/forBrian.tar.gz)

**Comment by brianwalenz** [comment] 2016-05-23 18:18
I changed the order of memory allocations to allocate a large chunk of memory after a temporary chunk is released.  The memory sizing in meryl is otherwise spot on.  It's also (supposed to be) using 20% less than what canu is requesting from slurm.

**Comment by brianwalenz** [comment] 2016-06-29 02:44
I'll declare success!  :-)

**Closed by brianwalenz** 2016-06-29 02:44 UTC

**Comment by JohnUrban** [comment] 2016-07-12 14:33
For your info: It looks like I still need to declare oeaMemory.
