### ISSUE TITLE
Error at 1-overlapper folder

### ISSUE THREAD

**Issue by dcopetti** [marbl/canu#1534] opened 2019-10-25 14:46 UTC
Hello,

@canfirtina and I are running Canu on a large, highly heterozygous plant genome.
He can provide you more details on the command used, but the error we get is the following:

"Canu failed at the correction step while generating data under “1-overlapper” folder. There are 330 sub-jobs (i.e., jobs generated by precompute) inside that folder. The output of each of these sub jobs from subjob no 79 to 330 gives me an error similar to this (below example is based on job #330):

Running job 330 based on command line options.
./precompute.sh: 1741: ./precompute.sh: /home/firtinac/tools/release/canu/sqStoreDumpFASTQ: Stale file handle
mv: cannot stat './blocks/000330.input.fasta': No such file or directory Failed to extract fasta.

Clearly it says there is no file called "'./blocks/000330.input.fasta’:” and when I check “./blocks” folder I only see files “0000XX.dat” files where XX is a number in range [00-78]. This means that it did not even generate the *.input.fasta files. I am not sure what’s causing this error."

Could you please help us figure out what is the issue here?
Thanks,
Dario

**Comment by skoren** [comment] 2019-10-25 14:49
The key is this message: 
```./precompute.sh: 1741: ./precompute.sh: /home/firtinac/tools/release/canu/sqStoreDumpFASTQ: Stale file handle
```

Your seqStore seems to have disappeared mid-run. What's your canu command, are you using staging? Post the full precompute.sh file and an ls of your seqStore folder.

**Comment by canfirtina** [comment] 2019-10-25 14:59
We use: Canu branch v1.9 +314 changes (r9524 b6c7bd2afc76b69e88cf781294e5d82246c68959)

Our canu command is the following:

`/home/firtinac/tools/release/canu/Linux-amd64/bin/canu -p 'asm_v2' 'genomeSize=2.5g' 'gridOptionsJobName=rab_v2' -nanopore-raw '/mnt/panzer/firtinac/rabiosa_assembly/ont/Rabiosa_G303_all_2kb_q7.fq' 'saveOverlaps=false' 'corOutCoverage=200' 'purgeOverlaps=dangerous' 'corMhapFilterThreshold=0.0000000002' 'corMhapOptions=--threshold 0.80 --num-hashes 512 --num-min-matches 3 --ordered-sketch-size 1000 --ordered-kmer-size 14 --min-olap-length 2000 --repeat-idf-scale 50' 'mhapMemory=60g' 'MhapBlockSize=500' 'ovlMerDistinct=0.975' 'batOptions=-dg 3 -db 3 -dr 1 -ca 500 -cp 50 -el 2000 -nofilter suspicious-lopsided' 'maxMemory=130g' 'useGrid=remote' canuIteration=1
`

I attached the [precompute.sh.txt](https://github.com/marbl/canu/files/3772606/precompute.sh.txt) file. Note that I had to add .txt extension as GitHub did not allow me to upload an .sh file.

ls of the seqStore folder is the following:

`blobs.0000  blobs.0004  blobs.0008  blobs.0012  blobs.0016  blobs.0020  blobs.0024  blobs.0028  blobs.0032  blobs.0036  blobs.0040  blobs.0044  blobs.0048  blobs.0052  blobs.0056  libraries            readlengths-cor.gp
blobs.0001  blobs.0005  blobs.0009  blobs.0013  blobs.0017  blobs.0021  blobs.0025  blobs.0029  blobs.0033  blobs.0037  blobs.0041  blobs.0045  blobs.0049  blobs.0053  errorLog    libraries.txt        readNames.txt
blobs.0002  blobs.0006  blobs.0010  blobs.0014  blobs.0018  blobs.0022  blobs.0026  blobs.0030  blobs.0034  blobs.0038  blobs.0042  blobs.0046  blobs.0050  blobs.0054  info        load.dat             reads
blobs.0003  blobs.0007  blobs.0011  blobs.0015  blobs.0019  blobs.0023  blobs.0027  blobs.0031  blobs.0035  blobs.0039  blobs.0043  blobs.0047  blobs.0051  blobs.0055  info.txt    readlengths-cor.dat`

Thanks.

**Comment by skoren** [comment] 2019-10-25 15:08
That all seems OK, I think the issue is your cluster I/O is failing and making nodes lose filesystem access. You'd have to check with your cluster IT to see what is happening on those nodes when they report the stale file handle message, but nothing in Canu could remove the seqStore mid run.

Try limiting your concurrent jobs, since you're on slurm adding ```gridEngineArrayOption="-a ARRAY_JOBS%20"``` should limit it to 20 jobs at a time. Assuming you have local disk on the compute nodes, I'd also suggest the staging option (https://canu.readthedocs.io/en/latest/parameter-reference.html#file-staging) to reduce I/O load on the main disk.

**Comment by skoren** [comment] 2019-11-13 16:33
Any updates?

**Comment by canfirtina** [comment] 2019-11-15 09:51
We started using the latest release and re-ran Canu using the same command that I posted earlier except we changed "purgeOverlaps=dangerous" to "purgeOverlaps=aggressive". Current run already successfully completed the step where it failed before.

I think we have a problem in our servers when deleting the files as it usually takes too long time to delete some files. Canu failed probably while trying to delete the files "dangerously" (e.g., it might took a long time for Canu and it failed due to a reason related to this? I am just guessing of course...). In short, Canu is currently running as intended without an issue.

**Comment by dcopetti** [comment] 2019-11-15 10:19
thank you for the update @canfirtina !

@skoren, I am wondering whether we made a mistake in specifying the expected genome size. 
Our plant has a haploid genome of about 2.5 Gb, but it is highly heterozygous for SVs made of TEs. Also a short read assembly ends up in 4.5-5 Gb (though very fragmented), so our aim is to have a 5 Gb assembly, with as much as possible of the two alleles in two separate sequences.
Do you think that now there is a discrepancy between the `corOutCoverage=200` and the `genomeSize=2.5g` that we have in the command? Should the latter be 5g? If so, do we need to restart the error correction? Do you think we can instead keep going and change the parameter for the other parts of the pipeline?

**Comment by skoren** [comment] 2019-11-15 18:12
Thanks for the info @canfirtina, I wouldn't expect that folder to ever be deleted but it may also have been a bug fixed with the release. 

@dcopetti Your settings should be OK for what you want. The genome size is just used to report statistics (NG50) and to set some initial cpu/memory parameters. Assuming you don't actually have > 200x of coverage, all your data would be corrected. You probably want the heterozygous parameters from the FAQ, which you've already included.

**Comment by skoren** [comment] 2019-11-19 21:22
Resolved per above comments.

**Closed by skoren** 2019-11-19 21:22 UTC
